### ISSUE TITLE
Changing caskroom location to system root lead to a system restore

### ISSUE THREAD

**Issue by WatermelonDriveway** [caskroom/homebrew-cask#10009]
I put `export HOMEBREW_CASK_OPTS="--caskroom=/Volumes/HD"` in my `.bashrc` and got a ton of system errors that certain extensions couldn't be used.  I wish I had the errors for you, but after a shut down I couldn't boot back up again.  I was on a fresh install of a few days, so it was definitely from changing the caskroom location.

**Comment by vitorgalvao** [comment]
I’m not really sure how we could’ve prevented that. You basically tried to put the caskroom directly on the root directory of your system. Why? You shouldn’t touch that without a very good reason. What likely happened next is that since homebrew-cask needs your permission (and asks for your password) to change the ownership of its directory, doing that screwed everything up.

The act of changing the caskroom’s location wasn’t the culprit, though, and like I said I’m not really sure how we could’ve prevented that, apart from asking if you’re really sure (because someone might indeed have an obscure reason to use the root directory of the file system) when you try to put it in certain locations.

Ideas @rolandwalker @phinze @ndr-qef?

**Comment by WatermelonDriveway** [comment]
Thanks for the response vitorgalvao.  I had no obscure reason for wanting it there, just that it would be a little easier to get to since I don't use my opt folder for anything else.  Didn't think about permissions.  I guess it's probably more common knowledge than i knew that that would be a bad place to put it, but I assumed there would be a note about it if it would cause that big of problems.  From that perspective I left this issue just to let you know the result of doing that.

**Comment by vitorgalvao** [comment]
> just that it would be a little easier to get to since I don't use my opt folder for anything else.

You’re not supposed to worry about that. That is why we link your apps to the appropriate locations. Perhaps what you were looking for was [`--appdir`, and not `--caskroom`](https://github.com/caskroom/homebrew-cask/blob/master/USAGE.md#options).

> I guess it's probably more common knowledge than i knew that that would be a bad place to put it

As a general rule, you shouldn’t be changing stuff outside your home directory (or more broadly, things that ask for your password) unless you fully understand it can mess up your system. Or you should do it actively as a learning tool, but not with data that matters to you.

> but I assumed there would be a note about it if it would cause that big of problems

Like I mentioned, I’m not really sure how we could’ve prevented that. If you do `sudo rm -r /` it also just goes ahead and starts doing it without warning. Asking for your password is a really big deterrent that the operation is dangerous. That said, we need your password momentarily by default to set the caskroom in `/opt`, so that lowers the mental barrier to inputing it for other operations related to homebrew-cask.

I’d have no quarrel with just closing this issue. However, I wouldn’t be opposed at all to a solution that made these types of occurrences harder, which is why I’d like to know if other maintainers have any ideas.

**Comment by phinze** [comment]
Ouch! Sorry you had such trouble @WatermelonDriveway. :confused:

@vitorgalvao has done a good job of explaining everything happening here so far. As for next steps, I think we can at least add a warning to the documentation around `--caskroom` explaining that it's an advanced feature and what sorts of issues to look out for.

**Comment by WatermelonDriveway** [comment]
@vitorgalvao I was not mistaking --caskroom for --appdir, I'm just intrigued by brew cask so I wanted to watch it do its magic, and liked how I had the option to change the caskroom directory.  I had no reason to change it other than messing around really, and I lost nothing of importance during the system restore.  A chflags hidden /opt is all I really needed to not have to see the opt folder.

@phinze A warning to the --caskroom documentation would have definitely prevented me from doing this, but again I'm sure if you expect most of your users to already know against messing with system root than it would be unnecessary.

Thanks for all your hard work guys, brew cask is fantastic.

**Comment by vitorgalvao** [comment]
@WatermelonDriveway To be clear, I really like what you did. The intersection of not knowing the dangers of messing with `/` but even so having the interest to learn about a CLI tool enough to find such options and actually trying them out, together with not having lost relevant data and opening a github issue to report your problem, says a lot about you. A lot of positive things.

I’m guessing you might not have a lot of programming experience and limited knowledge of unix-like systems, but if you’re interested in those things I’d say you have what matters most — a tinkerer mentality. Join that with your cordiality, and we’re looking at a fine future open-source contributor.

Naturally, I might just be extrapolating too much from a simple exchange.

That is in part why I’m really not sure what the best solution is, here. I do feel your issue is legitimate and should be addressed, but now that you know the reason it happened, you’re no longer the target for whatever the solution is. I guess we’ll just start with documenting.

**Comment by WatermelonDriveway** [comment]
Wow @vitorgalvao thank you so much.  I am definitely new to unix/CLI's and those are very encouraging words to hear for somebody trying to get involved.  You just made my week.
