### ISSUE TITLE
Golly doesn't install

### ISSUE THREAD

**Issue by lahwran** [caskroom/homebrew-cask#10155]
```
lahwran@lahwran:~$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
Already up-to-date.
Error: brew-cask 0.53.3 already installed
lahwran@lahwran:~$ brew cask install golly
==> Caveats
Cask golly installs files under "/usr/local".  The presence of such
files can cause warnings when running "brew doctor", which is considered
to be a bug in homebrew-cask.

==> Downloading http://downloads.sourceforge.net/project/golly/golly/golly-2.6/golly-2.6-mac109.zip
Already downloaded: /Library/Caches/Homebrew/golly-2.6.zip
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/golly/2.6/golly-2.6-mac109/Golly.app'
lahwran@lahwran:~$
```

**Comment by an0nym0use** [comment]
That download currently extracts to a folder called `golly-2.7b2-mac` rather than the expected `golly-2.6-mac109`. This means the symlinking can't work. Changing the `app` location lets cask symlink correctly, but the download shouldn't have the incorrect version. [Discussion post created](https://sourceforge.net/p/golly/discussion/467857/thread/50f164ca/#4e45) requesting golly maintainers to correct this.

**Comment by x1024** [comment]
It's at 2.7b3 now. The download link is no longer valid.
Consider this: https://github.com/caskroom/homebrew-cask/compare/master...x1024:patch-1

**Comment by vitorgalvao** [comment]
@x1024 Care to submit it?
