### ISSUE TITLE
Should `zap` trash user-generated content?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#10156]
I say yes. `zap` should, in my view, be considered the “nuke” option: get rid of everything. User preferences are also user-generated content (even if they don’t edit those files directly) and `zap` shouldn’t be limited to those, meaning instead “I don’t care about this app anymore and want everything gone from my system”. For a less drastic uninstallation, there’s `uninstall`.

This, naturally, would only consider user-generated content in standard locations for the apps; we’re not going to start hunting things down in the user’s system. Things should also be [trashed, not outright deleted](https://github.com/caskroom/homebrew-cask/pull/9523#issuecomment-77707173).

My proposal: when zapping, ~~make a `<appname>_zap` directory, dump everything to be zapped there, and then trash that directory~~ ([on second thought](https://github.com/caskroom/homebrew-cask/issues/10156#issuecomment-86259181)) trash every specified file and directory.

Refs https://github.com/caskroom/homebrew-cask/issues/10008 https://github.com/caskroom/homebrew-cask/pull/9523.

**Comment by jawshooah** [comment]
I am strongly in favor of every aspect of this. I've always thought of `zap` as the "get this tripe off my system" command. And trashing files solves the problem of users accidentally removing data they didn't intend to.

**Comment by RogerThiede** [comment]
I would be in favor of this as well given the following considerations:
* Articulate to the user which files are being removed as opposed to just a parent folder name
* Files are trashed, not outright deleted
* Caveats are available if it's known that the location of user-generated content could have been configured by the user and remind the user to take action themselves

**Comment by Amorymeltzer** [comment]
I really like this proposal, nicely put!  @RogerThiede's first point is particularly important if items will be moved to a new folder.

We need to be vocal about what is going on.  There is wide variability in zap-appropriate user-generated content.  I think we're all generally okay with unceremoniously `rm`ing `.plist` files in `~/Library/Preferences/` but I am much more wary of treating (often invisible) dotfiles or folders found closer to $home the same way.  Users (generally) only change `.plist`s through the app GUI, whereas dotfiles are more likely to follow a manual, hackish approach to creation.  I would be POd if `zap` `rm`ed or even trashed my `.emacs` without specifically alerting me to that fact.

Trashing is a **good solution**, but an extra warning would be appreciated for files a. likely to have a fair amount of work put into them, and b. likely to be invisible should the user review said trashed-folder via GUI or without the `ls` `-aA` flags.  I think the workflow for creating files is important to how we treat them, as is alluded to: files/folders generally made through/by the app are generally okay; those generally made manually should be carefully tread.

Additionally, and this is perhaps less important, would this be expected behavior?  I'm not saying it isn't good, but if someone has a button that is the nuclear-option delete, in a command-line setting, when else is a new folder generated, placed in `~/.Trash`, and the user prompted for review?  It's a tad unorthodox, if you will.  Again, I think it's a good idea, but it may not be expected behavior on the part of users.  `zap --nuke` might be a solution but, eh.

**Comment by vitorgalvao** [comment]
> @RogerThiede's first point is particularly important if items will be moved to a new folder.

My initial thought was to preserve the original directory structure inside that directory. Now, on second thought, they should likely just be trashed, as that allows for the OS’s “Put Back” functionality.

> Additionally, and this is perhaps less important, would this be expected behavior? I'm not saying it isn't good, but if someone has a button that is the nuclear-option delete, in a command-line setting, when else is a new folder generated, placed in `~/.Trash`, and the user prompted for review? It's a tad unorthodox, if you will. Again, I think it's a good idea, but it may not be expected behavior on the part of users. `zap --nuke` might be a solution but, eh.

`zap` itself is a wording taken from other software (`AppZapper`) and doesn’t have much meaning outside that connection. In that sense, acting as closely as it does (trashing instead of deleting) seems like it’d be the least confusing option.

**Comment by w-hive** [comment]
Yes please make the zap stanza remove *everything*

**Comment by vitorgalvao** [comment]
Decided as yes. Zapping should remove everything.
