### ISSUE TITLE
Fail to download balsamiq-mockups. Error 403.

### ISSUE THREAD

**Issue by nuthingman** [caskroom/homebrew-cask#10192]
Already did:
```
brew doctor
brew update
brew upgrade
```
But keep getting this error message:
```
$ brew cask install balsamiq-mockups
==> Downloading https://s3.amazonaws.com/build_production/mockups-desktop/Balsam

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'balsamiq-mockups' with message: Download failed: https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.0.3.dmg
```

**Comment by sheedy** [comment]
@vitorgalvao I suspect this is because the S3 URL for Balsamiq is versioned. 

I just updated cask and it is still referring to version `3.0.8` at `https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.0.8.dmg` ([download](https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.0.8.dmg) breaks).

The current version is `3.1.1` (as of today) at `https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.0.8.dmg` ([download](https://s3.amazonaws.com/build_production/mockups-desktop/Balsamiq_Mockups_3.1.1.dmg) works).
