### ISSUE TITLE
Prefer checksummed versioned or no_checksum latest casks?

### ISSUE THREAD

**Issue by phinze** [caskroom/homebrew-cask#1021]
This issue comes from a long discussion in #1011 between @gregstallings @vitorgalvao @NanoXD and @passcod.

If anybody believes the core issue to be different than the one I've titled; please let me know and I'm happy to edit.

----

Here's the way I put it over there:

> For a given cask, if we have available both latest / no_checksum and versioned / checksummed URLs, which should we prefer?

So to lay out some differences...

### **Preferring latest**

 * :+1: Maintainers don't have to deal with PRs for every cask update.
 * :+1: / :-1: For apps with autoupdate, users don't interact with homebrew-cask for upgrades. (Some users may prefer this usage model; other may prefer homebrew-cask to be a one-stop-shop package manager.)
 * :-1: There's no checksum protecting the download from MITM.

### **Preferring checksummed**

 * :+1: Checksums protect the downloads from tomfoolery and skullduggery :skull:.
 * :+1: / :-1: For upgrades, homebrew-cask manages different versions.
 * :-1: Maintainers + contributors need to process update PRs more often.

-----

There are a few things I'd like to highlight as we continue this conversation:

### Users and Maintainers are Different

There is an important distinction between *user benefit* and *maintainer benefit*. I believe we should strive for both, but in situations where they are at odds where should always prefer users over maintainers (within reason). Obviously hours of maintainer work for a minor user benefit is a bad idea. But something somewhat inconvenient for maintainers that provides a major benefit to users deserves to be considered.

Mostly I want to make sure we distinguish the two in our conversations about features and stuff, so we can properly talk about the needs of the two groups.

### There was one more thing but now I've forgotten it.

Maybe it will come back to me. :blush:

**Comment by phinze** [comment]
Closing this as I think the core maintainers are all on the same page. @rolandwalker's last update accurately represents the state of the union. Anybody who disagrees is welcome to chime in and we can talk about reopening. :ok_hand:

**Comment by Yann-R** [comment]
@rolandwalker 
> There will always be some cases where 'latest' is the only sensible approach, or the only possible approach. So we will never lose it entirely. If those remaining 'latest' Casks are more difficult to upgrade, that's just a compromise we will have to accept. The perfect is the enemy of the good.

Do you mean that when the download URL of the binary contains no version (e.g. http://company.com/download/latest_version.dmg) we must go to unversioned formula?

I am fully aware that a set of expert contributors to homebrew-cask are already thinking of a design of automatic-update mechanism, and I thank them for their efforts that should lead to a future solution.

But meantime, `brew cask install installed_formula` is a very acceptable workaround for many users like me, that gives a way to get an update of all their installed software in a not so bad way (like `brew cask install`\``brew cask list`\`). Nevertheless this can not work with the general use of `:latest` in formulae (used by around 950 casks out of 2400).
During this meantime, from a user point of view, the proposal @doits sounded interesting:
> - apps that have direct urls to each version and provide old version: checksum, link to version directly
> - apps with only the latest download url: no checksum, link to latest url
> - always a specific version in the file (no "latest" version), updated when new version of program is released

With this proposal, current formulae with `:latest` as version and `:no_check` for the hash would switch to numbered version and `:no_check`. 
This wouldn't break the formula that remains possible to install for any user. But it keeps also the possibility for the maintainer to trigger an update for every user who installed this software by increasing the version number in the formula.

The drawback being that the cask could be stored in a subfolder named x.y.z whereas the installed version is a newer one. If this is really a problem, a possible solution for this could be inspired from above proposals. Why not write '`>= x.y.z`' as version in the formula, instead of only '`x.y.z`'.
This would make it possible for homebrew-cask to:
- understand it should keep 'latest' as destination folder, but keeping the version number '`x.y.z`' stored in an auxiliary file in the caskroom
- and to take this version from the formula into account, to download the new version if it changed.

Isn't it sensible meantime, before a real update mechanism?
