### ISSUE TITLE
Add support for mirror URLs

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-cask#10241]
I can imagine there's a decent number of packages that have multiple (official) sources - download URLs and we should not limit ourselves to a single URL.

It may not be easy to add such functionality consider the Homebrew ruins we still have in the codebase, but I merely wanted to open the discussion in the first place to see if there's interest in such feature.

The initial implementation can be just to support array of URLs in `url` stanza, later on we can add things like weight/priority, some timeouts per each mirror etc.

Any suggestion/objections?

Related issues:

 - #3043
 - #10264

**Comment by jawshooah** [comment]
Assuming that since this isn't a PR, it's okay to comment ahead of maintainers.

I'm all for this idea, as there have already been [complaints](https://github.com/caskroom/homebrew-cask/issues/9934) about download speeds after switching to new hosts.

Would a simple `mirror` stanza _à la_ Homebrew work?

**Comment by vitorgalvao** [comment]
I’m not in favour, due to the added overhead for maintainers. Mirrors means we’ll have to verify the download sources every time for those casks. Adding a url from a different source from the official is already risky if the vendor ever goes somewhere different and some malicious source can reuse that old url, let alone specifically inviting those urls unnecessarily.

It also may or not make it harder to use `#{version}` and variants (probably not, most of the time) and `appcasts` (those will be handled automatically, in the future, but mirrors will be left in the dust).

Don’t get me wrong (and I believe I’ve been very consistent on these matters, so my views should be clear if you’ve found them before); I’m all for improving the life of the user first, but every little thing we add is not only another barrier for user submissions, it’s also another barrier for us to merge contributions quickly, and that benefits no one.

In sum, I don’t believe the lack of mirrors to be a big enough issue to justify the overhead.

**Comment by w-hive** [comment]
@vitorgalvao Want to suggest #10264 as a possible remedy for this.

"malicious" should not ever be an issue with binaries, since you're verifying the hash anyway, right?

**Comment by radeksimko** [comment]
@vitorgalvao Some of your concerns are valid.

When I say mirror, I actually mean official mirror, I don't want to see unofficial mirrors in here in Cask either. Too risky by definition.

Re: `version` - I'd expect that if something is called mirror, it will behave exactly the same way = have always the same versions as another mirror. If not, it's not a mirror.

Re: `appcast` - I wonder how packages with apcasts solve the problem of mirrors, whether anyone puts multiple URLs in the appcast feed... in that sense it's a valid concern and this question would need to be answered.

**Comment by w-hive** [comment]
@radeksimko If a hash is (for example) required, where is the risk in mirrors?

**Comment by radeksimko** [comment]
@w-hive We need to make sure the Cask is friendly to vendors (even though some of them are not making our work easy), therefore we should respect them if they want to distribute their SW through a limited set of channels, if we won't, we risk being approached by them with a request of removal of their SW because we do something they don't like.

Maybe better to reword "official" to "officially approved".

**Comment by vitorgalvao** [comment]
@w-hive that won’t solve the issue, as metalinks would still need to be provided officially anyway, and I don’t usually find those in the wild. It’d work on a too small scale to be an answer to the original point (mirrors). In addition, there seems to be [no support for it in curl](http://daniel.haxx.se/blog/2008/04/08/no-metalink-in-libcurl/), which is what we use and will [continue to for the foreseeable future](https://github.com/caskroom/homebrew-cask/issues/5552#issuecomment-69501349).

> "malicious" should not ever be an issue with binaries, since you're verifying the hash anyway, right?

Not in every cask. Some we can’t, as the link always point to a versionless url.

@radeksimko Yes, I was also referring to official mirrors, but as maintainers we still have to check those (and to an extent care they continue valid) as being official, like [we currently do](https://github.com/caskroom/homebrew-cask/blob/8dba4ca011c49a471c47f364fe8712a64b962136/Casks/xampp.rb#L5) for other casks. [Keeping those in check is already a huge pain](https://github.com/caskroom/homebrew-cask/pull/9098) (and I’ve since saw a few slip through, which will make corrections that much harder), and inviting a few extra ones in casks that don’t need that comment is, I believe, something that’ll give more work than benefit.

> Re: `version` - I'd expect that if something is called mirror, it will behave exactly the same way = have always the same versions as another mirror. If not, it's not a mirror.

Yes, I was thinking about “`#{version}` and variants” (i.e. string interpolation) specifically. The content of the mirror should be the same, but the ur structure might not (e.g. there are casks that have a vendorless download link on the website, and then a versioned on github). Like I said, those shouldn’t pose a big issue most of the time, but they do exist.

**Comment by radeksimko** [comment]
@vitorgalvao Hmmm, the long-term maintenance overhead is a valid concern, I agree.

Having said that, @rolandwalker was trying to implement something in https://github.com/caskroom/homebrew-cask/pull/3043 , not sure what was the original intention behind it though and whether you guys discussed these concerns at that time?

**Comment by vitorgalvao** [comment]
The intent of that issue [is different](https://github.com/caskroom/homebrew-cask/pull/3043#issuecomment-39326569).

> cases like distributions which logically belong together but happen to comprise multiple URLs. Examples: Multi-file RAR archives, Font families.

**Comment by vitorgalvao** [comment]
Closing for lack of interest/implementation. This is definitely not urgent and can be revisited at a later date.

**Comment by pacav69** [comment]
After reading this discussion then i think that mirrors option might not be a suitable alternative for my idea of an offline install of apps.

**Comment by Saklad5** [comment]
I think metalinks would be helpful for certain Casks. The ability to use partial hashes makes it trivial to ensure that mirrors are all giving the same file, and we can always err on the side of removing or ignoring mirrors when they diverge or don’t follow a predictable URL format.

I agree that this is not a particularly urgent feature, but I believe it is worth implementing eventually. Mirrors are often given for a reason, and the current approach may put undue strain on the vendor’s servers.

As for maintenance, the metalink schema is specifically designed with the idea that some servers may be down or invalid. We can just hash the download from the vendor when updating, and metalink will automatically ignore any pieces that don’t fit from various mirrors.

In fact, I feel that metalinks should be used for all Casks by default, whether or not mirrors are available. Partial hashes are extremely useful for both resuming and verifying downloads, and plenty of other package managers already use metalinks for similar reasons.
