### ISSUE TITLE
Andyroid -- Missing symlink source

### ISSUE THREAD

**Issue by andres-rojas** [caskroom/homebrew-cask#11053]
```Shell
➜  ~  brew cask install andy --verbose
==> Downloading http://andyroid.vonetize.com.edgesuite.net/Mac/v43/Andy_OSX_v43.dmg
/usr/bin/curl -fLA Homebrew-cask v0.51+ (Ruby 2.0.0-481) http://andyroid.vonetize.com.edgesuite.net/Mac/v43/Andy_OSX_v43.dmg -C 0 -o /Library/Caches/Homebrew/andy-43.dmg.incomplete
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  552M  100  552M    0     0   393k      0  0:23:56  0:23:56 --:--:--  852k
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/andy/43/Andy.app'
```

This may be related to issue #1249

**Comment by vitorgalvao** [comment]
It’s not related. The error simply means the thing inside the package it was trying to link no longer is there (likely, it changed it’s name). The fix is simply to correct that part in the cask.

**Comment by aramkarapetian** [comment]
+1

**Comment by vitorgalvao** [comment]
@aramkarapetian Please don’t “+1” issues.

Don’t any of you want to take a stab at fixing this? Download the `dmg`; the cask is assuming a `Andy.app` app on the root directory of it; it isn’t there, so the path has to be fixed.

**Comment by aramkarapetian** [comment]
hi vitorgalvao, sorry for that, I'd love to fix it. will give it a try soon

**Comment by vitorgalvao** [comment]
#12847.

**Comment by eyalfishler** [comment]
@vitorgalvao i'm the CTO of AndyOS and we will PR a new Andy OSX version (46.2) in the next few days.
As we want all the versions we release (OSX,Win,Ubuntu) to be live at the same time and also on cask, is there a way i can ping you to accept the PR faster?
Thanks.

**Comment by vitorgalvao** [comment]
@eyalfishler We’re usually pretty fast about merging PRs and span a few timezones, but with the festivities I can’t guarantee anything without further details of when exactly you want to release it, since we’re all volunteers.

What you can do is open the PR earlier than the actual release (the day before, or something), and specify the time and day you’d want it to be merged (link back to this discussion). That way, some maintainer can predict if they’ll be available and willing at the time.

After that, all you’d need to do is @mention us, and we’d merge it.
