### ISSUE TITLE
Localized version support

### ISSUE THREAD

**Issue by gmkey** [caskroom/homebrew-cask#11367]
Being a relative n00b for homebrew and homebrew-cask I noticed that homebrew-cask doesn't support internationalized releases of apps. E.g. firefox and thunderbird are both released in versions per locale, the default being: en-US. As a dutch national, I'd prefer not to download the en-US version, but the nl version. However this doesn't apply for all applications (some have the internationalisation embedded). 

I can think of several possible remedies:
- create duplicate .rb files per package: e.g. firefox-nl.rb that points to https://ftp.mozilla.org/pub/firefox/releases/#{version}/mac/nl/Firefox%20#{version}.dmg 
  ++ provides clean separation between languages (perhaps the possibility to create repositories per language)
  -- adds extra version-management demands
- add localisation support to homebrew-cask to allow users to add localization tokens: e.g. brew cask firefox --lang nl
- add automatic localisation support, by having homebrew-cask detect the users' locale and pull the appropiate package.
There are probably other approaches to solve this problem, but I'm not a developer. I'm very interested to hear if others are experiencing the same problems and have any suggestions how to deal with this.

**Comment by winkelsdorf** [comment]
Localizations and/or specific Version (e.g. MyApp version 9.0) should be placed in
https://github.com/caskroom/homebrew-versions

There is for example a Cask for a german Firefox:
https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefox-de.rb

Sadly nothing in Dutch, yet :( But see below..

Regarding your mentioned possibilities:
1) That's the way it's done
2) see 1)
3) Please not! Let me explain why: I am not a native english speaker but prefer my OS and software to run in English. If somebody had implemented this approach I wouldn't be using Cask: Despite my OS is set to English, locale is set to something else for Date/Time, Currency and so on. Checking for locale would be installing non-english casks, which is not what I want.

For more information how to use versions read:
https://github.com/caskroom/homebrew-versions

You need to tap to versions:
```code
brew tap caskroom/versions
brew cask install my-localized-or-specific-version
```

I created a Pull Request for you which adds Firefox NL to versions:
https://github.com/caskroom/homebrew-versions/pull/1015

As soon as it is accepted you can install by using
```code
brew tap caskroom/versions
brew cask install firefox-nl
```

For other apps to be localized feel free to create your own Casks. It's a descriptive language with a clear syntax, not that hard to take an existing cask as a template (e.g. Thunderbird in English) which helps creating a localized version.

Cheers

**Comment by vitorgalvao** [comment]
Thank you for the detailed explanation, @winkelsdorf. Closing.

**Comment by winkelsdorf** [comment]
You're welcome!

**Comment by gmkey** [comment]
Many thanks for this! I've just added my thunderbird-nl package to the appropriate repository.

**Comment by winkelsdorf** [comment]
@gmkey You'r welcome, too :)

**Comment by designorant** [comment]
@winkelsdorf Are you sure about the third point? Checking the default `locale` would not do any harm, quite the contrary in fact.

Consider the following use case:
On OS X set to en_GB (see `locale` output below),  `brew cask install firefox` installs the en_US flavour of Firefox. Surely it should be the en_GB version in this case.

````bash
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
````

**Comment by winkelsdorf** [comment]
@designorant Thanks for your feedback. 

Yes, I still think it's better to leave the decision up to the User, instead of applying any automated language switches.

Have in mind that only a few additional language Casks are available in Versions. Applying automatics for just Firefox, Thunderbird and others would mix up with Casks which are only en_US. So some would be localized, some not. What would be a little messy, wouldn't it?

And each and every language must be added and checked manually.. Thus Casks are 98% only en_US currently.

As an example against your's, here is my current config and locale output:
<img width="780" alt="screenshot 2015-07-25 18 11 30" src="https://cloud.githubusercontent.com/assets/1413291/8890247/30399264-32f9-11e5-9dd4-99cf62b087a4.png">
<img width="1082" alt="screenshot 2015-07-25 18 11 35" src="https://cloud.githubusercontent.com/assets/1413291/8890249/3213ef80-32f9-11e5-940f-d6d213db515d.png">

You see my system is using English as primary language whilst the locale only outputs de_DE. So I would get German Casks. No, please don't. German is only selected for getting correct locale metrics when doing Text/Spreadsheet Edits for the location I currently live.

Cheers,
Frederik
