### ISSUE TITLE
FontForge cask should not conflict with FontForge brew

### ISSUE THREAD

**Issue by davelab6** [caskroom/homebrew-cask#11860]
@DomT4 https://github.com/caskroom/homebrew-cask/blob/master/Casks/fontforge.rb#L14 has:

```
  conflicts_with :formula => 'fontforge'
```

I don't think this is wise, because the fontforge homebrew formula provides a system python fontforge module, but the cask does not. Therefore both are needed.

**Comment by DomT4** [comment]
I was literally about to tee up a PR to remove it :wink:. I'm probably also going to remove the binary symlinking from `FontForge.app/Contents/MacOS/Fontforge` into `/usr/local/bin` for now because it suffers the same symlinking problem of the Application we discovered in Homebrew/homebrew (Namely, FontForge doesn't like being "called" from outside its app bundle).
