### ISSUE TITLE
App suites are not showing in Launchpad

### ISSUE THREAD

**Issue by aalireza** [caskroom/homebrew-cask#12369]
I've installed racket on OSX 10.10.4 which in its formula, there's a "suite" symlinking the directory containing bunch of apps to ~/Applications. However the applications don't appear in Launchpad. I've tried to install sketchup which was mentioned [here] (https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#suite-stanza-details) which also has the same problem. I've reseted the launchpad database following [here] (https://apple.stackexchange.com/questions/150965/how-to-reset-launchpad-ordering-in-os-x-yosemite) which doesn't solve the problem.
Is this an expected behavior of 'suite' or is this a bug?

P.S. 'app' works well and applications will show in launchpad.

**Comment by vitorgalvao** [comment]
`suite` just links a directory, so yes, it should be expected.

**Comment by leafac** [comment]
I ran into this issue as well. (Coincidentally with exactly with Racket and SketchUp as well.) I expected those applications to show up on launchpad, as any other do. So have the following questions:

1. Why is `suite` a special case?

2. Is [moving instead of linking](https://github.com/caskroom/homebrew-cask/issues/13201) going to change this behavior?

3. Is there a workaround?

**Comment by vitorgalvao** [comment]
@leafac No idea. Put simply, this a Launchpad issue/expected behaviour. We know we need `suite`, and that’s it. We never touch Launchpad, nor do we intend to.

**Comment by leafac** [comment]
@vitorgalvao Thanks for the answer.
