### ISSUE TITLE
Recurring tunnelblick version errors

### ISSUE THREAD

**Issue by amarendra** [caskroom/homebrew-cask#12738]
When I try to start tunnelblick I get an pop-up asking me to

> tunnelblick must be installed in Applications.

> Do you wish to replace ..... <V1 with V2>

And when I approve that it starts but the next time I try to start it I get the same pop-up, sometimes V1 and V2 being the same versions sometimes V1 < V2 and vice versa.

I also notice there are two versions in `/opt/homebrew-cask/Caskroom/tunnelblick`.

**PS**. Now I am not sure and I might have done it - i.e. opted for "check updates automatically" when prompted and this might have caused this conflict.

1. How to fix this?
2. Can I at least remove the older version manually? Shall cask detect this? There will be any issues as a result?
3. So if I upgrade casks, all the versions (after the first install) are installed and kept on my disk? If so, how to make sure only one version (latest) is installed?

**Comment by scribblemaniac** [comment]
This is probably somewhat related to #10519

Unfortunately, I can only help you out a little bit here:

1. I can't help you with this because I do not know enough about the app.
2. Yes you can delete the the older version manually, there shouldn't be any issues with cask. However, the cask for tunnelblick specifies a slightly custom uninstallation. It will remove the launchctl entry `net.tunnelblick.tunnelblick.LaunchAtLogin` and will quit any apps with the id `net.tunnelblick.tunnelblick`. Considering you still want to use another version of the app, I doubt these are necessary for you to do.
3. I think that all the versions you install will be kept on your disk unless you uninstall them. I don't think there are any cask commands or options to keep only the latest version, but you could probably write a script to clean up old versions.

You'll have to wait for someone else with a bit more experience to give you some assistance with your other issues.

**Comment by amarendra** [comment]
Hey thanks for the response.

> but you could probably write a script to clean up old versions.

Automation was the reason I was moving apps to cask installations. Guess I will wait till cask matures and slowly move all cask installed apps back to individual installs because auto-update is supported in almost every app and I don't think cask offers anything extra (other than installing with a command) for my usage scenario at least. Also such issues are kind of an overhead.

**Comment by scribblemaniac** [comment]
Yeah give it time, we're still working on the upgrading functionality.

**Comment by amarendra** [comment]
Yeah, maybe I should try making a pull request or two when I find time and see whether there's something I can help with :-) (Closing it)
