### ISSUE TITLE
Should audacity be removed?

### ISSUE THREAD

**Issue by scribblemaniac** [caskroom/homebrew-cask#12972]
Audacity abandoned SourceForge a while back. Their new homepage can be found at [audacityteam.org](http://audacityteam.org/). The issue that arises is briefly touched upon #10344 but no long term solution was proposed. Now they have released a new version (2.1.1) which is only hosted on FossHub. Since we cannot download things from FossHub, I propose that we remove the cask altogether. Any thoughts?

**Comment by vitorgalvao** [comment]
If we cannot download it, then we cannot. We should remove it, yes.

**Comment by realistschuckle** [comment]
Sorry for the n00b question: now that you've removed the cask, how can I use `brew cask` to uninstall audacity? If I cannot, how do I figure out the manual steps to take?

**Comment by scribblemaniac** [comment]
In this particular case, deleting the Audacity.app link in your Applications folder would be equivalent to `brew cask uninstall audacity`. I don't know about a more general case solution however.

**Comment by vitorgalvao** [comment]
@realistschuckle Neat trick. You can use the location (including URL) of a cask instead of its name; you can also access older versions of a file with github. Joining the two, you can `brew cask uninstall https://raw.githubusercontent.com/caskroom/homebrew-cask/9f75961d44cedb6b0d7ea0afab4965b33ce402de/Casks/audacity.rb`.

**Comment by alswl** [comment]
It's back.

[Mac | Audacity®](http://www.audacityteam.org/download/mac/)

download link: https://www.fosshub.com/Audacity.html/audacity-macos-2.1.3.dmg

**Comment by miccal** [comment]
@alswl it never left - it was removed because fosshub.com does not allow CLI downloads.

**Comment by alswl** [comment]
Thanks, so sad.


--
alswl

On 3 May 2017 at 16:15:47, Matthews Miccal (notifications@github.com) wrote:

@alswl <https://github.com/alswl> it never left - it was removed because
fosshub.com does not allow CLI downloads.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/caskroom/homebrew-cask/issues/12972#issuecomment-298848651>,
or mute the thread

**Comment by Crocmagnon** [comment]
The new official download page for Audacity for Mac is https://sourceforge.net/projects/audacity/
Should we add it back ?

**Comment by commitay** [comment]
> The new official download page for Audacity for Mac is https://sourceforge.net/projects/audacity/

It isn't. http://www.audacityteam.org/download/mac/

> Here is the direct link for the current version : https://downloads.sourceforge.net/project/audacity/audacity/2.1.0/audacity-macosx-ub-2.1.0.dmg

This version is two years old.

**Comment by Crocmagnon** [comment]
Oh indeed, you're right ! I've been misled by my search engine...
Sorry for disturbing you !

**Comment by D7blacksushi** [comment]
Audacity is back alive with the new version 2.2.0 ! Released 2 November only! 
Check out: https://wiki.audacityteam.org/wiki/Release_Notes_2.2.0

But yeah only available through fosshub for download...
Maybe ask for an update on sourceforge for get the direct download?
