### ISSUE TITLE
Uninstall of Java failing

### ISSUE THREAD

**Issue by MrTact** [caskroom/homebrew-cask#13019]
I installed the most current version of java using caskroom today, and seconds later realized our office standard is to use an older version to match what is currently in production. When I ran brew cask uninstall java, it failed with the following error:

```
==> rmdir: /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj: Not a dir
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/bin/rmdir", "--", "#<Pathname:/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj>"]
```

In this case, the file in question is a symlink to another directory. Looks like maybe the install should be capturing that info and using rm instead. Alternately, maybe the uninstall code could just use rm -d?

**Comment by vitorgalvao** [comment]
Something weird happened there. `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj` is too specific, it should be trying to [remove `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin` directly](https://github.com/caskroom/homebrew-cask/blob/4800afc1dc4a0a2143047e60d934b1c05fcc23fe/Casks/java.rb#L49).

I can’t reproduce the error on a clean VM. @radeksimko @alebcay @fanquake can you?

**Comment by vitorgalvao** [comment]
Something weird happened there. `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Frameworks/Sparkle.framework/Versions/A/Resources/pt.lproj` is too specific, it should be trying to [remove `/Library/Internet Plug-Ins/JavaAppletPlugin.plugin` directly](https://github.com/caskroom/homebrew-cask/blob/4800afc1dc4a0a2143047e60d934b1c05fcc23fe/Casks/java.rb#L49).

What does `brew cask cat java` show?

**Comment by vitorgalvao** [comment]
Closing on account of no reply. If it is still an issue, please report back.

**Comment by dpo** [comment]
I'm having the same issue on 10.9. `brew cask cat java` says: https://gist.github.com/703936665a9b55f49db0

**Comment by adityadalal924** [comment]
@dpo Please open up a new issue so we can get all the necessary information to help you, see https://github.com/caskroom/homebrew-cask#reporting-bugs

**Comment by dpo** [comment]
It seems the problem comes from having a previous install of Java (not using `homebrew cask`). I followed the instructions https://www.java.com/en/download/help/mac_uninstall_java.xml and http://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jdk.html to uninstall everything. Installing/uninstalling the cask happens cleanly after that.

**Comment by adityadalal924** [comment]
Good to hear the issue was resolved. If anyone else stumbles upon this issue, to clean up java, do:

```
sudo rm -fr /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin 
sudo rm -fr /Library/PreferencePanes/JavaControlPanel.prefpane
```
and delete old versions from `/Library/Java/JavaVirtualMachines`

(running `/usr/libexec/java_home -verbose` should show nothing at this point)

and you can finish with `brew uninstall java && brew install java` if so desired
