### ISSUE TITLE
A command to upgrade all casks ?

### ISSUE THREAD

**Issue by matthewharwood** [caskroom/homebrew-cask#13256]
What is the best method on updating and upgrading a cast?  Say I have webstorm and I want to update to a new version?  Is there a method to upgrade all casks at once?

**Comment by matthewharwood** [comment]
http://stackoverflow.com/questions/31968664/upgrade-all-the-casks-installed-through-homebrew-cask

**Comment by scribblemaniac** [comment]
There is no official method for upgrading homebrew casks. This is currently being worked on, but it is still very far from completion. See #4678 for more details. That issue also has some examples of scripts that users use to upgrade all of their casks. The simplest way to upgrade a single cask would be to run `brew cask install --force <cask_name>`, but just know that there is a chance this may cause issues with your app since it won't be properly uninstalled first.

If anyone has anything to add to this discussion, I can add their input to my answer on SO to help other people who may find that question.

**Comment by vitorgalvao** [comment]
After https://github.com/caskroom/homebrew-cask/issues/13201 is done, we’ll be able to start working on an upgrade solution. Until then, @scribblemaniac’s answer is correct.

**Comment by szhu** [comment]
```bash
#!/bin/bash
# /usr/local/bin/brew-cask-reinstall
# Usage: brew cask-reinstall token1 token2 ...
for token in "$@"; do
    echo "==> Re-installing $token"
    brew cask uninstall --force "$token" && brew cask install "$token"
done
```

Sidenote: Will Homebrew Cask support external commands like brew does in the future? `brew cask reinstall` would look better than `brew cask-reinstall`.

**Comment by vitorgalvao** [comment]
Actually, I recommend:

```bash
caskup() {
  rm -rf "$(brew --cache)"
  brew update
  brew cask uninstall --force "$@"
  brew cask install "$@"
}
```

If you don’t get rid of the cache and try to reinstall a cask with `:latest`, you risk getting an old version ([known issue](https://github.com/caskroom/homebrew-cask/issues/13206).

There are no plans for a `reinstall` command, no. Don’t really see a strong case for it, but could be convinced otherwise. Currently, though, it’d have a really low priority.

**Comment by szhu** [comment]
Ah I see. The thing is, flushing the cache and re-downloading are sometimes long operations so I save those for other invocations. Even from a less pragmatic standpoint, I don't think reinstall should do anything in addition to what install does – "reinstall" basically should be "remove and install".

Also my question about the external commands was, will Homebrew Cask support the invoking external commands that begin with `brew-cask-`? For example, if I have an executable in my `PATH` called `git-testcommand`, I can invoke it with `git testcommand`. Likewise, the `brew-cask` executable can be invoked with `brew cask`.

**Comment by scribblemaniac** [comment]
If you don't like the look of the command, you can always just use alias to format it more to your liking.

**Comment by szhu** [comment]
No I can't. I want it to look like `brew cask reinstall`, with spaces in between. That necessarily requires the `brew` command to recognize it. Both `git` and `brew` have code specifically to allow these kind of external commands to be invoked in this way.

**Comment by scribblemaniac** [comment]
Oh, I didn't realize alias names couldn't have spaces (I don't use them very often). Anyway, this should indeed be a separate issue.

**Comment by vitorgalvao** [comment]
> @vitorgalvao this discussion should be in a separate issue, huh

Yes, it should. But there aren’t any plans in this direction now, and even though we can start discussing this now, finishing https://github.com/caskroom/homebrew-cask/issues/13201 is the priority.

**Comment by deinspanjer** [comment]
I posted an answer to the stackoverflow, but figured it wouldn't hurt to put it here as well.  I wanted a function that let me interactively choose which casks to re-install or not.  I also put the --quick argument in to not have to blow away the cache and update if I had just done so but exited out.

    brew-cask-upgrade() {
      if [ "$1" != '--quick' ]; then
        echo "Removing brew cache"
        rm -rf "$(brew --cache)"
        echo "Running brew update"
        brew update
      fi
      for c in $(brew cask list); do
        echo -e "\n\nInstalled versions of $c: "
        ls /opt/homebrew-cask/Caskroom/$c
        echo "Cask info for $c"
        brew cask info $c
        select ynx in "Yes" "No" "Exit"; do
          case $ynx in
            "Yes") echo "Uninstalling $c"; brew cask uninstall --force "$c"; echo "Re-installing $c"; brew cask install "$c"; break;;
            "No") echo "Skipping $c"; break;;
            "Exit") echo "Exiting brew-cask-upgrade"; return;;
          esac
        done
      done
    }

**Comment by Yann-R** [comment]
> Is there a method to upgrade all casks at once?

Personally, I use
```
brew cask install `brew cask list`
```
It's not totally perfect (otherwise why would we wait for a built-in upgrade command ;-))
because I have to clean "obsolete" old versions from the Caskroom folder after upgrading... But in a sense it's OK and safe for my use since this way I'm sure the previous version is still there in case the new version would be disappointing...

**Comment by n0ts** [comment]
Hi, I created brew-cask-upgrade.sh
https://gist.github.com/n0ts/94693a99756c1f47c94f5b2c005530e8

**Comment by vitorgalvao** [comment]
There are tons of those scripts. Please stop posting them. There are more than enough, and they all suffer from the same issues.
