### ISSUE TITLE
Add homebrew-cask support to _brew zsh-completions file

### ISSUE THREAD

**Issue by mbgearhead** [caskroom/homebrew-cask#1328]
Like many others, I heavily rely on the feature of zsh and its myriad add-ons to enhance my productivity. I'm very new to writing completions files, but I think I have successfully added tab-completion to the homebrew zsh-completion file in /usr/local/share/zsh-completions/_brew (requires installation of z-shell and zsh completions by "brew install zsh zsh-completions"). For anyone that is interested, please check out: https://gist.github.com/mbgearhead/7187772 and let me know if you have any suggestions. Cheers!
 - Miles

**Comment by vitorgalvao** [comment]
Completions for zsh are [available in oh-my-zsh](https://github.com/robbyrussell/oh-my-zsh/blob/a8ef111a796acbd7d235b52e5864c6af4b911aa5/plugins/brew-cask/brew-cask.plugin.zsh).

**Comment by ngocphamm** [comment]
And very unfortunately I don't use oh-my-zsh :(

**Comment by vitorgalvao** [comment]
@ngocphamm Either way, this issue is about tips for @mbgearhead’s work for `zsh-completions`, which does not directly concern us, in the sense that we can’t add the completions ourselves, since its a different project. It’s now up to whoever wants to submit them to the other project to do so, and for them to accept it. Leaving this open is just cluttering the huge amount of issues we have.

**Comment by ngocphamm** [comment]
I agree. I use [Prezto](https://github.com/sorin-ionescu/prezto) and happen to be able to convert that oh-my-zsh plugin to Prezto module.
