### ISSUE TITLE
Homebrew-Cask Truck Factor

### ISSUE THREAD

**Issue by gavelino** [caskroom/homebrew-cask#13308]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Homebrew-Cask** and obtained a value of **1**. For this value we did not consider the files in **Casks** folder.

The developer responsible for this TF is:

Roland Walker - author of 88% of the files 

To validate our results, we would like to ask **Homebrew-Cask** developers the following three brief questions:

(a) Do you agree that the listed developer is the main developer of **Homebrew-Cask**?

(b) Do you agree that **Homebrew-Cask** will be in trouble if the listed developer leave the project (e.g., if he wins in the lottery, to be less morbid)?

(c) Does **Homebrew-Cask** have some characteristics that would attenuate the loss of the listed developer (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br

**Comment by vitorgalvao** [comment]
Hello @gavelino,

Your questions are timely, since Roland has already left the project. I can answer them all.

Your metrics are somewhat shortsighted, though, since they assume core development to be the most important task for homebrew-cask. It is not (though it is crucial to a point), deciding how to deal with individual cask oddities is just as important.

No, we are not in trouble. We had other main core developers before.

Yea, we have plenty of ways to make these transitions work. Not only is our documetation compreensive, we have multiple maintainers that know the rules and requirements well, and make them clear to newcomers.

Thank you for your interest, and good luck in your study.
