### ISSUE TITLE
release 0.57

### ISSUE THREAD

**Issue by nexus-uw** [caskroom/homebrew-cask#13343]
<img width="546" alt="screen shot 2015-08-19 at 10 13 54 am" src="https://cloud.githubusercontent.com/assets/3188890/9358631/0ca47ee8-465b-11e5-9bde-df21a5efd852.png">
 

It would be nice to release all of these updates.

**Comment by Ngrd** [comment]
Actually, the number since the release doesn't tell much in this project. The new release is usually made when there are some new features were added on any breaking changes were made. All those 471 commits in most cases only affect casks. You can always run:
```bash
brew cask update
```
and you will get the most recent version with all those commits included. So there is no reason to spawn new releases every week.

**Comment by nexus-uw** [comment]
well I feel rather silly but thank you for prompt reply.
