### ISSUE TITLE
please update graphviz GUI to 2.39

### ISSUE THREAD

**Issue by n0mer** [caskroom/homebrew-cask#13413]
Currently https://github.com/caskroom/homebrew-cask/blob/master/Casks/graphviz.rb refers to 2.36.0

Latest version from http://graphviz.org/News.php is 2.38.0

But, there is a note here: http://graphviz.org/Download_macos.php , which says GUI is no longer available for Mountain Lion, Maverick and i suppose Yosemite as well.

https://github.com/Homebrew/homebrew/blob/master/Library/Formula/graphviz.rb - this script for `brew` refers to 2.38.0

**Comment by Ngrd** [comment]
There is nothing much can be done with this cask update. The current latest stable release is 2.38.0 which works only on Mac OS X Snow Leopard and Lion. Officially Graphviz 2.38.0 isn't supported by Mac OS X Mavericks and later.

Partially this cask is fixed in https://github.com/caskroom/homebrew-cask/pull/13417. The users of Mac OS X Snow Leopard and Lion will get the latest stable version (2.38.0) from now on. Others, however, will have to use an old 2.36.0 version.
