### ISSUE TITLE
All application has only lowercase name?

### ISSUE THREAD

**Issue by say8425** [caskroom/homebrew-cask#13623]
After buying new macbook pro, I want to install `qlimageSize ` with brew cask.
So I command `brew cask install qlimageSize`, but it did not work. The problem is lowercase. The correct command is `brew cask install qlimagesize` not `qlimageSize`. 

Of course, it's very simple problem and you can think it's not problem. But I found many applications have lowercase name in brew cask. So I suggest the name in brew command always make lowercase. If you command `brew cask install qlimageSize` then it convert with `brew cask install qlimagesize`

But before committing or developing, I want to know one thing. Is all of application have lowercase name in brew cask? And have to do that?

**Comment by vitorgalvao** [comment]
Yes, all of them are lowercase. They need to be for technical reasons, since it needs to match the header line, but theoratically you might be able to make them with different cases, so it might be desirable for personal taps. It is also way better for usability (who’d want to try all variations before arriving at the correct name?). This is also not an issue at all, so it does not need a fix. In all the time since the inception of homebrew-cask, you’re the first person I remember having such an issue.

Please do not submit a fix for this, as it is not broken.
