### ISSUE TITLE
Force Install a Cask - Override Warnings

### ISSUE THREAD

**Issue by sbdchd** [caskroom/homebrew-cask#13729]
I am currently trying to install [remote desktop connection](https://github.com/caskroom/homebrew-cask/blob/9b2b7b7d7e929b461ebeb9fcf52250774d48e004/Casks/remote-desktop-connection.rb) but my os version is allegedly not compatible. 

I have installed this program through the dmg directly and it worked fine, so I am wondering if there is a way to force install the cask, overriding the compatibility error.

Thanks.

**Comment by vitorgalvao** [comment]
There is not, nor do we plan on adding one. When we add such an OS requirement, it is because the vendor says that is the case (and I’ve confirmed this one personally more than once), so we won’t change it (it works for you, but might break for someone else).

Your best best is to create a personal tap with this.
