### ISSUE TITLE
Installation of utorrent  with brew cask

### ISSUE THREAD

**Issue by kfollesdal** [caskroom/homebrew-cask#14368]
I have install utorrent by homebrew cask by run the following  command ```brew cask install utorrent```  I then get the following message:
```
To complete the installation of Cask utorrent, you must also
run the installer at

  '/opt/homebrew-cask/Caskroom/utorrent/latest/uTorrent.app'
```
Then I run the installer and uTorrent is installed in the ```~/Application``` (not symlinked). 

Question: Is not one of the main ideas to brew cask that the applications are installed in ```/opt``` and then symlinked to ```~/Applications```?

**Comment by vitorgalvao** [comment]
> Is not one of the main ideas to brew cask that the applications are installed in `/opt` and then symlinked to `~/Applications`?

No, [not anymore](https://github.com/caskroom/homebrew-cask/issues/13201).

This case touches in part of the “why”, even. What you did was *manually* run uTorrent’s installer. homebrew-cask didn’t run it, you did, so it installed as if homebrew-cask had never been involved at all (all we did was download it) which is why it installed wherever it wanted/you chose.

**Comment by jawshooah** [comment]
@kfollesdal Also note that for the vast majority of casks, you don't have to run a manual installer. Some apps don't provide a direct download, though, so this is the best we can do.
