### ISSUE TITLE
Subdirectories in Casks directory?

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#14479]
I already asked this question for Formulas (https://github.com/Homebrew/homebrew/issues/45046)
but I just wanted to be sure it's the same for Casks.
So is it possible to put casks into subdirectories in the Casks directory of a tappable repository?

**Comment by vitorgalvao** [comment]
Nope. Same as them.

**Comment by adius** [comment]
…and let me guess: You wouldn't accept a pull request? ^^

**Comment by vitorgalvao** [comment]
Our conversation from the other issue has nothing to do with this. Like I said there, the work you put into it is still appreciated, and we’re not in the habit of declining stuff based on who they came from.

I never even considered the feature previously, so I don’t even have an opinion yet. In addition, other maintainers should also vouce their opinion.

That said, I don’t think you should spend the time on implementing it here, no, because we’re in talks of merging with homebrew (there’s a recent open issue, I’d link you, but am currently on a phone), so that work would likely end up being thrown out if/when that happens. If you submit it there and they accept it, though, perhaps both projects can benefit.
