### ISSUE TITLE
mactex repeatedly re-downloading

### ISSUE THREAD

**Issue by FranklinChen** [caskroom/homebrew-cask#15301]
The mactex formula was recently changed to not track its version and as a result a script I have that does updates by running `brew cask install mactex` repeatedly reinstalls mactex even though it is already up to date.

**Comment by vitorgalvao** [comment]
The title of this issue is misleading. It’s not `mactext` that is misbehaving.

`brew cask install` shouldn’t be installing something that is already installed, though (unless you give it the `--force` flag). `brew cask list`, however, [is broken](https://github.com/caskroom/homebrew-cask/issues/14058) so the way of checking for the installation of `mactex` may be screwing up as well.

For now, you can try to `brew cask uninstall --force mactex && brew cask install mactex` and see if it fixes it, but more likely you’ll have to fix your script. `mactex` doesn’t provide a versioned download (if you don’t like that, you need to complain to the developers, not us) so there’s no way to know if your installed version is up to date or not, anyway.

**Comment by vitorgalvao** [comment]
[Here’s the reason we switched it](https://github.com/caskroom/homebrew-cask/pull/15196#issuecomment-158113476).

**Comment by adidalal** [comment]
https://github.com/caskroom/homebrew-cask/pull/18908
