### ISSUE TITLE
No such file or directory - /usr/bin/type -aP ruby

### ISSUE THREAD

**Issue by maxweb4u** [caskroom/homebrew-cask#15422]

**Comment by vitorgalvao** [comment]
There is not even near enough information to understand your problem.

Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
