### ISSUE TITLE
Request: MacTeX without Ghostscript

### ISSUE THREAD

**Issue by lifepillar** [caskroom/homebrew-cask#15431]
Homebrew already provides a `ghostscript` formula. Currently, MacTeX installs its own (outdated) version, which overrides Homebrew's `ghostscript`, with obvious consequences (e.g., errors upon updating the formula). Would it be possible to install MacTeX without Ghostscript, possibly adding a caveat suggesting to use Homebrew's formula?

**Comment by vitorgalvao** [comment]
We simply install [their `pkg`](https://github.com/caskroom/homebrew-cask/blob/f07ed4bddc5c48242c2ff185f4bdc4976a93657d/Casks/mactex.rb#L10) downloaded from the website, so we have no say in it.

You need to complain upstream, to the mactex developers, and ask for a version without ghostscript (or find it, if it already exists).

**Comment by adityadalal924** [comment]
@lifepillar It sounds like you're looking for BasicTeX, which can be found at https://tug.org/mactex/morepackages.html

**Comment by lifepillar** [comment]
Thanks for the quick feedback. Packages like MacTeX provide a choice of programs to be installed when launched via the GUI. Isn't there an equivalent function from the command-line, which Homebrew Cask might exploit?

@adityadalal924 BasicTeX is ~1/20th of the whole Tex Live, so it is not exactly the same as MacTeX minus Ghostscript. I will try it anyway, thanks for the hint.

**Comment by vitorgalvao** [comment]
> Packages like MacTeX provide a choice of programs to be installed when launched via the GUI. Isn't there an equivalent function from the command-line, which Homebrew Cask might exploit?

No. We purposefully do not call GUIs.

**Comment by ELLIOTTCABLE** [comment]
I have the same issue/question/concern: I don't want BasicTeX (as it's missing a lot of things); but I also definitely don't want the terrible un-OS-X-friend GUI crap installed *either*.

It *is* possible; the `installer(8)` tool allows for it: you have to:

1. Dump the installer options provided,

        installer -showChoiceChangesXML -pkg "~/Desktop/mactex-20150613.pkg" -target "/"  \
           > ~/Desktop/showChoiceChangesXML.xml

2. Then change the choices as desired. Here's an example for *this specific package* that disables the GUI and Ghostscript options:

   ```plist
   <?xml version="1.0" encoding="UTF-8"?>
   <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
   <plist version="1.0">
   <array>
      <dict>
         <key>attributeSetting</key>
         <false/>
         <key>choiceAttribute</key>
         <string>enabled</string>
         <key>choiceIdentifier</key>
         <string>choice2</string>
      </dict>
      <dict>
         <key>attributeSetting</key>
         <false/>
         <key>choiceAttribute</key>
         <string>enabled</string>
         <key>choiceIdentifier</key>
         <string>choice3</string>
      </dict>
   </array>
   </plist>
   ```

3. Presumably, if added to Cask, this wouldn't be necessary; but if you're doing this by hand, you can verify that your changes to the options apply cleanly:

        installer -pkg "~/Desktop/mactex-20150613.pkg" -target "/"  \
           -showChoicesAfterApplyingChangesXML "~/Desktop/showChoiceChangesXML.xml"

4. Finally, install the package with those options:

        sudo installer -pkg "~/Desktop/mactex-20150613.pkg" -target "/"  \
           -applyChoiceChangesXML "~/Desktop/showChoiceChangesXML.xml"

----

Postscript (pun intended): If you want to *remove* the damage already done, you can probably construct something from the receipt; be careful though, because it lists *shared directories* like `/usr/local/man`, so it's not a simple `xargs rm`:

    pkgutil --pkg-info org.tug.mactex.ghostscript9.16
    pkgutil --files org.tug.mactex.ghostscript9.16

**Comment by vitorgalvao** [comment]
@elliottcable we’re not equipped for such changes based on options. It was discussed in the past, but abandoned due to lack of interest in implementing it.

You can give it a stab at adding it to the core, if you’d like, but we’re not going to edit the current cask to do that change.

**Comment by commitay** [comment]
`mactex` with a `depends on formula: ghostscript` https://github.com/caskroom/homebrew-cask/pull/38190
