### ISSUE TITLE
Cask request: gptfdisk

### ISSUE THREAD

**Issue by ilovezfs** [caskroom/homebrew-cask#15476]
At least at the moment, homebrew has decided to relegate gptfdisk to the boneyard tap, which means it will not be found by brew search (unlike other taps) and which means there are no longer binary bottles available.

https://github.com/Homebrew/homebrew/commit/725a7ec805a669c868652a5859f3c7840da3390e
https://github.com/Homebrew/homebrew-boneyard/commit/6d38b101e2feab16e6baa8248c11de3cb275058d

(I have noted my objection here: https://github.com/Homebrew/homebrew/pull/46398#issuecomment-160431744)

gptfdisk is also distributed on http://sourceforge.net/projects/gptfdisk/ as a pkg so it's looking like a prime candidate for homebrew cask unless homebrew changes its mind.

**Comment by vitorgalvao** [comment]
Always keep in mind making your own tap is extremely easy, so you can do so even for homebrew’s formula, since it works for you.

Too be honest, I’m not too inclined to add it either. It’s not like there’s a demand for it, and the wording on the homepage makes it sound like it doesn’t work *and cannot* work in El Capitan (and presumably later OS X versions), which means this will only become less useful over time, even if it currently works for you in particular.

I don’t feel that strongly about it that I couldn’t be persuaded otherwise, though. If any other homebrew-cask maintainer feels like this should be added (not indifference, but actually thinks it should be added) then sure, but otherwise we should just close this issue.

**Comment by ilovezfs** [comment]
The homepage is simply incorrect. Did you read my example?

**Comment by ilovezfs** [comment]
https://github.com/Homebrew/homebrew/pull/46398#issuecomment-160433176

**Comment by vitorgalvao** [comment]
Please do not post in a row. If you forgot to add something, edit the comment (I’ve done it for you now).

> Did you read my example?

Yes, I did (I skimmed it, more accurately).

> The homepage is simply incorrect.

But why should we take your word instead of what’s said on the homepage? How do we know it doesn’t simply work for *you* due to an annomaly in *your* setup (say, you having installed it before upgrading, or something). Neither team (homebrew and homebrew-cask) will (or should) simply take the word of a random person over the word of the developer, without further investigation. Should we blindly add something the developer says doesn’t work just because you say it works for you, and then potentially have other users reporting that it’s broken? Not exactly a smart move.

You are absolutely arguing in the wrong places. Both my reservation and the reservation of homebrew’s team would be solved simply by having the developers say it does indeed work (or not claiming it doesn’t), **so ask them**. Contact the developer, prove to them that it does indeed work in El Capitan, and they’ll have no reason to have the message there, which in turn will make so there’s no reason either homebrew or homebrew-cask can’t have this.

**Comment by ilovezfs** [comment]
It is not an anomaly in my setup. This is a clean install virtual machine with gptfdisk never installed until just now built from the homebrew boneyard tap. SIP is clearly enabled without any tweaks to csr-active-config or csr-data
```
ilovezfss-Mac:~ ilovezfs$ csrutil status
System Integrity Protection status: enabled.
ilovezfss-Mac:~ ilovezfs$ sudo nvram csr-active-config
Password:
nvram: Error getting variable - 'csr-active-config': (iokit/common) data was not found
ilovezfss-Mac:~ ilovezfs$ sudo nvram csr-data
nvram: Error getting variable - 'csr-data': (iokit/common) data was not found
ilovezfss-Mac:~ ilovezfs$ `
```
As for whether you trust me, that's up to you. The demonstration that it works without issue when used on any disk besides the system disk is very clear. As expected with SIP enabled, it should not be able to operate on the system disk and the errno 1 EPERM is exactly what you should and do get. If I had SIP disabled, then you would see it succeed in the case of the system disk as well.

Yes, I could try to reach out to Rod Smith to see exactly what was on his mind when he wrote that comment on the homepage, but until then, the current situation of boneyard or SourceForge is unfortunate to say the least.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/Homebrew/homebrew/pull/46398#issuecomment-160473325.
