### ISSUE TITLE
Symlinking doesn't work

### ISSUE THREAD

**Issue by lexfrei** [caskroom/homebrew-cask#15626]
I got a clean install of OS X 10.11 and `brew cask install google-chrome` doesn't  links installed apps to Applications (can's see this apps in Finder in Applications folder) and `brew linkapps` doesn't fix it.
I'm new to cask, but I fink it isn't normal. Is there any way how I can forced link it or it is a bug in cask?

**Comment by vitorgalvao** [comment]
By default we install to `~/Applications`, not `/Applications`. Are you looking in the right place?

**Comment by adityadalal924** [comment]
Also, if you want apps to show up in Applicattions, under Finder (That's /Applications), you could add something like `export HOMEBREW_CASK_OPTS="--appdir=/Applications"` to your .bash_profile

**Comment by lexfrei** [comment]
Probably, I doesn't understand what going on in OS X, i'm linux-user in main-theme.
When I'm opening my default Application dir and there is no installed apps it's strange.
So, if it is normal case, you `must` write about it with big rad letters or provide an option to change default before first install, IMHO. It's comfortable.
Thank you for assist.
On your choice: you can close this ticket or think about my opinion and "fix" it.

**Comment by adityadalal924** [comment]
We're moving away from symlinking soon(TM). That will remove this entire issue

Early on in the project, the maintainers made a decision to use ~/Applications and it's persisted since.

Add that line to your options if you want things to work "normally" for you (I also have the same behavior, as it feels "natural"), that's about the best we can do currently, unfortunately.

Closing this issue, but feel free to make a new one if anything else comes up!
