### ISSUE TITLE
Look up and replace applications with Caskroom

### ISSUE THREAD

**Issue by nuno-agostinho** [caskroom/homebrew-cask#15699]
The other day, I wanted to download my applications into a new computer. Since I have many apps, I needed to search manually in Caskroom for each. So why doesn't Caskroom provide a look up function to see if there are casks for the apps in a given folder?

Something as simple as `brew cask lookup` to search apps in the /Applications and ~/Applications folder (by default) and that would return a list of which apps are available in Caskroom (maybe if Caskroom finds casked apps, it would not warn about those?)

Also, something like `brew cask convert` or `brew cask replace` could be used to do the look up AND then to install the apps through Caskroom, replacing the current applications downloaded from other sources. Of course, this should only replace apps if Caskroom provides the same or a newer version of the installed app.

**Comment by vitorgalvao** [comment]
Because the point is to have all the apps we can and make sense. If there’s an app you have that isn’t yet in homebrew-cask, add it, or request it. The goal is not for you to use homebrew-cask and manual downloads interchangeably, but homebrew-cask exclusively.

Baking such a feature to the core would go against the goals and be a waste of resources.

That said, over two years ago @exherb made [a script for this](https://github.com/exherb/homebrew-cask-replace), so if you want it, use it. We won’t implement the feature.

**Comment by Amorymeltzer** [comment]
`ls /Applications/ | sed 's/\.app[/@\\]//g'| xargs -n1 brew-cask search` will get you halfway there

**Comment by nuno-agostinho** [comment]
@vitorgalvao Thanks for pointing me to that script!

I understand the goal but there's at least one limitation with using homebrew-cask: there are apps you can find only on the App Store. And unless I'm mistaken, you can't install them through cask. Anyway, thanks hearing me out! :)

@Amorymeltzer This is nice, thanks!

**Comment by vitorgalvao** [comment]
> I understand the goal but there's at least one limitation with using homebrew-cask: there are apps you can find only on the App Store. And unless I'm mistaken, you can't install them through cask.

Yes, but there’s nothing we can do about that, and a lookup function would be useless in that case anyway.
