### ISSUE TITLE
WebStorm linked binary isn't working

### ISSUE THREAD

**Issue by diimdeep** [caskroom/homebrew-cask#15719]
linked binary in cask: 
```
binary 'WebStorm.app/Contents/MacOS/webstorm
```
isn't working from cli

```
2015-12-09 22:03:55.940 webstorm[11483:304150] Value of (null): (null)
2015-12-09 22:03:55.945 webstorm[11483:304150] Info.plist is corrupted, Absent JVMOptions key.
```

On first startup webstorm ask to install python script in `/usr/local/bin/wstorm` it's with hardcoded paths.

**Comment by vitorgalvao** [comment]
If webstorm has its own way of doing this and will walk you through it, then we shouldn’t interfere, and remove that line.

Unfortunately, it seems they build that script at the time it’s needed, so no way we can link it ourselves, and since you can pick its install location, there’s also no way we can reliably remove it on uninstall.

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/pull/15750.
