### ISSUE TITLE
Install java fails with error

### ISSUE THREAD

**Issue by madamedefarge** [caskroom/homebrew-cask#15743]
brew cask install java fails with error;-

Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/java/1.8.0_66-b17/JDK 8 Update 66.pkg'

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

We’ve just undergone a major change, so please also `brew uninstall --force brew-cask && brew update`.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
