### ISSUE TITLE
Update broke brew-cask in the shell

### ISSUE THREAD

**Issue by thibmaek** [caskroom/homebrew-cask#15786]
Updating with `brew update && brew upgrade --all` broke my brew-cask command.
Running it outputs: `bash: brew-cask: command not found`

All my apps installed trough cask are still listed in /opt/homebrew-cask/
and all the other taps installed in brew itself are working.

Tried reinstalling with: `brew tap caskroom/cask` but that gave me `Warning: Tap caskroom/cask already tapped.`

Any solution on how to fix this? Tried updating brew and all the taps again but that didn't work as well.
If you guys need any additional info let me know. My shell is /usr/local/bin/bash@4.3.42 and I'm running this from 10.11.2

**Comment by vitorgalvao** [comment]
That’s due to a recent change. You got a message about it when upgrading homebrew-cask, so you might’ve missed it. Run `brew uninstall --force brew-cask; brew update`.

For more details [see the README](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

**Comment by thibmaek** [comment]
Oh so new cask is included in brew itself?
Good to know
