### ISSUE TITLE
How to detect move to new system?

### ISSUE THREAD

**Issue by manojlds** [caskroom/homebrew-cask#15962]
I was seeing that `brew cask install` started to fail, and saw the README here to understand that `brew uninstall --force brew-cask; brew update` needs to be run.

We have automated dev box setup in our company, and I would like to propagate this to other developers. Is there a way for me to detect if the switch to the new system has happened or not? Otherwise it would have to be a brute force remove and add all the time, or some other hacky approach to track if this was run.

Any pointers? Thanks

**Comment by vitorgalvao** [comment]
> Otherwise it would have to be a brute force remove and add all the time

Why “all the time”? You only need to do it once per setup. Also, there isn’t really a *better* way. Quickest is to run `brew uninstall brew-cask`. If it returns a non-`0` exit value (in this case, `1`), then it failed to uninstall, which means it likely already switched (alternatively, the user just uninstalled it and did nothing else).

So `brew uninstall brew-cask && brew update` will only run `brew update` if the uninstall fails. But you should run `brew update` regularly, so why not? But at that point, why not just run `brew uninstall --force brew-cask; brew update` anyway?

There’s no way you’ll be able to make a check that won’t require more code than this, and this is pretty fast, even. Also you’ll presumably need to remove that extra code for the check later anyway, so your best bet is to run one of those commands anyway (since they’re fast, work well, and are already there) and remove them when you would remove your custom check code anyway.

**Comment by manojlds** [comment]
Ok, makes sense, thanks!

**Comment by jawshooah** [comment]
Another method would be something like this:

```bash
if [[ -d $(brew --repository)/Cellar/brew-cask ]]; then
  brew uninstall --force brew-cask
fi

brew update
```
