### ISSUE TITLE
Error: Cask 'torbrowser' definition is invalid: Bad header line: parse failed

### ISSUE THREAD

**Issue by glats** [caskroom/homebrew-cask#16016]
When I try "brew cask install torbrowser"
give me the following error : Error: Cask 'torbrowser' definition is invalid: Bad header line: parse failed

thanks for advanced

**Comment by adityadalal924** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)
