### ISSUE TITLE
Calibre Definition is invalid

### ISSUE THREAD

**Issue by BenjaminRCooper** [caskroom/homebrew-cask#16037]
Receiving the following error when trying to follow the process of using gitbook for [Mostly Adequete Guide](https://github.com/MostlyAdequate/mostly-adequate-guide)

```Cask 'calibre' definition is invalid: Bad header line: parse failed```

**Comment by vitorgalvao** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)
