### ISSUE TITLE
Visual Studio Code installation issue

### ISSUE THREAD

**Issue by tundal45** [caskroom/homebrew-cask#16082]
I am getting the following when trying to install Visual Studio Code through cask.

```
$: brew cask search visual-studio-code
==> Exact match
visual-studio-code
$: brew cask install visual-studio-code
Error: Cask 'visual-studio-code' definition is invalid: Bad header line: parse failed
```

It does not seem like the cause is the same as https://github.com/caskroom/homebrew-cask/issues/10240. I don't know what the cause could be beyond case insensitivity that could cause that error.

**Comment by adityadalal924** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by tundal45** [comment]
Thanks!
