### ISSUE TITLE
Error: Cask 'torbrowser' definition is invalid:

### ISSUE THREAD

**Issue by itsNikolay** [caskroom/homebrew-cask#16115]
```
~❯ brew -v
Homebrew 0.9.5 (git revision 7ea6; last commit 2015-12-25)

~❯ brew install Caskroom/cask/torbrowser
==> brew cask install Caskroom/cask/torbrowser
Error: Cask 'torbrowser' definition is invalid: Bad header line: parse failed
```

**Comment by vitorgalvao** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)
