### ISSUE TITLE
can't install anything with brew cask

### ISSUE THREAD

**Issue by puiseux** [caskroom/homebrew-cask#16155]
I try to install picasa with 
```brew cask install picasa```

or 

```$ brew install Caskroom/cask/picasa```

I have the same answer : 
```
Error: Cask 'picasa' definition is invalid: Bad header line: parse failed
```

I have the same answer when i try to install digikam

**Comment by adityadalal924** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew update; brew cleanup; brew cask cleanup
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by puiseux** [comment]
Perfect, it works. 
Thank you
