### ISSUE TITLE
Discussion on implementation of multiple West-European <> German dictionaries

### ISSUE THREAD

**Issue by winkelsdorf** [caskroom/homebrew-cask#16687]
Hi,

I would like to create a Cask for several West-European languages as OSX Dictionaries.

Source of the dictionaries is:
http://clasquin-johnson.co.za/michel/mac-os-x-dictionaries/west-european-languages/german.html

Other langauges are available too:
http://clasquin-johnson.co.za/michel/mac-os-x-dictionaries/west-european-languages/english.html

My workflow requires the following languages:
* German <> English
* German <> French
* German <> Italian
* German <> Dutch

Each of the languages requires two set of OSX Dictionaries to be installed.

Working fine done manually, so an excellent candidate for a Cask.

**Question: Implement them per Language, per Direction or as a Bundle?**

Bundle could be named: ```johnson-german-dictionaries.rb``` and following the above example would need to include 8 download URLs. IIRC it's not possible to download and install multiple files with a single cask, correct?

2nd approach: Create a bask Cask for Johnson's dictionaries, implement 8 version casks. I see a mess of casks here.

Cheers,
Frederik

**Comment by vitorgalvao** [comment]
To be honest, I don’t believe any of those solutions is a good fit for the official repos.

Having a bundle could give the users more dictionaries than what they bargained for. Creating multiple casks would (as you mention) create a mess. It’s fine (acceptable) when some dictionaries have specific needs and are included here as packages/apps (we have a few), but I worry about including dictionary plugins. Above all, I believe this is so niche it won’t be worth the overhead at all.

However, I do also think this is the perfect case for a user tap, and would gladly link to it from our documentation (we did link to some specific user taps in the past, but they since were removed because they were dead).

Will keep this open for now to allow for discussion.

**Comment by winkelsdorf** [comment]
:+1: for the User tap, your arguments against this inside the main repo are plausible. We have had multiple casks with base bundle recently for some Adobe casks in Cask-Versions, and it is a mess.

I'll setup a User repo for this later on.

Let's see what other think about.

**Comment by winkelsdorf** [comment]
Can be closed for now: 

1) I overlooked that the dictcc dictionary plugin is already available as a cask in the main repo (```dictcc-en-de-dictionary-plugin.rb```)

2) The other dictionaries I was trying to create casks for are only available from a download host which prevents deep-linking (heise.de). For complete reference, I was considering implementation for German<>Englisch Dictionary of Beolingus, which is way better that dictcc speaking of the language context, and the German OpenThesaurus. Both available here: http://tekl.de/deutsch/Lexikon-Plugins.html

I contacted the Author of both if we might get a direct official download link, until then this is closed if you agree.

Cheers,
Frederik
