### ISSUE TITLE
Error: Cask 'jabref' definition is invalid: Bad header line: parse failed

### ISSUE THREAD

**Issue by ben-albrecht** [caskroom/homebrew-cask#16706]
Not sure what the solution is, but it appears the `jabref` formula is not working.

`> brew install Caskroom/cask/jabref`

    ==> brew cask install Caskroom/cask/jabref
    Error: Cask 'jabref' definition is invalid: Bad header line: parse failed

`> brew cask install jabref`

    Error: Cask 'jabref' definition is invalid: Bad header line: parse failed

Cask formula in question: [jabref.rb](https://github.com/caskroom/homebrew-cask/blob/master/Casks/jabref.rb)

**Comment by vitorgalvao** [comment]
This error is not a bug, it's caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)
