### ISSUE TITLE
`search` should search all `caskroom/homebrew-*` repos by default (even it untapped)

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#16732]
Refs https://github.com/Homebrew/homebrew/pull/47954, https://github.com/Homebrew/homebrew/pull/47954#issuecomment-170565760, https://github.com/caskroom/homebrew-cask/issues/24418#issuecomment-249695586.

It makes sense and would prevent cases of users who don’t know about the existence of [caskroom/versions](https://github.com/caskroom/homebrew-versions) and our other repos submitting repeated casks, or asking for them when they already exist.

**Comment by Amorymeltzer** [comment]
This is a great idea :clap:

**Comment by adityadalal924** [comment]
I'm confused, doesn't the proposed Homebrew PR fix the issue already?

**Comment by vitorgalvao** [comment]
@adityadalal924 When you `brew search …` it does, but not when you `brew cask search …`, since our search doesn’t tap into theirs (or at least shouldn’t).

**Comment by vitorgalvao** [comment]
Updated repo and discussion to point out every cask repo in the main org should be auto-searched.

**Comment by BenjaminHCCarr** [comment]
I think that the functionality should be the same between `brew` and `brew cask`; though I would advocate rolling this into #24418; and turn `auto-search` on for all.

**Comment by vitorgalvao** [comment]
> I think that the functionality should be the same between `brew` and `brew cask`

Precisely. Now it is not. With this change, it would be.

**Comment by BenjaminHCCarr** [comment]
@vitorgalvao; I absolutely agree, and I think `auto-search` should be the default, and we should try to follow the same "structure" / "flags" as `brew`

That said, for those of us who have been at this a long time, things like `brew instal {{$Cask}}` spitting out `Caskroom/cast/{{$Cask}}`doesn't really make much sense anymore as I understand it; I get having a warning that you aren't compiling, but almost everyone is using `bottles` anyway; an interesting stat would be what % of users in `core` are adding `--flags` to force a `brew` rather than a `bottle`. When you had to tap caskroom, etc, it made sense. But this doesn't really "click with me" anymore, and maybe I should actually open a new issue in HB or at least search 'in:issues'; an example:
```
tyr:~/Code/Homebrew benc$ brew install osxfuse
==> Auto-updated Homebrew!
Error: No available formula with the name "osxfuse" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
These formulae were found in taps:
Caskroom/cask/osxfuse                    Caskroom/versions/osxfuse-beta
To install one of them, run (for example):
  brew install Caskroom/cask/osxfuse
```
if *anything* I think it should say `brew cask install osxfuse`; as someone who is going to blindly C&P isn't going to know what they are doing anyway, so we might as well get them to start with the right syntax.

I would love to see this implemented in `homebrew-cask`; but I personally think it should done as an early step in the roadmap to #24418. And then start moving things to the appropriate repos.

**Comment by vitorgalvao** [comment]
Thank you, @reitermarkus!
