### ISSUE TITLE
Potential issue with Alfred integration

### ISSUE THREAD

**Issue by deinspanjer** [caskroom/homebrew-cask#17374]
I just tried to run "brew update" from within Alfred, and it ended with an error (I'm so sorry but I didn't capture the error before closing the Terminal window).  After that, my brew was completely non-functional.  I found an issue in the brew github issues which matched the error I saw and it provided commands to fix it.  I'm wondering if maybe the brew workflow in Alfred is doing something wrong that caused that problem since I've never had an issue running "brew update" from a normal terminal window before.

https://github.com/Homebrew/homebrew/issues/48256

I'm in the middle of an upgrade right now, but I'll see if I can break it again with the Alfred command and provide more info if so.

**Comment by vitorgalvao** [comment]
There’s no Alfred integration. The one that existed changed Alfred, not homebrew, since even that wouldn’t be the cause.

The homebrew workflow for Alfred isn’t affiliated with us in any way, so you’ll have to contact the developer.

In addition, you’re reporting a homebrew issue. We’re homebrew-cask. Not related.
