### ISSUE TITLE
Bad header line in Caskroom/cask/osxfuse

### ISSUE THREAD

**Issue by brandur** [caskroom/homebrew-cask#18479]
osxfuse fails with this error when I try to install it:

```
$ brew install Caskroom/cask/osxfuse
==> brew cask install Caskroom/cask/osxfuse
Error: Cask 'osxfuse' definition is invalid: Bad header line: parse failed
```

As far as I can tell, my Homebrew and its definitions are up-to-date:

```
$ brew --version
Homebrew 0.9.5 (git revision 6fd6; last commit 2016-02-09)

$ brew update
Already up-to-date.
```

**Comment by vitorgalvao** [comment]
That was caused by an update to how `homebrew-cask` works. Details can be found [here](https://github.com/caskroom/homebrew-cask#important-december-update-homebrew-cask-will-now-be-kept-up-to-date-together-with-homebrew-see-15381-for-details-if-you-havent-yet-run-brew-uninstall---force-brew-cask-brew-update-to-switch-to-the-new-system).

To fix the issue, please run:
```bash
brew uninstall --force brew-cask; brew update
```

If you are still having problems, [open an issue with the appropriate template](https://github.com/caskroom/homebrew-cask#questions-wanna-chat)

**Comment by brandur** [comment]
@vitorgalvao Cool. Thanks for the quick response.
