### ISSUE TITLE
Better description of flash.rb and flash-player.rb

### ISSUE THREAD

**Issue by chincheta0815** [caskroom/homebrew-cask#18883]
Is it possible to get a better description of the difference between flash.rb and flash-player.rb?

**Comment by vitorgalvao** [comment]
We don’t have descriptions, so no, not really, not sure what you’re asking about.

**Comment by vitorgalvao** [comment]
The difference is irrelevant, even, since `flash` points to a page that’ll soon be dead (https://github.com/caskroom/homebrew-cask/pull/18884).

To clarify, though, the difference is `flash` installs the plugin, while `flash-player` installs an app (that you can use to watch `swf` files and the like.
