### ISSUE TITLE
Permission denied `brew install Caskroom/cask/google-cloud-sdk`

### ISSUE THREAD

**Issue by patsplat** [caskroom/homebrew-cask#18974]
Any workarounds?

```bash
$ brew install Caskroom/cask/google-cloud-sdk
==> brew cask install Caskroom/cask/google-cloud-sdk
Error: Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/nokogiri-1.6.6.2/gem_make.out
$ 
```

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by patsplat** [comment]
np will get back to you.  ty

**Comment by patsplat** [comment]
After re-running all commands it works.  Also gem uninstalled nokogiri 1.6.x; after re-installing looks like nokogiri 1.5.x was installed

```bash
$ ls -lh /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/gems/2.0.0/gems/
total 0
drwxr-xr-x   4 root  wheel   136B Aug 22 20:24 CFPropertyList-2.2.8
drwxr-xr-x  11 root  wheel   374B Aug 22 20:25 libxml-ruby-2.6.0
drwxr-xr-x  19 root  wheel   646B Aug 22 20:25 nokogiri-1.5.6
drwxr-xr-x  14 root  wheel   476B Aug 22 20:25 sqlite3-1.3.7
$ 
```

Thanks for help.

Cheers,

Patrick

**Comment by patsplat** [comment]
May have been a conflict btw installing SDK directly vs via cask.  Had initially installed directly, then was transitioning to using cask to manage.
