### ISSUE TITLE
Feature request: `brew cask outdated`

### ISSUE THREAD

**Issue by bgandon** [caskroom/homebrew-cask#19115]
### Description of feature/enhancement

Have a `brew cask outdated` verb, that behaves the same way `brew outdated` does.

### Justification

See: https://github.com/bgandon/brew-cask-outdated

Is it normal that I should use an externel a shell script for this?

### Example use case

```
$ brew-cask-outdated 
facter (2.4.4 < 2.4.6)
filezilla (3.14.1 < 3.15.0.2)
java (1.8.0_72-b15 < 1.8.0_74-b02)
pacifist (3.5.8 < 3.5.9)
puppet (3.8.2 < 3.8.6)
sourcetree (2.1 < 2.2)
sublime-text-dev (3095 < 3102)
```

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/9490

If you wish to pick up that work, feel free to do so. Otherwise, we’ll revisit this when we’re adding upgrade functionality.

**Comment by bgandon** [comment]
The upgrade functionality is not a must for this to exist.

**Comment by bgandon** [comment]
In the meanwhile (we've been waiting for years don't we?) could we advertise users for such workaround?

**Comment by bgandon** [comment]
Why hasn't #9490 been merged already?

**Comment by bgandon** [comment]
The `upgrade ` functionality is a unicorn. 2 years and nothing yet. Why would it be so complicated?

The check list in #4678 is a joke. Who can understand anything to such bullshit? You need to simplify, guys. It's not that complicated. And I coded this `brew-cask-outdated` script to remind you this fact.

**Comment by bgandon** [comment]
It's getting emotional and even more deeply irrational in #9490.

So, what are you expecting me to do?

You say I should ask. Very well. Didn't I just do that in the above thread?
You say I delete comments. Hum hum. Aren't they just above?
You say I never contributed. Ah yes? Didn't I try in #12746?

Could you just be a little bit less scaring please? You just look like Jack Torrance in [The Shining](https://en.wikipedia.org/wiki/The_Shining_(film))!

Now stop insulting, stop assaulting. Honestly. Poor @salimane, how dare you, that ain't any noise! He was just positive!

So.

Your pain has a name. It's called “success”. And it's no bad news.

**Hard subject? Many questions from users that don't understand?** You bet!

→ Then why don't you have a wiki page on that? Just to say people : “It's a long story, but please go there and read it first.” Just stop keeping the relevant information scattered in outstandingly long and numerous threads (I mean all those Github issues like #4678 and #13201). You'll save a lot of time with this, believe me!

**Lacking free time? Too many users requests?**

→ Ask for help, then. Write a wiki page to explain what needs to be done. And stop trying to do it. Just guide others in doing it. Don't be afraid telling people you can't do something. Because when you'll start, people will like you even more. And you'll have a much less stressful relationship with HBC!

**All in all**

You can still continue to do exactly the same as before. Kill yourself trying to find the time you don't have. Getting angry against users because you believe they eat your time making too many requests. Loose your time with way too long bla-bla-bla threads in github issues. Continue telling for years “Thank you, but sorry, this feature will be out next week” and nothing comes out. Insulting newcomers. Assaulting fans. No problem. I don't mind. It's your problem, not mine.

So what's your call Vítor?

**Comment by adidalal** [comment]
I'm a (relatively new) maintainer, and I don't pretend I know the whole history of the project or why certain decisions were made. Frankly, I don't particularly care, the past is the past. I'm also going to ignore semantics/politics/addressing your organizational? concerns for this post, and focus purely on factual and technical info.

I also want a `brew cask outdated` (and, like you, am currently just using a shell script to do the dirty work for me). However, as decided previously and clarified in https://github.com/caskroom/homebrew-cask/issues/13201 (yes it's a long issue, read the first and second to last posts if you need a tl;dr), we're going to *stop* symlinking apps and go back to "actual" install behavior. This is a good thing, and it makes a lot of sense, for reasons explained in that issue.

*However*, this will immediately and irreversibly break all these "upgrade" scripts (because there's no more using the filesystem as a data store), hence the strong pushback/redirection to an issue that you thought was unrelated. For upgrade to work, we need to keep a list of installed cask versions. Have ideas there? Open up a new issue/PR, I'd actually really like to hear them, and (I personally, not speaking for the team here) will commit to giving you my feedback. It's (to me) not a trivial problem, and one that I haven't heard an elegant solution for. 

Additionally, I agree that we should make it easier to contribute more to HBC, and to that end, I've been rewriting and expanding CONTRIBUTING a great deal. Any issue labelled "ready to implement" is also open for contribution - and most aren't too involved so as to be out of the reach of beginners.

**Comment by adidalal** [comment]
Ok, didn't see @vitorgalvao's [previous comment](https://github.com/caskroom/homebrew-cask/pull/9490#issuecomment-187407513), which is basically what I said above. Leaving it anyway, as I've typed it up already.

**Comment by vitorgalvao** [comment]
Hello again, @bgandon,

I won’t be reading your reply attentively. I’ve read just enough to see it was you and skimmed the rest. It’s clear you’re willing to argue even if over minutia, and quite frankly you’re not worth spoiling my mood over.

Lets get be clear: your attitude was the problem, here. It was deeply disrespectful, and that’s enough. You didn’t ask, you didn’t try to familiarise. You came in exalting yourself (and not just here) and insulting the team. I don’t complain about users asking questions or the work this takes as long as we’re all amicable, here. If you think running a successful project means we’re under any obligation to take abuse, or that other users receive the type of reply you did, then you’re severely delusional.

Again, you’re kindly being asked to leave. Please grant that courtesy.

Unless, of course, you are willing to change your tone. If not and you actually think your attitude so far was correct, then that’s your prerogative. Just don’t do it here, because it isn’t welcome.
