### ISSUE TITLE
`find_outdated_appcasts`: Add counter for number of Casks

### ISSUE THREAD

**Issue by adidalal** [caskroom/homebrew-cask#19121]
Envisioning a parameter where the number of Casks to find outdated appcasts for can be set (ie. number of issues to open).

Use case: I may have time to do maybe 10 a day, so right now I just run it and manually exit after I see issues + 10.

I know this doesn't exactly fit with the original plan of "someone run once a week", but with a greater frequency, the delta per run should also decrease.

**Comment by vitorgalvao** [comment]
Your use case is perfectly reasonable, and I do see your point (hadn’t considered the situation before).

My issue with setting a limit is since state (i.e where you last stopped) isn’t saved, that means each day you ask for 10 more, all the ones you already did (and the correct ones) will get pinged again, and the script will take more and more time to get said 10.

A solution might be for it to look at appcasts randomly instead of alphabetically, when setting a limit. Not sure that’s very effective, though (since casks that are usually updated at the same time, like `navicat`s would lose the advantage of being updated all at once).

The solution might not lie in `find_outdated_appcasts`, but in one of the others. A variation of a solution I have been thinking about for a while would be something like:

Change `find_outdated_appcasts` to:

+ When starting, check if there’s an `outdated appcast`-labeled issue.
  + If yes and it is assigned to someone, abort.
  + If yes and it is not assigned to anyone, close it. Continue.
  + If no, continue.
+ Open an new empty issue labeled `outdated appcast` and assign it to yourself.
+ Check all appcasts.
  + If aborted, delete the empty issue.
+ Edit issue with all outdated appcasts.
+ Unassign yourself.

Change `fix_outdated_appcasts` to:

+ When starting, check if there’s an `outdated appcast`-labeled issue.
  + If yes and it is assigned to someone, abort.
  + If yes and it is not assigned to anyone, assign yourself. Continue.
  + If no, abort.
+ Get all outdated casks in issue.
+ Start fixing them.
  + If aborted, get list of already fixed casks and remove them from issue. Unassign yourself.
+ If finished, delete issue.

This would allow for a smaller barrage of open issues, and would better allow for multiple maintainers to fix casks are their leisure, without having to commit to doing them all.

**Comment by adidalal** [comment]
Sounds like a solid plan, happy to test anything you whip up! (Not a priority, I'm quite okay with aborting each time for now.) My only sticking point is poor default behavior for opening appcasts, but will write up my thoughts and suggestions for that later on, not at a computer at the moment. 

A quick note, you can't delete issues on GH, only close them.

**Comment by vitorgalvao** [comment]
> A quick note, you can't delete issues on GH, only close them.

Right. Corrected.

> My only sticking point is poor default behavior for opening appcasts

Yes, I have been thinking about that. There are some Safari plugins that can show XML and other formats directly in the browser, like Chrome, but I’m not convinced that’s the best solution. Running `less` with syntax highlight could work, but all I can find about that requires installing additional software (so an extra dependency) and only works on local files, so it requires actually downloading and saving the appcast to a file (which I’d like to avoid) and obfuscates the initial `cat`ting of the cask, which is also a minus. Using Quicklook instead of `less` solves the latter, though not the former. Other suggestions are welcome, naturally.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/19274.

I’ve made some tweaks to the original plan (updated in that issue and in the comment here, as well).
