### ISSUE TITLE
(Yet Another) Formula request: Franz

### ISSUE THREAD

**Issue by andreis** [caskroom/homebrew-cask#19368]
This just popped up on Product Hunt, it's a unified chat app for multiple services.

http://meetfranz.com/

**Comment by andreis** [comment]
5 minute review: pretty bare Bootstrap-in-Electron kind of app, which just embeds the web versions of said services. Might be promising, but currently it's pretty unattractive.

**Comment by vitorgalvao** [comment]
Its value proposition is actually pretty strong, I’d say. If you need to use multiple chat services, use it instead of fumbling around with multiple apps. If you don’t, than use the native apps for what you do use.

You might be unimpressed with the technology they chose, but that doesn’t really affect how useful people will find it. I’d say their target is well defined, and for their target, this’ll be great. Also, still on the topic of the technology, there’s really no other way they could support these much services without going insane. Also, some they wouldn’t be able to support at all, due to closed APIs.

**Comment by adidalal** [comment]
LOL dropbox link for download, a *real* MVP

**Comment by magicgoose** [comment]
> if you uninstall this use something like AppCleaner; it leaves a lot of junk behind when it installs

A properly written formula should include `zap` instructions which should remove all that junk, right?

**Comment by vitorgalvao** [comment]
> A properly written formula should include `zap` instructions which should remove all that junk, right?

Right.

**Comment by vitorgalvao** [comment]
Done in https://github.com/caskroom/homebrew-cask/pull/19403.
