### ISSUE TITLE
Preventing perpetually out of date appcasts, other concerns for cloud-based apps

### ISSUE THREAD

**Issue by bengotow** [caskroom/homebrew-cask#19386]
Hey folks,

I'm one of the developers of Nylas N1, an open-source mail client. There's currently an out of date cask for N1 here: https://github.com/caskroom/homebrew-cask/blob/master/Casks/nylas-n1.rb.

I've used `homebrew` a lot over the years, but I'm a bit behind the times and unsure of the value-add provided by `homebrew cask`. As the maintainer of a project moving very quickly, I have a couple concerns:

- The cask seems to be updated manually, and is perpetually out of date, even if only by a week. How can we ensure this does not happen, other than pull requesting changes ourselves *every few days*?

- Our Mac app updates on it's own. Is homebrew really necessary in these scenarios? Is there any way that rather than link to any particular version, the cask could just link to our permanent download URL: https://edgehill.nylas.com/download?platform=darwin

- Our app is powered by cloud sync infrastructure (like Mailbox or Spotify) and updates roll out to both constantly. There's really no scenario in which a user would want an old version of N1, and in many cases it just won't work because the platform has moved on. We work hard to make sure everyone moves to the latest versions quickly and without interruption via autoupdaters, update banners, etc. Is there any way we can make old versions of the cask unavailable?

**Comment by adidalal** [comment]
The value-add is installing and managing GUI OS X apps from the command line.

We strongly encourage the use of versioned Casks, and they're semi-automatically updated via some scripts we're in the middle of refining. It is *really easy* to update Casks for users via `cask-repair`. It's even scriptable (ie. add `cask-repair -v {{version}} -b nylas-n1` to your release script. We're fast about merging changes, though we're all volunteers so no SLA or guarantees).

We don't mess with inbuilt updates, that's what the `auto_updates` line is for. At some point we'll move away from symlinking to actually moving to /Applications, and hat makes sure that an outdated Cask won't overwrite/interfere with Sparkle etc.

`brew update` will update Cask definitions for end users, and many people script it such that updates are automatically installed - not sure what you are looking for there.

**Comment by bengotow** [comment]
Hi @adidalal—thanks for the reply! `cask-repair` does look easy to use—I'd just rather not have a third-party trying to keep track of our releases in the first place.

Would it be possible for us to change the cask so that it did not include a `SHA` hash and linked to `https://edgehill.nylas.com/download?platform=darwin`, which always serves the latest version of the app? If you wanted to run an update check, you could hit that URL and check the `Content-MD5` or `ETag` header. That would allow you to build a "check for update" flow that does not download things unnecessarily or depend on knowing what the latest version of the app is in a third-party database.

Alternatively, could we somehow link the cask to our GitHub releases, which do get updated immediately when we ship a release? https://github.com/nylas/N1/releases

**Comment by adidalal** [comment]
Yes, we can change the appcast to `https://github.com/nylas/N1/releases.atom` if it's a better source of update information.

Also pinging @vitorgalvao for thoughts.

**Comment by vitorgalvao** [comment]
> I'd just rather not have a third-party trying to keep track of our releases in the first place.

Sounds like you’d prefer for us to not include your app in homebrew-cask in the first place. If that’s the case, we’d be happy to oblige.

> Would it be possible for us to change the cask so that it did not include a `SHA` hash and linked to `https://edgehill.nylas.com/download?platform=darwin`, which always serves the latest version of the app? If you wanted to run an update check (which is not really necessary because the app auto-updates), you could hit that URL and check the `Content-MD5` or `ETag` header. That would allow you to build a "check for update" flow that does not download things unnecessarily or depend on knowing what the latest version of the app is in a third-party database.

That solution wouldn’t really work. For one, why would we want an appcast in the first place if we’re not using it to update the version in the cask? We also prefer to have versioned URLs as much as possible, as people overwhelmingly prefer to have it checked on download (we have various issues on it, and the preference is clear).

> Alternatively, could we somehow link the cask to our GitHub releases, which do get updated immediately when we ship a release? https://github.com/nylas/N1/releases

No, because those automated scripts are inconsistent depending on the app, so we can’t rely on them and hence have no mechanism to do so. I think, @adidalal, that @bengotow was asking for our cask to be updated automatically based on it, not necessarily for us to change `appcast`.

In all honesty, I’d rather not include a cask than have a crippled one. If you prefer for us not to include it, please feel free to say so, and we’ll remove it. You’ll still be able to provide a cask yourself, and then just tell your users to run `brew cask install {{url_to_your_cask}}`.

**Comment by i-c** [comment]
> We also prefer to have versioned URLs as much as possible, as people overwhelmingly prefer to have it checked on download (we have various issues on it, and the preference is clear).

I think what @bengotow is trying to get at here is that, because the N1 desktop app leans heavily on the server APIs and is in active development, a versioned cask actually has negative value here. Downloading a specific version rather than the latest available from the source, at least until there's a production-stable version of N1 client and server available, has a good chance of getting something that just plain doesn't work.

**Comment by vitorgalvao** [comment]
@i-c Yes, I understand that. But again

> I'd just rather not have a third-party trying to keep track of our releases in the first place.

That sounds like they prefer to not have a third-party involved *at all*, and that is fine, we respect those wishes. They can either:

+ Host the cask themselves.
+ Ignore having a cask and ask us to not provide one.
+ Same as above, but reintroduce the cask when they feel the app is stable.

Either one is fine. Having a deliberately crippled cask waiting for an alleged time when the app will be stable isn’t that great. The thing I like the most about homebrew(-cask) is how easy it is to have your own tap, you’re not beholden to the main repository.

What difference does it make here, even? We’re so fast merging contributions (especially if they’re submitted without mistakes), that having the cask download the outdated version for a few hours after release isn’t significant. Even if for some random chance you did download that marginally outdated version (and remember, that will *only happen if you’re downloading the app for the first time*) the app would just auto-update. Problem solved.

 The slowness isn’t relevant, here, because it won’t have any meaningful effect. However (once again), *it seems like @bengotow is uncomfortable having a third party controlling one of the distribution channels of their app **and that is absolutely fine***. He just needs to say so (so we’re sure that is actually the case) and we’ll remove the app immediately and not allow it to be submitted again.

**Comment by bengotow** [comment]
Hey! Thanks for the reply—I think you're definitely correct. As a project maintainer there's a laundry list of places that try to cache our releases or serve them on their own - Softpedia, Download.com, etc. `Homebrew-cask` isn't an ad-ridden download site, and it's really a great idea,  but it effectively does the same thing.

I really appreciate that you're aiming to keep casks up to date and rev them quickly when new releases come out. An hour or a day isn't a problem at all - and you're right that those users will just see an update banner when they launch the app, restart it, and be up to date. It's definitely fine to keep the cask and update it periodically.

That said, I feel like keeping appcasts up to date is crucial for the success of `homebrew-cask`, and you're fighting an uphill battle (https://github.com/caskroom/homebrew-cask/issues/19246) with the current approach. I was hoping this issue might spark a discussion about how to create cask files that are more permanent or don't require version bumping at all, especially since there are several places we already post releases and their SHA hashes.

If anyone stumbles across this in the future, I think a few solutions might be:

 - Support checking an RSS feed and reading the SHA hash and latest binary URL from there. Sparkle is the most popular Mac auto-updater utility, and it uses an RSS feed like this: http://sparkinspector.com/sparkle/feed.xml. (Hey - another of my apps has a cask!) We post releases to GitHub, and they also serve XML: https://github.com/nylas/N1/releases.atom

 - Support making an OPTIONS request to the download URL and checking the ETag response header, and use that to identify whether the user's version is outdated.

**Comment by vitorgalvao** [comment]
None of those options will work. `appcast` (the stanza) isn’t new. It was actually introduced a long time ago so we had a bunch of data to look at them. At first the idea was indeed to parse them automatically, and here’s the thing: it can’t be done. Even sparkle appcasts vary wildly. There simply is (currently) no way to automatically parse all appcasts and maintain our sanity.

As for the second option, not only will that also provide inconsistent results, you’re assuming upgrade functionality, which doesn’t (yet) exist in homebrew-cask.

As for the outdated appcasts issue you linked, that is actually an outlier. Those scripts (yes, that issue was machine generated and there is also a script that will help update all of it) are pretty recent and suffered a massive change recently *geared exactly* to help fix everything quicker. The new changes aren’t yet merged, however.

---

As an unrelated note, now that I have you, what do you think of softpedia in regards to your app? I have a small app that they picked up and said that if I didn’t want it featured, I could just say and they’d remove it, and I’m still not sure how I feel about it.

From all those kinds of websites, softpedia actually seems marginally acceptable, and I see a lot of popular apps there. Was hoping to pick some brains on the subject. Do you have any feelings on it?
