### ISSUE TITLE
Unity cask 404s

### ISSUE THREAD

**Issue by kepler0** [caskroom/homebrew-cask#19436]
Just went to install the Unity cask and got this error:

```
$ brew cask install unity
==> Downloading http://netstorage.unity3d.com/unity/cc9cbbcc37b4/MacEditorInstaller/Unity.pkg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'unity' with message: Download failed: http://netstorage.unity3d.com/unity/cc9cbbcc37b4/MacEditorInstaller/Unity.pkg
```

**Comment by adidalal** [comment]
Just so you know, the unity cask is *just* the unity editor. 

Use the unity download-assistant for a normal install to select components https://github.com/caskroom/homebrew-cask/pull/19471

Else, being fixed in https://github.com/caskroom/homebrew-cask/pull/19470. Will also update ios and android build tools, this time.
