### ISSUE TITLE
Problems installing gitkraken

### ISSUE THREAD

**Issue by ribeiroevandro** [caskroom/homebrew-cask#19466]
When trying to install gitkraken with `brew cask install gitkraken` command is generating this error `Error: Download failed on Cask 'gitkraken' with message: Download failed: http://release.gitkraken.com/darwin/v0.7.0.zip`

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
