### ISSUE TITLE
Can not uninstall puppet

### ISSUE THREAD

**Issue by nexussafe** [caskroom/homebrew-cask#19561]
OS X 10.11

    % brew cask uninstall puppet
    ==> Running uninstall process for puppet; your password may be necessary
    ==> Removing files from pkgutil Bill-of-Materials
    Password:
    ==> chmod: Unable to change file mode on /usr/share/doc: Operation not permitted
    Error: Command failed to execute!
    
    ==> Failed command:
    ["/usr/bin/sudo", "-E", "--", "/bin/chmod", "--", "777", "#<Pathname:/usr/share/doc>"]
    
    ==> Output of failed command:
    
    
    ==> Exit status of failed command:
    #<Process::Status: pid 25040 exit 1>

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by nexussafe** [comment]
I opened a new bug report https://github.com/caskroom/homebrew-cask/issues/19661
