### ISSUE TITLE
Adobe Apps

### ISSUE THREAD

**Issue by lukeadams** [caskroom/homebrew-cask#19746]
It looks like there are a handful of Adobe applications already in Cask. What do you guys think about adding the rest of them?
I found a [great list with the most recent download links](http://prodesigntools.com/adobe-cc-2015-direct-download-links.html#ddl), so it would be relatively simple to generate formulae for each. I might contact the author of that post to see how they are scraping the links.
Have:
- Air
- Air Runtime helper ("ARH")
- Bridge CC
- CC Desktop App
- Digital Editions
- DNG Convertor
- Illustrator CC
- Indesign CC
- Photoshop CC
- Lightroom
- Reader

Missing:
- [ ] InCopy CC
- [ ] InCopy CC
- [ ] Dreamweaver CC
- [ ] Dreamweaver CC
- [ ] Animate CC
- [ ] Premiere Pro CC 
- [ ] After Effects CC
- [ ] Audition CC
- [ ] Prelude CC 
- [ ] SpeedGrade CC 
- [ ] Media Encoder CC 
- [ ] Adobe Muse CC 
- [ ] Edge Animate CC 
- [ ] Edge Code CC 
- [ ] Edge Inspect CC	
- [ ] Edge Reflow CC 
- [ ] Edge Reflow CC 
- [ ] Fuse CC 
- [ ] Adobe Scout
- [ ] Adobe Drive
- [ ] Extension Manager CC

**Comment by vitorgalvao** [comment]
I clicked a bunch of those links, and they all gave an *access denied* error.

You’re absolutely welcome to submit PRs for those other casks (we don’t call them formulae, as those are a different thing), but the core team will likely not do it. Apart from those not having any demand (here), they’re anything but easy to add (as expected from such a consumer-hostile company). Just ask @winkelsdorf how hard those are to do right. On the other hand, since he has already done a great job with the main apps, you might have an easier time by following the already existing casks. I doubt it’ll be the same for all of those, though.

**Comment by lukeadams** [comment]
> all gave an access denied error.

The Adobe trials require a cookie to be set: (snippet from [InDesign cask](https://github.com/caskroom/homebrew-cask/blob/master/Casks/adobe-indesign-cc.rb#L5-L7))
```ruby
url 'http://trials3.adobe.com/AdobeProducts/IDSN/11/osx10/InDesign_11_LS20.dmg',
  user_agent: :fake,
  cookies: { 'MM_TRIALS' => '1234' }
```
> Apart from those not having any demand

Totally reasonable. I needed to install Animate CC and modified @winkelsdorf 's Illustrator cask and it worked like a charm (PR incoming). I can just submit them as I need them.

Great to hear your thoughts! :smile:

**Comment by adidalal** [comment]
@lukeadams Submitting them as you need them would be the best option, for sure. Thanks for contributing back!

**Comment by danielbayley** [comment]
@lukeadams I’m also interested in getting Adobe’s generally **terrible** installation process to work better with Cask, and have PRs almost ready for After Effects, Premiere Pro and Media Encoder based on the existing casks.

@vitorgalvao Are we intentionally treating _adobe-creative-cloud_ as a separate thing from the individual app casks like _adobe-illustrator-cc_?
I just tried `brew cask install adobe-illustrator-cc` which resulted in `/Applications/Adobe Illustrator CC 2015/…` while installing _Creative Cloud_ will result in `/Applications/Adobe Creative Cloud/…`

Also, is the intentional behaviour to install the `en_US` version by default and then put all other versions in _homebrew-versions_? What about `en_GB` (which is the locale I actually want…)

**Comment by vitorgalvao** [comment]
> Also, is the intentional behaviour to install the `en_US` version by default and then put all other versions in *homebrew-versions*?

[Yes](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#regional-and-localized).

> @vitorgalvao Are we intentionally treating *adobe-creative-cloud* as a separate thing from the individual app casks like *adobe-illustrator-cc*?

Adobe Creative Cloud is a beast. If you can devise a good uninstaller, we would appreciate it.

**Comment by danielbayley** [comment]
> Adobe Creative Cloud is a beast. If you can devise a good uninstaller, we would appreciate it.

Is that a euphemism for _mess_? 😄

I’d like to get it to _install_ properly first before I worry about removing all the junk they scatter _all over_ the place!

@vitorgalvao Speaking of which, do you have an opinion on my second question?

**Comment by vitorgalvao** [comment]
> Is that a euphemism for mess?

Yes. A jumble of messy beasts.

One of the considerations with the uninstallation of Creative Cloud is to making sure Adobe apps installed stand-alone are not also removed.

> I’d like to get it to install properly first before

It’s a `.app` installer, it needs to be manually run since it calls a GUI (and we have a policy to not call GUIs). There’s nothing wrong with the installation.

> do you have an opinion on my second question?

Everything seems to be working fine in that regard. Adobe picks the installation path, not us. It makes sense that if you install the application without the whole suite, it has a different path.

> Shouldn’t this issue should be open?

[No](https://github.com/caskroom/homebrew-cask/issues/19746#issuecomment-195746677). We (the core team) will not work on it, and having the issue open adds no value.

**Comment by lukeadams** [comment]
I am aware that this issue is closed, but I just thought I should mention:
while the links included in that list I posted ages ago do work, they are not hosted by Adobe. 
Taking @danielbayley 's AE cask for example, the url from that list is http://prodesigntools.com/trials3/AdobeProducts/AEFT/13_5/osx10-64/AfterEffects_13_5_LS20.dmg
and should become
http://trials3.adobe.com/AdobeProducts/AEFT/13_5/osx10-64/AfterEffects_13_5_LS20.dmg
Remember it needs 'MM_TRIALS' => '1234' set as a cookie if you are testing with cURL

**Comment by adidalal** [comment]
Those links actually do redirect to adobe links, but track your download (prodesigntools gets a commission based on referrals, if I remember correctly).

Regardless, the "clean" links are as you posted above work correctly

**Comment by lukeadams** [comment]
That's awesome! I had no idea.
