### ISSUE TITLE
Cask Upgrade - small utility

### ISSUE THREAD

**Issue by Tenzer** [caskroom/homebrew-cask#19924]
First of, thank you for making this project, it helps make OS X slightly more Linux like :)

I have written a small utility to help Cask users check if they have outdated packages or have old versions left behind that could be cleaned up, it is available at: https://gist.github.com/Tenzer/0b76ef1c4e9bf146b003. I was wondering if you would accept a PR for adding a link to it in the README file here, in case other users may find it useful?

**Comment by vitorgalvao** [comment]
Thank you, but this is something we need to work on natively. There are many scripts like this, and they all suffer from the same flaws: they hardcode `/opt/homebrew-cask/Caskroom`, which is a mistake because there’s no guarantee the user is using that directory and they rely on parsing the directories inside the caskroom to figure out what needs to be updated, [which will definitely break](https://github.com/caskroom/homebrew-cask/issues/13201).
