### ISSUE TITLE
megasync package is not working

### ISSUE THREAD

**Issue by frantzmiccoli** [caskroom/homebrew-cask#20162]
From a fresh El Capitan 10.11.4 installation.

    brew cask install megasync

The app is recognised in spotlight but doesn't start, the actual client does work though: `https://mega.nz/MEGAsyncSetup.dmg`.

**Comment by vitorgalvao** [comment]
Did you put the app `/Applications`, like the `caveat` tells you to?

Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by frantzmiccoli** [comment]
No, I didn't follow that instruction (not even sure that I did notice it), because I ran this command alone a lot of others and expected the client to be installed. I am now using their regular client. I will try to pay attention for the next bug reports.
