### ISSUE TITLE
praat cask broken

### ISSUE THREAD

**Issue by psibre** [caskroom/homebrew-cask#20488]
Once again, praat can no longer be installed:
```
$ brew cask install praat
==> Downloading http://www.fon.hum.uva.nl/praat/praat6014_mac64.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'praat' with message: Download failed: http://www.fon.hum.uva.nl/praat/praat6014_mac64.dmg
```

**Comment by psibre** [comment]
This is a regression of a chronic problem, see [this comment](../pull/13384#issuecomment-133793954) for an explanation.
Not sure why the URL was reverted in 589dad930862848aa12fc3fc69d18abb7c3aa038... maybe it has to do with #17498?

**Comment by vitorgalvao** [comment]
The cask now has an appcast to detect when it is updated, so this isn’t a big issue.

It’s not a problem if the cask breaks with new versions, why would you want to install an outdated version, anyway?

Updated.

**Comment by psibre** [comment]
@vitorgalvao I did notice the `appcast` stanza, but how does it work? Could you please point me to some public documentation?
If I understand correctly, the atom feed in the appcast will send a notification that there's a new version, but I don't know who receives that notification, and whether the cask will still have to be manually updated? If so, then I do think it would make sense for the cask to *not* break before somebody manually updates it, because as we've seen it breaks the ability of everybody to install the app normally for days...

**Comment by vitorgalvao** [comment]
As to how `appcast`s work, see https://github.com/caskroom/homebrew-cask/issues/19121 and https://github.com/caskroom/homebrew-cask/pull/19274. They’re not for users, but for maintainers.

I very much doubt updates break everyone’s ability to install the app for *days*, at least regularly. We’re pretty fast about merging PRs. It’ll also only affect your first install, and I also doubt there are people regularly installing it for the first time with homebrew-cask, right at the moment when it breaks.

If you’re using homebrew-cask to upgrade the version you already have, then you’re doing it wrong, since we don’t support upgrades yet (hence any method used is unsupported).

Using `appcast`s for updates is a recent development still in the works, so the idea is to improve that. I actually find it beneficial that a cask breaks in this way right now, as it provides an example of what to watch out for, and a metric to improve those scripts.
