### ISSUE TITLE
Sketch sha256 mismatch

### ISSUE THREAD

**Issue by JakeCobley** [caskroom/homebrew-cask#20538]
Error: sha256 mismatch
Expected: 13c449c0e951178ee8d15b6ea9dd41871f3338b3035b3b628861f084eaa41e9c
Actual: 8879703703babf42e33682377e10199368d8a66e53af0af1743c78a0e0b6a8cf
File: /Library/Caches/Homebrew/sketch-3.6.1.zip

**Comment by adidalal** [comment]
Update HBC, Sketch 3.7 is out.

-----
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
