### ISSUE TITLE
aseprite 1.1.4.1 cask not installing : symlink is not there

### ISSUE THREAD

**Issue by trollworkout** [caskroom/homebrew-cask#20753]
I always get this error

`Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/aseprite/1.1.4.1/aseprite.app'`

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.

**Comment by adidalal** [comment]
```
==> Downloading http://www.aseprite.org/downloads/Aseprite-v1.1.4.1-trial-MacOSX
Already downloaded: /Library/Caches/Homebrew/aseprite-1.1.4.1.dmg
==> Verifying checksum for Cask aseprite
==> Symlinking App 'Aseprite.app' to '/Applications/Aseprite.app'
🍺  aseprite staged at '/opt/homebrew-cask/Caskroom/aseprite/1.1.4.1' (127 files, 12M)
```

https://github.com/caskroom/homebrew-cask/pull/20755

**Comment by trollworkout** [comment]
Still not working for me
![screen shot 2016-04-23 at 10 58 08 pm](https://cloud.githubusercontent.com/assets/6987027/14765229/e7134b4a-09a6-11e6-8d11-99f7cf7d6f67.png)

**Comment by adidalal** [comment]
you need to brew update
