### ISSUE TITLE
Appcast checkpoint

### ISSUE THREAD

**Issue by benwa** [caskroom/homebrew-cask#20898]
The Atom feed for GitHub releases doesn't have a `<pubDate>` tag, making the `curl --compressed --location "{{appcast_url}}" | sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256` in [appcast.md](../blob/master/doc/cask_language_reference/stanzas/appcast.md) incorrect for .  It does however have an `<updated>` tag.

**Comment by vitorgalvao** [comment]
Having that `sed` section does not mean it’ll be incorrect when there is no `<pubDate>`, it just means it’ll do nothing. That’s by design.

The problem is some appcast have a `<pubDate>` that changes to the date the appcast was accessed, making it give a different `sha256` when it wasn’t in fact changed. That circumvents those.

**Comment by benwa** [comment]
Ah, so the `checkpoint` is the `sha256` of the entire feed, not just the date?

**Comment by vitorgalvao** [comment]
Yes. The `sed` section is there to remove the `<pubDate>` tag entirely.
