### ISSUE TITLE
Stattransfer cask error

### ISSUE THREAD

**Issue by lucasrdc** [caskroom/homebrew-cask#21307]
Stattransfer cask has a checksum md5 mismatch, and, before change this I found this error below:

`==> Downloading https://www.stattransfer.com/downloads/stdemo.dmg`
`Already downloaded: /Library/Caches/Homebrew/stattransfer-13.dmg`
`==> Verifying checksum for Cask stattransfer`
`==> Running installer for stattransfer; your password may be necessary.`
`==> Package installers may write to any location; options such as --appdir are ignored.`
`Error: pkg source file not found: '/opt/homebrew-cask/Caskroom/stattransfer/13/st_installer_v13.pkg'`

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
