### ISSUE TITLE
FYI: Wondershare Casks (and others)

### ISSUE THREAD

**Issue by christopheranderton** [caskroom/homebrew-cask#21399]
I replied to the pull at: https://github.com/caskroom/homebrew-cask/pull/19659 
but maybe it's better to report this as a issue instead. 

Regarding Wondershare Video Converter Ultimate.app cask (and other Wondershare Casks). 
After installing the Cask, the application will install ”helper” apps and ”downloader” apps silently upon the first launch (and sending data back and forth, even when not using the app.). This applies to Wondershare apps but also to the myriad of the OEMs of Wondershare, such as iSkysoft and others.

### Example

Installation of Wondershare Video Converter Ultimate.app (same app as iSkysoft Video Converter .app).

Upon launch it will silently install following items into your user library: **Wondershare Helper Compact.app** and **MediaDownloader.bundle.**

**The paths created with the added files:**

`$HOME/Library/Application\ Support/MediaDownloadKit`

`$HOME/Library/Application\ Support/Helper`

and in some cases at: `$HOME/Library/Helper` and `$HOME/Library/Helpers`

Removing the files or directories will result that upon the next launch, they will be reinstalled (silently). Also, many of the releases from Wondershare and their OEMs includes XPC Vulnerabilities (the software is using 99% Open Source code, even if they don't give a darn about the licenses).

#### More

This applies to almost 150 or even more applications from Wondershare, iSkysoft (another brandname for Wondershare), Xillisoft, Aimersoft, Xiisoft, Tenorshare, Aiseesoft, AnyBizSoft, Kigo, Tipard, MacX and plenty of other OEMs (Wondershare, or a Wondershare owned company is selling complete packages at the Chinese market).

Even if anti-virus or malware scanners don't warn about this, most of these apps are not considered to be trusted. Some apps as example from Wondershare tracks the user, even if you have uninstalled the Wondershare applications in question (as the helper apps are still in place).

Just a FIY. :)

Cheers!

**Comment by adidalal** [comment]
Same as uTorrent, which we had an earlier discussion about in https://github.com/caskroom/homebrew-cask/issues/15799 - any thoughts on a possible solution?

**Comment by vin047** [comment]
Hi, I was the one who originally added the Wondershare Video Converter Ultimate cask. Having reviewed @christopheranderton comment, I can see on my Mac that these extra apps/bundles have indeed been installed on my system (thanks for notifying). I wasn't aware that it installed extra apps and wouldn't have submitted the cask (or even installed it) had I known.

Hence I think it should be removed. My reasoning is because I believe the default cask tap should be a trusted one. When you're adding an external tap, you have to be wary as you're trusting the maintainer. With the default tap, you're trusting the community then that it's relatively safe (I realise that this is general bad practice but I would say that this probably ends up making the user more aware of suspicious apps - when it's not in the default tap there'll be a record of why X.app was rejected/removed).

And anyway, there's nothing stopping a user from installing an app the old fashioned way, or setting up their own tap and sharing with others who want these apps, regardless of their trustworthiness

Regarding the point made in the other discussion about having to apply this to other casks; I think it should apply and they should be removed too (exceptions made for well known OEMs like Adobe). However I realise that this would be a daunting task and so respect your decision if you don't think what I've said is a strong enough argument. All I can add at this point, is that as a big fan and user of Homebrew Cask, the idea of a default trusted repo is very appealing, and I'd much rather give up the convenience of having all these apps located in Homebrew Cask if it meant a more secure and safe repo. I'm willing to help out too if you decide to go down this route.

**Comment by adidalal** [comment]
Added in a PR, but the points made in the earlier discussion still stand. In particular, https://github.com/caskroom/homebrew-cask/issues/15799#issuecomment-164276364 - that needs to be addressed, as that is the root of the problem/discussion.

**Comment by vitorgalvao** [comment]
What I wrote in https://github.com/caskroom/homebrew-cask/issues/15799#issuecomment-164252398 also still stands (emphasis added):

> That would, however, also mean we should take a stance against **every sourceforge cask**, as they’re becoming shadier and shadier, and we know they’re starting to bundle adware with their downloads.

Those are *a lot* of casks. In addition, think about the notion mentioned by @vin047:

> I'd much rather give up the convenience of having all these apps located in Homebrew Cask if it meant a more secure and safe repo. 

To me, that is a dangerous idea. [We want you to not trust us blindly](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/url.md#when-url-and-homepage-hostnames-differ-add-a-comment). I don’t want users to be so trustworthy of HBC that if we make a mistake it won’t be caught. Taking this stance is, I believe, how we become worthy of your trust: by doing the best we can to be auditable and inviting you to do so.

[It’s the responsibility of users to know the apps they are installing](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not-a-discoverability-service.md). As @Amorymeltzer (taking the chance to ping him on this) [said](https://github.com/caskroom/homebrew-cask/issues/15799#issuecomment-164276364):

> We're a service, not a decision-making enterprise.

And not making those decisions is a feature, not a bug. @Amorymeltzer [again](https://github.com/caskroom/homebrew-cask/issues/15799#issuecomment-164276364):

> if a user wants bad software then so be it, that's their call.

Ultimately, I see nothing in this issue that answers the conclusions in https://github.com/caskroom/homebrew-cask/issues/15799.

What do you do if an app you want is not in HBC? You add it and/or you install it manually. Removing them is not really a deterrent.

[Having said that all that](http://youtu.be/ENHVQ2gslp8), I’m a bit more convinced on the `caveat` route (after all, these casks do install crap at install time) **until** I again think of all the sourceforge casks. Are we going to add the `caveat` to all of those? And what about the ones that they haven’t infected and we’re unfairly punishing the developers?

The issue remains in my view: none of the presented options acceptably tackles the issue.

**Comment by christopheranderton** [comment]
@vin047 Yeah, back then, i used some of their products without even think about it. Then i started on a new job where there was a whole chapter in the company security guidelines about Wondershare (and the OEMs and clones of their apps). 

It's not really easy to know everything about every application or developer out there. 

@vitorgalvao Maybe a more visible ”Disclaimer” warning for monsters upon the first install of a cask. Or maybe a very short global cask ”caveat”. It's quite common, specially in applications supporting third party add-ons/plug-ins. Homebrew is not about plug-ins or add-ons, and while the user should know about the things they install, it's not reality (in many ways). A warning /disclaimer may not reach everyone, but if someone reads the warning and decides to do some research before installing that super cool application, it may save a week for that person of getting rid of adware or malware. So i think it's worth it.

Maybe it's have been discussed already?

Of course, the warning should be in the lines what other projects has. Not to make people run away fearing the evil lurking Monsters in the Caskroom! 

And at last, sorry for my spectacularly bad english.

**Comment by alebcay** [comment]
I think I have to agree with @vitorgalvao on this one. It is ultimately up to the end user to maintain the safe and desired operation of their machine. I think it's a good idea to provide a warning/`caveats`, but removing even adware-infested Casks could set a precedent of removing whatever Casks we maintainers and/or contributors feel fit. Under this precedent, we should go back and remove uTorrent as well (#15799) along with any app that may display ads or promotional content.

I don't think it's Homebrew Cask's responsibility to act as a rogue app watchdog for end users, and I would be concerned about the credibility of my judgment were we to shoulder this responsibility. If we were to go down that path, we should revise the current [Cask rejection criteria](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/rejected-casks.md). Under the current criteria, we would not remove the Casks in question because they probably won't put the entire project at risk, and they do not satisfy any of the other options listed either.

tl;dr: If we really want to make the inclusion of malware/adware a valid reason for rejecting/excluding an app, let's establish it as a precedent first in docs and not make this a corner case.

**Comment by vitorgalvao** [comment]
Closing.

It’s very well possible there is an acceptable solution to this problem, but one hasn’t been presented yet.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/22383/

@christopheranderton @vin047 We’re still discussing the approach, but if approved, you’ll need to do the outlined steps, including reporting the app to Apple. You may wish to do that either way.

**Comment by magicgoose** [comment]
I suggest starting at least by showing this information when user executes `brew cask info …` command. This way it's not intrusive at all, because it will still install just like any other cask, but if the user is in doubt, they can use that command to see if there might be anything suspicious.
And in case of sourceforge casks, there can be simply a notice that it's a sourceforge cask, and the user can decide for themselves if it's acceptable for them.

@christopheranderton said `It's not really easy to know everything about every application or developer out there. `, I agree, it'd be nice if HBC will make it easier to know what you are installing.

**Comment by adidalal** [comment]
Caveats are shown when using brew cask info, not sure what else you are referring to
