### ISSUE TITLE
brew cask not finding installed apps

### ISSUE THREAD

**Issue by meireles** [caskroom/homebrew-cask#21896]
I have a few applications installed with `brew cask install` but a  `brew cask list` returns `Warning: nothing to list`.
Nevertheless, I can see all my apps installed when I:

    ls /opt/homebrew-cask/Caskroom/
    basictex		java			rstudio-preview		tex-live-utility
    cyberduck		macdown			slack			transmission
    firefox			qt-creator		sourcetree

Any ideas of how I can fix this?

**Comment by jawshooah** [comment]
The default Caskroom path recently changed to `/usr/local/Caskroom` (#21857). You can either `mv /opt/homebrew-cask/Caskroom /usr/local` or, as a transitional measure, add `--caskroom=/opt/homebrew-cask/Caskroom` to your `HOMEBREW_CASK_OPTS`.

**Comment by tiennou** [comment]
Would it be acceptable to put that @jawshooah comment in the warning provided by cask ? As it stands "migration" doesn't make it clear that a simple `mv` can do the trick... Thanks !

**Comment by cwonrails** [comment]
Thanks to @jawshooah and @tiennou - I just resolved all issues using this method.

**Comment by jawshooah** [comment]
@tiennou The reason I didn't include the `mv` method in the warning printed by cask is that many users likely still have casks that were linked rather than moved prior to #13966, so just moving the Caskroom would leave a bunch of broken symlinks.

Unfortunately the only silver bullet that works regardless of where and how your casks were originally installed is to `brew cask install --force`.

**Comment by tiennou** [comment]
Oh ok, effectively if it's broken afterward 😉 . I just find the current warning not so helpful because it just says there's something wrong, without making it clear how to (cleanly) fix, and, as you point out, what are the shortcomings of each solution (e.g. `mv` breaks symlinks and `--caskroom` is "slated" for removal). Putting a link to some meta-issue (like this one) that describe what is the correct fix would be nicer, instead of scavenging for 10 minutes for additional context.

**Comment by jawshooah** [comment]
Fair enough. Mind submitting a PR with the suggested changes so we can discuss further? I've got my hands full at work at the moment.

**Comment by vitorgalvao** [comment]
@tiennou See https://github.com/caskroom/homebrew-cask/pull/21915. Please comment there (or feel free to submit a PR you find answers this better).

**Comment by krisleech** [comment]
You can do `ln -s /usr/local/Caskroom /opt/homebrew-cask/Caskroom` to restore any symlinks, such as those in `~/Applications`.
