### ISSUE TITLE
Parallel via brew not getting installed

### ISSUE THREAD

**Issue by arunsingh** [caskroom/homebrew-cask#22319]
Verifying checksum for Cask parallels-desktop
==> Moving App 'Parallels Desktop.app' to '/Applications/Parallels Desktop.app'
Warning: Unexpected method 'appdir' called during postflight on Cask parallels-desktop.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

Warning: Unexpected method 'appdir' called during postflight on Cask parallels-desktop.

  Most likely, this means you have an outdated version of homebrew-cask. Please run:

      brew uninstall --force brew-cask; brew untap phinze/cask; brew update; brew cleanup; brew cask cleanup

  If this doesn’t fix the problem, please report this bug:

      https://github.com/caskroom/homebrew-cask#reporting-bugs

Password:
sudo: /Parallels Desktop.app/Contents/MacOS/inittool: command not found
🍺  parallels-desktop staged at '/opt/homebrew-cask/Caskroom/parallels-desktop/11.2.0-32581' (32 files, 752K)

**Comment by vitorgalvao** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
