### ISSUE TITLE
How to install git. doctor and update didnt help

### ISSUE THREAD

**Issue by AndreyJu** [caskroom/homebrew-cask#22567]
MacBook-Admin:~ Admin$ brew install git
You must: brew install git
You must: brew install git
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
MacBook-Admin:~ Admin$ 
*********************************************************************************
MacBook-Admin:~ Admin$ brew install -vd git
You must: brew install git
You must: brew install git
/usr/local/bin/brew tap homebrew/core -q
You must: brew install git
You must: brew install git
Error: Git is unavailable
Error: Failure while executing: /usr/local/bin/brew tap homebrew/core -q
/usr/local/Library/Homebrew/utils.rb:334:in `safe_system'
/usr/local/Library/Homebrew/tap.rb:530:in `ensure_installed!'
/usr/local/Library/Homebrew/tap.rb:561:in `formula_dir'
/usr/local/Library/Homebrew/formulary.rb:331:in `core_path'
/usr/local/Library/Homebrew/formulary.rb:283:in `loader_for'
/usr/local/Library/Homebrew/formulary.rb:215:in `factory'
/usr/local/Library/Homebrew/formulary.rb:360:in `find_with_priority'
/usr/local/Library/Homebrew/extend/ARGV.rb:20:in `formulae'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
/usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
/usr/local/Library/Homebrew/cmd/install.rb:100:in `install'
/usr/local/Library/brew.rb:87:in `send'
/usr/local/Library/brew.rb:87
MacBook-Admin:~ Admin$

**Comment by vitorgalvao** [comment]
Wrong repo. You want [homebrew](https://github.com/Homebrew/brew/). Also, you specifically ignored the multiple warnings and instructions telling you how to report bugs. Had you read them, you likely would have noticed you’re in the wrong place.

I strongly suggest when you submit to your issue on the homebrew repo, you read their instructions and make your issue a bit more fleshed out. Explain instead of just spewing commands, and use [proper formatting](https://help.github.com/enterprise/11.10.340/user/articles/github-flavored-markdown/#fenced-code-blocks).

All these projects are made by volunteers. Please respect the maintainers’ time when asking for help.
