### ISSUE TITLE
OS X 10.12 - hdiutil[3566:110987] kCFURLVolumeIsAutomountedKey missing for file:///private/var/setup/: Error Domain=NSCocoaErrorDomain Code=260 "The file “setup” could

### ISSUE THREAD

**Issue by CiscoPress** [caskroom/homebrew-cask#22742]
```
$ brew cask install virtualbox --force
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
==> Downloading http://download.virtualbox.org/virtualbox/5.0.24/VirtualBox-5.0.24-108355-OSX.dmg
Already downloaded: /Users/john/Library/Caches/Homebrew/virtualbox-5.0.24-108355.dmg
==> Verifying checksum for Cask virtualbox
==> 2016-07-12 11:12:26.131 hdiutil[3566:110987] kCFURLVolumeIsAutomountedKey missing for file:///private/var/setup/: Error Domain=NSCocoaErrorDomain Code=260 "The file “setup” could
==> Running installer for virtualbox; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is Oracle VM VirtualBox
==> installer: Upgrading at base path /
==> installer: The upgrade was successful.
🍺  virtualbox staged at '/opt/homebrew-cask/Caskroom/virtualbox/5.0.24-108355' (4 files, 87M)

$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.

Warning: Your Xcode (7.3) is outdated
Please update to Xcode 8.0.
Xcode can be updated from
  https://developer.apple.com/xcode/downloads/


```

Virtualbox installation is working fine, but maybe you are interested in macOS Sierra error

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

When the the guide isn‘t followed we get the same issues over and over again. It may not seem to you like it makes a difference, but we already get a non-trivial amount of new issues and pull requests everyday. Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I closed this issue because it’s apparent to me the guide wasn’t followed. If I made a mistake in closing, I ask that you correct me. I will reopen it and we can continue the discussion.

If, however, you have indeed not paid the due attention to the guide, pleased go back and do. We will be waiting for your new properly formatted issue (or pull request) that will have most (if not all) the necessary details required for us to help you. With a little luck you won’t even need to open a new issue, as the instructions to report bugs include a lot of fixes for common problems.

Finally, if it was the guide itself that was unclear, make a new pull request with your suggestions on how to improve it.

Thank you.
