### ISSUE TITLE
Error: sha256 mismatch while run "brew cask install nodeclipse"

### ISSUE THREAD

**Issue by suniljav** [caskroom/homebrew-cask#22761]
Dear Team,

While running the "brew cask install nodeclipse" I am getting "Error: sha256 mismatch".

I also ran "brew update" and "brew cask cleanup" but still I am getting the same error "Error: sha256 mismatch"

Please help me to install node eclipse ide

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

When the the guide isn‘t followed we get the same issues over and over again. It may not seem to you like it makes a difference, but we already get a non-trivial amount of new issues and pull requests every day. Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I closed this issue because it’s apparent to me the guide wasn’t followed. If I made a mistake in closing, I ask that you correct me. I will reopen it and we can continue the discussion.

If, however, you have indeed not paid the due attention to the guide, pleased go back and do. We will be waiting for your new properly formatted issue (or pull request) that will have most (if not all) the necessary details required for us to help you. With a little luck you won’t even need to open a new issue, as the instructions to report bugs include a lot of fixes for common problems.

Finally, if it was the guide itself that was unclear, make a new pull request with your suggestions on how to improve it.

Thank you.
