### ISSUE TITLE
keeweb url broken for 1.2.1

### ISSUE THREAD

**Issue by staydecent** [caskroom/homebrew-cask#22828]
Attempting to install keeweb (after update/upgrade everything) fails: `brew cask install keeweb`

```
==> Downloading https://github.com/keeweb/keeweb/releases/download/v1.2.1/KeeWeb.mac.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'keeweb' with message: Download failed: Download failed: https://github.com/keeweb/keeweb/releases/download/v1.2.1/KeeWeb.mac.dmg
```

It appears as though the `1.2.1` release is not a verified release for keeweb and does not have any uploaded binaries associated with it: https://github.com/keeweb/keeweb/releases

Updating the version to `1.2.2.` would likely address this (apologies I don't know how to find the *sha* string to offer a pull request).

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

When the the guide isn‘t followed we get the same issues over and over again. It may not seem to you like it makes a difference, but we already get a non-trivial amount of new issues and pull requests every day. Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I closed this issue because it’s apparent to me the guide wasn’t followed. If I made a mistake in closing, I ask that you correct me. I will reopen it and we can continue the discussion.

If, however, you have indeed not paid the due attention to the guide, pleased go back and do. We will be waiting for your new properly formatted issue (or pull request) that will have most (if not all) the necessary details required for us to help you. With a little luck you won’t even need to open a new issue, as the instructions to report bugs include a lot of fixes for common problems.

Finally, if it was the guide itself that was unclear, make a new pull request with your suggestions on how to improve it.

Thank you.

**Comment by adidalal** [comment]
Contributing has details on how to submit a PR - we have a cli tool that makes version bumps very easy

**Comment by adidalal** [comment]
Specifically https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/sha256_mismatch_error_fix_outdated.md

**Comment by vitorgalvao** [comment]
As a small note, [I have already updated it](https://github.com/caskroom/homebrew-cask/commit/5c0fa0c8543db98dbaaadb921bf4929cf45d6a9b#diff-3a812b150d917a2951ef62fde1e20ca5), but those links are for future issues.
