### ISSUE TITLE
further refactor of ~/Library artifacts

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#2310]
I left this issue separate from #2300 b/c it involves user-visible changes.

Question: should we consolidate `--prefpanedir`, `--qlplugindir`, etc and present only `--appdir` and `--librarydir` in the UI?

(We could also simplify some code in `locations.rb`)

The current UI gives very fine-grained control, but that can be achieved another way.  If a user really wants to install prefpanes to `~/Library/PreferencePanes` but fonts to `/Library/Fonts`, he or she can issue two separate install commands with different values for `--librarydir`.

Other than "fine-grained control" I can't think of any advantages to having so many command-line options.

**Comment by vitorgalvao** [comment]
I have some opinions on why we shouldn’t (will be explained after the line, in case you want to read them), but the reason I believe strongly encapsulates why we shouldn’t, is it’d break `HOMEBREW_CASK_OPTS`. Right now you can “set it an forget it”, but with that consolidation, it’d become way less useful, and users would need to care about the options frequently.

---

We’d also need `--binarydir`, if consolidating the other options (but I think that wasn’t yet implemented when you opened this issue).

Aside from that, the options are there already, and unlike a GUI application, their existence doesn’t clutter the interface (there may be a bit more documentation to read, but that is far from the same). I’m also predicting some user confusion — `--fontdir` is way easier to understand than the concept of a single flag that should be used differently in different situations.

It can also lead to problems when you don’t know something is not an app. For example: you may have heard of [Secrets](http://secrets.blacktree.com/), but when deciding to install it with homebrew-cask, you’d not be at fault by thinking it was an app, instead of a prefpane.

**Comment by vitorgalvao** [comment]
As a further note, closing this also means removing this item from https://github.com/caskroom/homebrew-cask/issues/4678.
