### ISSUE TITLE
microsoft-lync URL invalid

### ISSUE THREAD

**Issue by LoganBarnett** [caskroom/homebrew-cask#23339]
Looks like the URL is out of date?

```
==> Downloading https://download.microsoft.com/download/5/0/0/500C7E1F-3235-47D4-BC11-95A71A1BA3ED/lync_14.3.3_160216.dmg

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'microsoft-lync' with message: Download failed: Download failed: https://download.microsoft.com/download/5/0/0/500C7E1F-3235-47D4-BC11-95A71A1BA3ED/lync_14.3.3_160216.dmg
The incomplete download is cached at /Users/logan/Library/Caches/Homebrew/microsoft-lync-14.3.3_160216.dmg
```

Similar to #14167

**Comment by LoganBarnett** [comment]
I was able to successfully download it manually from here:
https://download.microsoft.com/download/5/0/0/500C7E1F-3235-47D4-BC11-95A71A1BA3ED/lync_14.4.1_160608.dmg

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.
