### ISSUE TITLE
FileBot app name changed to include version number? 

### ISSUE THREAD

**Issue by wickles** [caskroom/homebrew-cask#23538]
Please see commit 6a5496946f146888252800b484da66bc67b75eb3 and my comment therein. 

Not sure if my comment will be otherwise noticed so posting here. Anyone have a good reason why it should be important to alter the app name by adding '-brew' and the version number? If there aren't any good reasons I'd like to change it back..

**Comment by jawshooah** [comment]
Did you follow the breadcrumbs from [the PR that introduced the change](https://github.com/caskroom/homebrew-cask/pull/23350)?

**Comment by wickles** [comment]
Good point, I wasn't thinking. So the conflict is just with the App Store app name FileBot.app right? Any reason to keep the version number or can we just name it FileBot-brew.app?

**Comment by jawshooah** [comment]
Paging @vitorgalvao and @rednoah.

**Comment by vitorgalvao** [comment]
> Any reason to keep the version number or can we just name it FileBot-brew.app or such?

No opposition from me, but that decision is completely @rednoah’s to make.

**Comment by rednoah** [comment]
The path `/Applications/FileBot.app` conflicts with the Mac App Store version, so we can't use that. Now that brew cask uses `/Applications` instead of `~/Applications` this has become a problem. `/Applications/FileBot-brew.app` is fine for me unless there's any objections from the brew cask team.

IMHO the original behaviour of copying app bundles into the caskroom and then linking to `~/Applications` worked very well for FileBot. Would people prefer the old behaviour for this particular cask? What does @victorpopkov think?

**Comment by vitorgalvao** [comment]
> IMHO the original behaviour of copying app bundles into the caskroom and then linking to `~/Applications` worked very well for FileBot. Would people prefer the old behaviour for this particular cask?

We’re definitly not doing that. Not only do the overwhelming majority of people prefer the new method, we’re not going to change that behaviour for a single cask.

Not only is the code not prepared for it anymore, it would be both confusing and nonsensical.

**Comment by jawshooah** [comment]
> Now that brew cask uses /Applications instead of ~/Applications this has become a problem.

How so? The small subset of users who want both the App Store version and the Homebrew-Cask version can just install with `--appdir=~/Applications`. Problem solved?

**Comment by rednoah** [comment]
Then I vote for doing `target: 'FileBot-brew.app'` that should make everyone reasonably happy.

**Comment by vitorgalvao** [comment]
> Then I vote for doing `target: 'FileBot-brew.app'`

We specifically say in our rules to **not** remove version numbers with `target:`, because if the developers put them there, they must have a reason. We even require *all* uses of `target:` to be annotated with specific standard comments. [You’ve been told that recently](https://github.com/caskroom/homebrew-cask/pull/23342#issuecomment-236764840).

[Why don’t you remove the version number from the app bundle](https://github.com/caskroom/homebrew-cask/issues/23538#issuecomment-238120075)?

> that should make everyone reasonably happy.

No, making the change simply because you asked for it without understanding why it can’t be done another way does not leave me happy at all.

We manage thousands of casks. We have rules for a reason: to make it manageable *at all*. It’s fine to make exceptions once in a while, but we avoid and document those because if we didn’t, they could be reverted by someone that wasn’t aware of the conversation or cause confusion (and hence more overhead for us).

If **you** want the version number out of the app installed in the users’ machine, why do **we** need to renamed it? It makes no sense, and we don’t usually make nonsensical changes.

**Comment by rednoah** [comment]
`FileBot-brew.app` or `FileBot_4.7.1-brew.app` either way is fine for me. I'm not the OP. So we keep `FileBot_4.7.1-brew.app` as per brew cask rules? Fine with me. Case closed. :D

**Comment by vitorgalvao** [comment]
> So we keep `FileBot_4.7.1-brew.app` as per brew cask rules?

Or the app bundle is renamed upstream to `FileBot-brew.app`. Would still like to know why you keep the version number in the name (genuine question).

Would also resolve your concern of older versions being kept if the users does not remove them (yes, we need to work on that as well, but it would be fixed now).

Either way, we can close this. If it is renamed upstream, we’ll get a PR.

Thank you all.

**Comment by rednoah** [comment]
The archive is called `FileBot_4.7.2-brew` so I thought it would make sense to content would be `FileBot_4.7.2-brew` as well. I'll look into that for next release.

**Comment by wickles** [comment]
I understand the basic reasoning, but I don't see why there can't be some exceptions to removing the `#{version}` from the app bundle in a clear case of it being an artifact from an automated build process. In this case you have access to the developer and can hope to simply have it fixed upstream, but naturally you can't always rely on that. 

But @vitorgalvao you (and I assume other maintainers) have clearly put a lot of thought into those rules, so I don't mean to start an argument. If it's not going to change I'll leave it alone. :+1:

**Comment by rednoah** [comment]
I'll force the `tarfileset` paths to `FileBot.app` again with the next major release, and leave it to users to either use `--force` or `--appdir=~/Applications` if they encounter conflicts.

**Comment by wickles** [comment]
Maybe beating a dead horse here but I suggest `FileBot-brew.app`.

**Comment by rednoah** [comment]
Let's just leave it the way it is for now.
