### ISSUE TITLE
Unable to uninstall java cask

### ISSUE THREAD

**Issue by utkonos** [caskroom/homebrew-cask#23703]
I am unable to uninstall the java cask even with --force. Here is the error output:

```
$ brew cask uninstall --force java
==> Running uninstall process for java; your password may be necessary
==> Removing launchctl service com.oracle.java.Helper-Tool
==> Removing launchctl service com.oracle.java.Java-Updater
==> Quitting application ID com.oracle.java.Java-Updater
==> 2016-08-11 12:18:09.250 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, 
==> 2016-08-11 12:18:09.251 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, 
==> 2016-08-11 12:18:09.251 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, 
==> 2016-08-11 12:18:09.252 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, 
==> 36:109: execution error: System Events got an error: Application isn’t running. (-600)
Error: Command failed to execute!

==> Failed command:
["/usr/bin/sudo", "-E", "--", "/usr/bin/osascript", "-e", "tell application \\\"System Events\\\" to count processes whose bundle identifier is \\\"com.oracle.java.Java-Updater\\\""]

==> Standard Output of failed command:


==> Standard Error of failed command:
2016-08-11 12:18:09.250 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-08-11 12:18:09.251 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-08-11 12:18:09.251 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
2016-08-11 12:18:09.252 osascript[19555:710539] CFPasteboardRef CFPasteboardCreate(CFAllocatorRef, CFStringRef) : failed to create global data
36:109: execution error: System Events got an error: Application isn’t running. (-600)


==> Exit status of failed command:
#<Process::Status: pid 19554 exit 1>
```

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.
