### ISSUE TITLE
Add `reinstall` command

### ISSUE THREAD

**Issue by caleb531** [caskroom/homebrew-cask#23998]
### Description of feature/enhancement

First, I want to note that I searched through the issues on this repository and couldn't find an existing issue for this. In short, I'd love to see a `brew cask reinstall` command that works like `brew reinstall`.

### Justification

1. A `brew cask reinstall` command would make HBC more consistent with brew, as brew already offers its own `reinstall` command. 
2. As far as I can tell, `brew cask install --force` already functions as an effective cask reinstall, so perhaps the only change needed is to add `brew cask reinstall` as an alias to `brew cask install --force` (which I think is a worthy change, because `reinstall` is easier to type/autocomplete).
3. Because this addition should map to existing behavior, it should not be dependent on major migrations like #13201 (which looks great, BTW).

### Example use case

My request was actually inspired by the move in #13201, since the format of the caskroom had changed substantially (though I also wanted to eliminate those awkward app symlinks in my `/Applications` directory). I used `brew cask install --force` to reinstall all of my casks (so the symlinks would be replaced with `.app` bundles), but I think calling a `brew cask reinstall` command would've made that feel much more intuitive.

Thoughts?
Caleb

**Comment by reitermarkus** [comment]
It's not quite that simple, as `reinstall` should basically behave the same as `upgrade`, but instead of installing a newer version, it should install the currently installed version again.

**Comment by adidalal** [comment]
Actually, brew reinstall always installs the latest version

**Comment by reitermarkus** [comment]
@adidalal, thanks for pointing that out, I didn't know that, since I rarely `reinstall` anything. So actually the difference between `reinstall` and `upgrade` is that `reinstall` does the same as `upgrade`, but without keeping the old version.

 I would expect `reinstall` to install the currently installed version in order not to break anything.

**Comment by vitorgalvao** [comment]
> So actually the difference between `reinstall` and `upgrade` is that `reinstall` does the same as `upgrade`, but without keeping the old version.

Since with #13201 we eliminate the idea of keeping old versions around and always keep just the latest, it would make both commands nearly the same. I say “nearly” because there’s another important difference: `upgrade` will do nothing if there is no new version or if the cask `auto_updates true`, while `reinstall` would always reinstall.

I’m fine with making `brew cask reinstall {{cask}}` an alias to `brew cask uninstall {{cask}} && brew update && brew cask install {{cask}}`.

**Comment by Git-Jiro** [comment]
Hi! I am going to try to implement this!

**Comment by Git-Jiro** [comment]
Hi! I think this can be closed now, correct?

**Comment by vitorgalvao** [comment]
Correct

**Comment by Saklad5** [comment]
Shouldn’t this command respect options like appdir?

**Comment by jawshooah** [comment]
@Saklad5 that would require creating some kind of install receipt on disk, as Homebrew does, which we haven't gotten to yet. Definitely a good use case though.
