### ISSUE TITLE
Frequent and rapid update on single cask

### ISSUE THREAD

**Issue by anantshri** [caskroom/homebrew-cask#23993]
folks, 

So yet another merge successful (https://github.com/caskroom/homebrew-cask/pull/23988), this was my 6th edit of the same file (https://github.com/caskroom/homebrew-cask/commits?author=anantshri) coz of frequent update that chrome / chromium follows.  This time i waited for nearly a week or so before going ahead and changing that specific cask.

All i have been doing is a version bump and 2 checksum bump. Can't we automated that part, as the appcast url is also present and if that has latest version i would ideally expect brew to pick that up for me.

Just opening the question here asking for a simpler process.

**Comment by jawshooah** [comment]
> The appcast url is also present and if that has latest version i would ideally expect brew to pick that up for me

All appcasts are not created equal, and there is no guarantee that any given appcast follows a particular format. This makes it very difficult to automate updates as you suggest without delving into myriad special cases and overcomplicating the core code for very little gain.

Appcasts are there to notify us that a cask *may* have been updated, so that a maintainer or contributor can manually investigate and open a PR if need be. In fact, we even have scripts available to help maintainers and contributors [identify Casks with outdated appcasts](https://github.com/caskroom/homebrew-cask/blob/15171687a14436e6bde53c3a1111c8602f30e9ae/developer/bin/find_outdated_appcasts) and [update them individually](https://github.com/caskroom/homebrew-cask/blob/15171687a14436e6bde53c3a1111c8602f30e9ae/developer/bin/fix_outdated_appcasts).
