### ISSUE TITLE
Cannot run gpg

### ISSUE THREAD

**Issue by chrisfinazzo** [caskroom/homebrew-cask#24072]
I am seeing this issue when trying to commit an  update for a Cask. I have checked that the remotes (origin, chrisfinazzo) exist, but there seems to be another problem with my configuration.
<img width="697" alt="screen shot 2016-08-26 at 12 06 24 pm" src="https://cloud.githubusercontent.com/assets/1534882/18013965/b940614a-6b8e-11e6-985f-b0320325343c.png">
<img width="697" alt="screen shot 2016-08-26 at 11 37 53 am" src="https://cloud.githubusercontent.com/assets/1534882/18013968/bd4e3f1e-6b8e-11e6-894c-4a97a035b0ff.png">

**Comment by adidalal** [comment]
Please *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. To do so, edit the top post and then comment after this one so I can check back.

Closing in the meantime, because a number of people never report back and it’s useless to keep the issue open in that case and without all the required information.
