### ISSUE TITLE
Cask broke! 'Unknown command cask'

### ISSUE THREAD

**Issue by JikkuJose** [caskroom/homebrew-cask#24331]
I did something silly with the homebrew repo that I am unable to revert & cask broke! I tried to reinstall but nothing worked so far. Here is what I did, any ideas?

``` bash
[~/Downloads] $ brew install caskroom/cask/brew-cask
==> Tapping caskroom/cask
Cloning into '/usr/local/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3405, done.
remote: Compressing objects: 100% (3387/3387), done.
remote: Total 3405 (delta 36), reused 446 (delta 12), pack-reused 0
Receiving objects: 100% (3405/3405), 1.15 MiB | 209.00 KiB/s, done.
Resolving deltas: 100% (36/36), done.
Checking connectivity... done.
Tapped 0 formulae (3,412 files, 3.5M)
==> brew cask install caskroom/cask/brew-cask
Error: Unknown command: cask
[~/Downloads] $ brew cask
Error: Unknown command: cask
[~/Downloads] $
```

System: Mac OSX 10.11.6

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by JikkuJose** [comment]
Sorry, I somehow assumed the text was for contributing to the repo alone. Thats why I deleted & posted this.
