### ISSUE TITLE
Feature request: (Bring back) cask info missing information about latest version installed

### ISSUE THREAD

**Issue by atais** [caskroom/homebrew-cask#24412]
### Description of feature/enhancement
So for a while now I have been using `brew cask` and before last update it was possible for me to find in `brew cask info $cask` if I had the latest cask version installed.
Now this information is gone.

### Justification
I wrote a small script to update all the casks:
https://gist.github.com/atais/9c72e469b1cbec35c7c430ce03de2a6b
while this option is still not available.

It was possible to determine which version should be updated or not. Now there is still a way, but I am not sure why the option got deleted.

### Example use case

Example `cask info` now:

```
iterm2: 3.0.8
https://www.iterm2.com/
/usr/local/Caskroom/iterm2/3.0.5 (68B)
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/iterm2.rb
==> Name
iTerm2
==> Artifacts
iTerm.app (app)
iterm2 is up-to-date.
```

**Comment by adidalal** [comment]
Will let another maintainer comment on the changed behavior.

But see also https://github.com/buo/homebrew-cask-upgrade

**Comment by reitermarkus** [comment]
The reason for this change was because `list` and `info` were broken before in that they didn't recognise old versions that were installed. 

The new, and expected, behaviour is to list all installed versions. Having info on the state of a cask (up-to-date/outdated) will not be added until `upgrade` is implemented.

**Comment by vitorgalvao** [comment]
Closing as answered.
