### ISSUE TITLE
Improve command for getting `checkpoint:`

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#24454]
Pointed out in https://github.com/caskroom/homebrew-cask/pull/24450#issuecomment-246776984, there’s a situation where the command to calculate `checkpoint:` may not work.

Solution might be to remove all newlines from appcasts, making the final command (added `tr -d '\n'`):

```
curl --compressed --location --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' "{{appcast_url}}" | tr -d '\n' | /usr/bin/sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256
```

That means:

+ Updating the documentation.
+ Updating `audit`.
+ Updating the test.
+ Updating `cask-repair`.
+ Updating all casks, since the result will be different for most.

Making this issue first to see if there are any objections or better solutions.

**Comment by reitermarkus** [comment]
How about instead of complicating this even further, we implement this as an internal command, which doesn't have the limitations `sed` has? This way we also don't have to always sync this command and the `audit` code. Copy-pasting `curl --compressed --location --user-agent 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' "{{appcast_url}}" | /usr/bin/sed 's|<pubDate>[^<]*</pubDate>||g' | shasum --algorithm 256` is a pain anyways.

**Comment by vitorgalvao** [comment]
@reitermarkus could you be more specific? How do you envision this working as an internal command? Do you mean an internal command to calculate it?

**Comment by reitermarkus** [comment]
Yes, an internal command which uses the same logic that `audit` uses. Something like `_appcast_checkpoint`?

**Comment by vitorgalvao** [comment]
I’m absolutely fine with that. It would simply output the value, correct?

**Comment by vitorgalvao** [comment]
Closing in favour of https://github.com/caskroom/homebrew-cask/issues/24811. We should consider this ready to be implemented. There seems to be no objections to your suggestion.
