### ISSUE TITLE
quickbooks package is busted

### ISSUE THREAD

**Issue by fxfactorial** [caskroom/homebrew-cask#24523]
```
brew cask install quickbooks
Warning: The default Caskroom location has moved to /usr/local/Caskroom.

Please migrate your Casks to the new location and delete /opt/homebrew-cask/Caskroom,
or if you would like to keep your Caskroom at /opt/homebrew-cask/Caskroom, add the
following to your HOMEBREW_CASK_OPTS:

  --caskroom=/opt/homebrew-cask/Caskroom

For more details on each of those options, see https://github.com/caskroom/homebrew-cask/issues/21913.
==> Downloading https://http-download.intuit.com/http.intuit/CMO/apple_web/sample/static/qbomac/releases/QuickBooks

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'quickbooks' with message: Download failed: https://http-download.intuit.com/http.intuit/CMO/apple_web/sample/static/qbomac/releases/QuickBooks_2.4.6/QuickBooks.QBOWeb.dmg
The incomplete download is cached at /Users/Edgar/Library/Caches/Homebrew/Cask/quickbooks--2.4.6.dmg.incomplete
```

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by fxfactorial** [comment]
What is the specific problem here? The package is busted, was this a duplicate?

**Comment by vitorgalvao** [comment]
[`curl` error](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/a_cask_fails_to_install.md#curl-error).

`-1` my response all you like, that does not change the fact you did not follow the instructions we were adamant you follow. If you had followed them, you’d saved time and saw the problem is not with us, but the download itself upstream is currently down.

You need to contact upstream, we can’t solve the issue.

**Comment by fxfactorial** [comment]
@vitorgalvao `brew cask` is the package manager, at least have it say that its not my fault. Since when does good software just throw its hands up and say its not my fault.

I know how to read curl errors as well, why not take down the package at least in the mean time.

**Comment by vitorgalvao** [comment]
> at least have it say something more informative. 

More informative how? It can’t know the cause of why `curl` is failing. Also, we’re pre-alpha software, any improvements to messages (and everything else) are welcome.

> I know how to read curl errors as well

I am not questioning your ability to interpret the error, just asking you follow the guide that was given, especially since we ask so much for it to be followed.

> why not take down the package at least in the mean time.

Because it’s likely a momentarily issue. It’s more productive to just ask upstream what the issue is. Removing it will just lead to people asking why it was removed and probably forgetting to add it back — it’s not worth the hassle.
