### ISSUE TITLE
Quick Look Plugins installed in wrong directory?

### ISSUE THREAD

**Issue by lukasoppermann** [caskroom/homebrew-cask#24918]
Hey,

so I tried installing https://github.com/sindresorhus/quick-look-plugins/issues/57#event-803204259 on OSX 10.11.6, it says it worked, if I try reinstalling it, it says it is already installed, however the files are not within `/Library/QuickLook` and so it does not actually work.

However copying files manually into the folder works. But I would much rather install via casks, as it would allow for automatic updates.

Am I doing something wrong, or is this an issue with cask?

**Comment by vitorgalvao** [comment]
That repo is a list of plugins. Which one did you try to install?

Also, please follow the [bug report template](https://github.com/caskroom/homebrew-cask#reporting-bugs). We ask for specific information to be given so we can help you and say your issue might be close if you don’t give it.

We don’t even know if your version of HBC is up to date. Please read the instructions and try again.

**Comment by vitorgalvao** [comment]
Also, you’re looking into `/Library/QuickLook` but we install under `~/Library/QuickLook`. We inform you of that at installation time. That is the correct directory for user installs.

**Comment by lukasoppermann** [comment]
hey @vitorgalvao sorry.

I had the problem with all of the plugins in the list. I am on `Homebrew 1.0.4`. How can I find my cask version?

You where right about `~/Library/QuickLook`, the files are there. However they are not picked up. 😢 

Do you have any idea what I could try or how I can provide info. I am at a loss what other info you need, I looked at the template but it did not really help, sorry.

**Comment by vitorgalvao** [comment]
This seems to be some kind of issue in your setup. We’ve always installed to `~/Library/QuickLook` and it has always worked.

I just tried uninstalling and installing a few plugins, and it worked as expected (uninstalling makes them stop working, installing makes them continue to work).

Try moving them in and out of the directory manually (don’t forget to `qlmanage -r`). If it continues to not work, it’s confirmed the issue is not with HBC.

**Comment by lukasoppermann** [comment]
Hey @vitorgalvao, so the problem is actually with the `symlink` moving the "real" `.qlgenerator` files into the folder works. But if I remove them and move the `symlinks` created by homebrew cask back in, it stops working. Do you have any idea what this could be?

**Comment by vitorgalvao** [comment]
We stopped symlinking a good while ago. If your HBC is still symlinking, [follow this](https://github.com/caskroom/homebrew-cask/blob/master/doc/reporting_bugs/pre_bug_report.md).

After updating, uninstall all those casks and install them again and it’ll start moving the plugins instead of symlinking them.

**Comment by lukasoppermann** [comment]
Awesome, thanks. That worked.
