### ISSUE TITLE
Problem installing Veracrypt in Sierra

### ISSUE THREAD

**Issue by drawcard** [caskroom/homebrew-cask#24983]
Hi, I'm having some trouble trying to install Veracrypt (on macOS Sierra) - I think it might be a permissions problem with /usr/local which is apparently read only in Sierra.

Output below.
```
$ brew cask install veracrypt
==> Caveats
veracrypt requires osxfuse with "MacFUSE Compatibility Layer" enabled.
If you did not enable that option, veracrypt will fail to install.

To enable the option, you need to install osxfuse manually (double-click the installer).
The installer should be located under /usr/local/Caskroom/osxfuse

==> Satisfying dependencies
==> Installing Cask dependencies: osxfuse
osxfuse ...
already installed
complete
==> Downloading https://download-codeplex.sec.s-msft.com/Download/Release?Projec
Already downloaded: /Users/drawcard/Library/Caches/Homebrew/Cask/veracrypt--1.18a
==> Verifying checksum for Cask veracrypt
==> Running installer for veracrypt; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
Password:
==> installer: Error -  
Error:   Command failed to execute!

  ==> Failed command:
  ["/usr/bin/sudo", "-E", "--", "/usr/sbin/installer", "-pkg", "#<Pathname:/usr/local/Caskroom/veracrypt/1.18a/VeraCrypt_Installer.pkg>", "-target", "/"]

  ==> Standard Output of failed command:
  

  ==> Standard Error of failed command:
  installer: Error -  


  ==> Exit status of failed command:
  #<Process::Status: pid 59917 exit 1>
```

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

Also, try installing the app manually (i.e. without homebrew cask) to see if it fails.

**Comment by drawcard** [comment]
Ok, I got the message :) I have resubmitted a bug report: https://github.com/caskroom/homebrew-cask/issues/25040
