### ISSUE TITLE
Install wechat-web-devtools error

### ISSUE THREAD

**Issue by causlayer** [caskroom/homebrew-cask#25387]
brew cask install wechat-web-devtools
==> Downloading http://dldir1.qq.com/WechatWebDev/mina/20160923/wechat_web_devtools_0.9.092300.dmg
Already downloaded: /Users/apple/Library/Caches/Homebrew/Cask/wechat-web-devtools--0.9.092300,20160923.dmg
==> Verifying checksum for Cask wechat-web-devtools
Error: It seems the App source is not there: '/usr/local/Caskroom/wechat-web-devtools/0.9.092300,20160923/微信web开发者工具.app'

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.
