### ISSUE TITLE
Version :Latest Usage

### ISSUE THREAD

**Issue by Saklad5** [caskroom/homebrew-cask#25483]
Why is it preferable to use the "latest" placeholder when there is no versioned download available? Casks seem to work and update (using the cask-repair script) fine if you put the version in when the download isn’t versioned.

Forgoing the version and checksum is very inconvenient for users, and it will be even worse once “brew cask upgrade” is finally implemented. Does the current guideline really make sense?

**Comment by reitermarkus** [comment]
> Why is it preferable to use the "latest" placeholder when there is no versioned download available? 

Casks will break simply because the unversioned download, and hence of course the checksum, changes, and the version will be wrong.

**Comment by Saklad5** [comment]
OK. The appcast checksum changes as well, and that isn’t a problem.

**Comment by vitorgalvao** [comment]
> OK. The appcast checksum changes as well, and that isn’t a problem.

Because that’s used internally. It’s for us, the user never interacts with it, it is not checked at download, and does not break the cask.

**Comment by Saklad5** [comment]
Are there any plans to improve this behavior in the future? It will be very important when “brew cask upgrade” comes around.

**Comment by vitorgalvao** [comment]
> Are there any plans to improve this behavior in the future? It will be very important when “brew cask upgrade” comes around.

There’s nothing we can do about it. This isn’t a behaviour that needs improving, it is a limitation imposed on us externally. To mitigate this, you can either find more `appcasts` and add them to casks (those we convert to versioned casks because we can automate finding new versions) or you ask upstream developers to always provide versioned downloads.

I’ll add that at the time `:latest` was implemented, there was no `cask-repair`, and we didn’t have so many contributing users (according to some user reports, the easiness and convenience of `cask-repair` actually drives those users to contribute when they wouldn’t have otherwise), so perhaps if we eliminated `:latest` we would be fine. But those are a bigger pain to update as well because you can’t simply check a public value (url, appcast) to know the new version, you have to actually download the app and check it manually, and that is inconvenient to the point it would likely only be done after the cask broke. Having casks constantly break and rushing to fix them is a poor experience.

Once more, two ways to mitigate this: find more appcasts, ask developers for versioned urls.
