### ISSUE TITLE
sha256 mismatch error for CrashPlan install on Sierra

### ISSUE THREAD

**Issue by lendenmc** [caskroom/homebrew-cask#26158]
I'm trying to install CrashPlan on macOS Sierra with
```
brew cask install crashplan
```
Here is the output:
```
==> Downloading https://download.crashplan.com/installs/mac/install/CrashPlan/CrashPlan_4.8.0_Mac.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask crashplan
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: fd0189c9ab40e77d5b3aee653ac052002754133fe4f361e0b7c088dae44ca271
Actual: 43ae48b8ae5c19312cdc4be561774f3e2fde64a483534f8de61a68403b16335f
File: /Users/.../Library/Caches/Homebrew/Cask/crashplan--4.8.0.dmg
To retry an incomplete download, remove the file above.
```
I removed the file above, try `brew update`, `brew cleanup -s`, `brew cask cleanup` and so on, but I'm still getting the same error.
FYI running `brew doctor`on my machine doesn't spot any issue.

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-cask/pull/26160

**Comment by lendenmc** [comment]
You're right about that, sorry.
