### ISSUE TITLE
uninstall corrupted

### ISSUE THREAD

**Issue by suncoma** [caskroom/homebrew-cask#26335]
suncoma@zxs ~$ brew cask install eclipse-jee
Warning: A Cask for eclipse-jee is already installed.

To re-install eclipse-jee, run:
  brew cask uninstall --force eclipse-jee && brew cask install eclipse-jee
suncoma@zxs ~$ 
suncoma@zxs ~$ 
suncoma@zxs ~$ 
suncoma@zxs ~$ 
suncoma@zxs ~$ brew cask uninstall --force eclipse-jee
==> Downloading /usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161102083946.059/Casks/eclipse-jee.rb
curl: (3) <url> malformed
Error: No available Cask for /usr/local/Caskroom/eclipse-jee/.metadata/4.6.1,neon:1a/20161102083946.059/Casks/eclipse-jee.rb

**Comment by vitorgalvao** [comment]
You must *always* follow the [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) guide. When you opened this issue, the template in place urged you to do so and gave you the relevant links.

The template also stated clearly that

> if it is apparent you ignored the instructions for reporting issues, your issue may be closed without review.

That seems very much to be the case, here, which is why this was closed.

Again, as the template states (emphasis added)

> When the guide isn‘t followed we get the same issues over and over. **Having to repeatedly deal with the same solved and documented problems leads to maintainer burnout and a lot of wasted hours** that could instead have been spent improving Homebrew-Cask itself and fixing real bugs.

I’ll add it is **exhausting**, and when maintainers are exhausted, everyone loses.

A lot of work was put into those guides precisely so we can keep things running smoothly. When users ignore the guides to save a few minutes individually, maintainers lose hours and become fatigued.

I ask that you respect our time and efforts and follow the guides.

**Comment by suncoma** [comment]
if your soft is not usable I will wipe it out without reporting guides - and will suggest others to do the same - you mess up my operating system.

**Comment by vitorgalvao** [comment]
> if your soft is not usable I will wipe it out without reporting guides

As you wish. If you cannot take the time to correctly make a bug report, we cannot take the time to help you properly.

> and will suggest others to do the same

Threats do not help your case. We’re not here to serve you personally.

> you mess up my operating system

No, we did not, you’re being extremely exaggerated and don’t even understand the error message. The only thing the cask did was download a `dmg` and move an `app` bundle. That does not mess up operating systems.

**Comment by suncoma** [comment]
thank you for support !!! no help needed - I am wondering how you design it. cheers.
