### ISSUE TITLE
Add GoAgentX

### ISSUE THREAD

**Issue by xuzj365** [caskroom/homebrew-cask#26602]
Hope can increase the application of GoAgentX！

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for (…) [making requests](https://github.com/caskroom/homebrew-cask#requests)

> (…)

> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.
