### ISSUE TITLE
Eclipse IDE removal/reinstallation fails

### ISSUE THREAD

**Issue by yami-no-ryuu** [caskroom/homebrew-cask#27169]
For some reason it tries to redownload a formula using complex version number doing no good

```
brew cask reinstall eclipse-cpp
==> Downloading /opt/homebrew-cask/Caskroom/eclipse-cpp/.metadata/4.6.1,neon:1a/20161126201326.804/Casks/eclipse-cpp.rb
curl: (3) <url> malformed
Error: No available Cask for /opt/homebrew-cask/Caskroom/eclipse-cpp/.metadata/4.6.1,neon:1a/20161126201326.804/Casks/eclipse-cpp.rb. Did you mean:
eclipse-cpp
Error: nothing to install
```

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.
