### ISSUE TITLE
Could we change the cask update deprecation message to use a more ordered date?

### ISSUE THREAD

**Issue by Numbermaniac** [caskroom/homebrew-cask#28568]
I don't know whether 2017-07-01 is referring to 1 July or 7 January to be honest; I think it'd be better if the deprecation notice used a date format like "7 January 2017" so no ambiguity in the format.

**Comment by miccal** [comment]
If you think this is an odd request, note that @Numbermaniac and myself (and @fanquake I believe) are in Australia, and we read `07-01` as `the 7th of January`, where many around the world would read `07-01` as `the 1st of July`.

**Comment by vitorgalvao** [comment]
> has America infected the world with this much uncertainty around dates?

Yes, they have.

> Shame on them.

Shaming them does not accomplish anything, though.

> ISO 8601 universality (…) and it follows convention used around most of the world

No one in this issue is disputing the merits of ISO 8601 or arguing it shouldn’t be universal. However, none of that helps. Seeing `2017-01-07` and *wishing* it’s ISO 8601 does nothing.

Just over half of the maintainers of this project are non-American. Yet, by convention we still default to the American-english version of software when there is an alternative, because it makes sense to do so. There’s no reason to assume right out the bat that we use ISO 8601.

I do agree with your *sentiment*, just not with your *argument*. Yes, it would be great if we could all use the same agreed upon system. Unfortunately, computer system are made by humans ([obligatory XKCD](https://xkcd.com/927/)).

In sum, here’s the main flaw in your argument: **this message is to be read by humans, not machines**. Ambiguity matters not because the code breaks, but because users are confused.

**Comment by reitermarkus** [comment]
In the future, let's just use the 15<sup>th</sup> of the month. 😂
