### ISSUE TITLE
Error: sha256 mismatch: Kicad

### ISSUE THREAD

**Issue by ahiairrassary** [caskroom/homebrew-cask#28629]
[`kicad`](https://github.com/caskroom/homebrew-cask/commits/master/Casks/kicad.rb)

There is a sha256 mismatch error, as you can see below:

```
brew cask install kicad
==> Downloading http://downloads.kicad-pcb.org/osx/stable/kicad-4.0.5.dmg
######################################################################## 100.0%
==> Verifying checksum for Cask kicad
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: b9747534aa29074eeb383dd4b506cf76e977f5b222dd08022d856a48d6137049
Actual: 4e15567c655176bd8d187d8d9c3e9413e7777e84bd5cef057f04b5895a5e786b
File: /Users/XXX/Library/Caches/Homebrew/Cask/kicad--4.0.5.dmg
To retry an incomplete download, remove the file above.
```

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by ahiairrassary** [comment]
Thx !

Sorry I did not see this sentence: It’ll likely need a new version, **but it’s possible the version has remained the same** in your issue template... My bad
