### ISSUE TITLE
make cask standalone

### ISSUE THREAD

**Issue by acornejo** [caskroom/homebrew-cask#2879]
I've been using cask and it am really pleased with it.

It seems to me that there is little dependence between brew and cask. Is there a reason why cask depends on brew (i.e. we cant use cask without first installing brew)?

Currently I've been using `alias cask="brew cask"` to do all my cask related operations, but it would be a lot better if cask was just a separate package manager (and it just so happens that you can install cask through brew).

Personally I've been using both cask and brew formulas, so its not that I mind having brew installed, it just seems a weird dependency. (seems a bit like having to do `brew vim file` every time I want to use vim to edit a file.)

**Comment by phinze** [comment]
@rolandwalker if I understand correctly, are we pretty close to being independent nowadays?

I'd like to figure out what's left tying us down - I think it might be nice to "graduate" to just being Cask.

**Comment by rolandwalker** [comment]
As a verb, yes, we now can stand alone.  You should be able to run `/usr/local/bin/brew-cask`, and I think that someone could alias it to `cask`.

But, we are still entirely integrated with the Homebrew ecosystem, because (still true, as above) we don't handle pulling down new Casks.

At a project level, Homebrew has made interop stronger – they are starting to automatically find and install Casks for command starting with `brew`, and to install Casks for brew dependencies (as we install Formulae as Cask dependencies.)

So we have two sorta-opposite trends running, which seems like it makes no sense.  Yet both trends so far have brought benefits.

Another thing to consider is that Homebrew has a new way to propagate subcommands.  If we move our command to the `cmd` directory (and impose a little discipline on core development), users could receive core ugrades via simple `brew update`, and we could throw away the recommended update command:
```bash
$ brew update && brew upgrade brew-cask && brew cleanup && brew cask cleanup
```

**Comment by phinze** [comment]
Thanks for the status update! I don't foresee us ever going that far away from homebrew; my primary concern is about branding clarity. I also think it would be nice for `cask` to work on its own, but that's less important to me.

Here's a probably-confusing food metaphor, 'cause I'm sorta hungry:

> homebrew and cask will always go together like peanut butter and jelly, but right now "jelly" is mostly known as "that fruity peanut butter sweetener". but jelly has a lot going for it on its own - maybe you could even use jelly in a non-PB&J-sandwich context! but at least we can start thinking of jelly as jelly, yakno?

Let me know if that made any sense and I'll go get a snack. ;)

**Comment by rolandwalker** [comment]
Oh, branding!  Our branding is a muddle at best.  Clarity would be welcome.

If we started calling ourselves "Cask", some things would definitely become more clear, others less so (*cf* #8575).  Homebrew was smart to call the project by one name, and the recipes by another.

In favor of the project name "Cask": many people already use it.
