### ISSUE TITLE
Can we make HB flags not interfere with `cask`?

### ISSUE THREAD

**Issue by vitorgalvao** [caskroom/homebrew-cask#28977]
I’m building an [external command](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/hacking.md#external-commands) for cask. However, I’m running into a snag caused by Homebrew (related: https://github.com/caskroom/homebrew-cask/issues/16265). Basically, short flag options become not viable.

Steps to reproduce:

```
# Make a simple temporary executable script
echo '#!/bin/bash
[[ "${1}" == "--flag" ]] && echo "long flag given"
[[ "${1}" == "-a" ]] && echo "short flag given"
[[ -z "${1}" ]] && echo "no flag given"' > /tmp/brewcask-example
chmod +x /tmp/brewcask-example

# Add its directory to your PATH
PATH=/tmp:$PATH

# Run it as an external command, with and without the flags
brew cask example
brew cask example --flag
brew cask example -a

# You’ll get (in order)
no flag given # correct
long flag given # correct
Error: There is more than one possible option that starts with '-a' # incorrect
```

That last option is being “stolen” by Homebrew itself. Try something like `brew cask example --help` and you’ll get their help, not even ours.

HB flags shouldn’t interfere with HBC commands. That `--help` example would be particularly confusing to a user.

Pinging @reitermarkus @claui @jawshooah @mwean.

**Comment by MikeMcQuaid** [comment]
> Try something like brew cask example --help and you’ll get their help, not even ours.

If you use `#: ` before your comments at the top of a file they will be output by `brew --help`.

**Comment by vitorgalvao** [comment]
> If you use `#: ` before your comments at the top of a file they will be output by `brew --help`.

It only works for `brew` external commands, not `brew cask` ones.

And this looks like a bug, but I just tried `brew services --help` and my terminal is filled with the (correct) instructions. I then cannot leave/do anything until I <kbd>ctrl</kbd><kbd>C</kbd>.

**Comment by MikeMcQuaid** [comment]
> It only works for brew external commands, not brew cask ones.

It could be made to work on `brew cask` external commands fairly easily.

> And this looks like a bug, but I just tried brew services --help and my terminal is filled with the (correct) instructions. I then cannot leave/do anything until I ctrlC.

I cannot reproduce this. It could be related to pager (e.g. `less`) settings.

**Comment by vitorgalvao** [comment]
> I cannot reproduce this. It could be related to pager (e.g. `less`) settings.

I have no custom settings for `less`. I can reproduce in both `zsh` inside `iTerm2` (my setup) and `bash` inside `Terminal` (pristine and unchanged, that I keep for tests such as this).

In both terminals the title bar (where the current running command is shown) goes crazy, switching between `bash` and `ruby`, suggesting there‘s an infinite loop. When you `brew services --help`, does it fit all at once on your Terminal? In mine it does not (not tall enough).

**Comment by MikeMcQuaid** [comment]
@vitorgalvao No idea then, sorry.

**Comment by amyspark** [comment]
@mikemcquaid, I can confirm and reproduce the two bugs described by @vitorgalvao.

The first one:
> That last option is being “stolen” by Homebrew itself. Try something like brew cask example --help and you’ll get their help, not even ours.

It's a bug in Cask's `cli.rb`:
https://github.com/Homebrew/brew/blob/56458f03fcc68ef6d8ee3ee4a7c1d16021aa5800/Library/Homebrew/cask/lib/hbc/cli.rb#L227-L235
Line 234 specifies that it should print the first argument if available, which the example script does (instead of `example`, which doesn't exist as a command!)

The second one:
> And this looks like a bug, but I just tried brew services --help and my terminal is filled with the (correct) instructions. I then cannot leave/do anything until I <kbd>ctrl</kbd><kbd>C</kbd>.

This one only happens *if homebrew/services has not been previously tapped*, because in this case the help request is redirected to the `tap` command, which *always returns the help text without actually tapping the cask* 🤦‍♀️ .
The execution flow is roughly like this:

`brew services --help`
 - `help.rb` [does not find the command](https://github.com/Homebrew/brew/blob/021729e1646212d47d3f52c0b29034e7da97693b/Library/Homebrew/cmd/help.rb#L69) and so returns
 - now `brew.rb` tests [whether it belongs to a Tap](https://github.com/Homebrew/brew/blob/b488a89b5d2bd9c96e3128f598221fed1c3c1911/Library/Homebrew/brew.rb#L103-L107)
 - it does, so `brew tap homebrew/services` [is triggered](https://github.com/Homebrew/brew/blob/b488a89b5d2bd9c96e3128f598221fed1c3c1911/Library/Homebrew/brew.rb#L113-L115)
 -  ***because the `HOMEBREW_HELP` environment variable is still set, `help.rb` sets the `help_flag`, [and attempts to print `tap` help instead](https://github.com/Homebrew/brew/blob/021729e1646212d47d3f52c0b29034e7da97693b/Library/Homebrew/cmd/help.rb#L72-L73)***
 -  now, `puts(command_help(path))` does the job, but after doing so `exit 0` returns _from the "tap"_
 - [we execute `brew services --help` again](https://github.com/Homebrew/brew/blob/b488a89b5d2bd9c96e3128f598221fed1c3c1911/Library/Homebrew/brew.rb#L115), and since the tap didn't clone the repo but merely printed the help text, this triggers the loop.

The bug lies in the remarked step: if a tap is required, it should *not* obey the `HOMEBREW_HELP` environment variable.

A pull request in Homebrew is forthcoming.
