### ISSUE TITLE
Thunderbird Uninstall/Reinstall Deletes Default Profile

### ISSUE THREAD

**Issue by blogabe** [caskroom/homebrew-cask#29946]
I don't see how the changes in https://github.com/caskroom/homebrew-cask/pull/29937 would cause this, but I uninstalled Thunderbird then re-installed this morning to get on the new version.  After the install, I noticed Thunderbird was using a brand new default configuration.  I had to use Time Machine to pull my config from the day before.  This has never happened before upon uninstall/reinstall of TB.  Anyone else experience this?

**Comment by vitorgalvao** [comment]
Unless you uninstalled with `zap`, it’s unlikely the culprit was HBC.

**Comment by blogabe** [comment]
@vitorgalvao Always quick to close issues I notice.

I uninstalled using `brew cask uninstall --force thunderbird`

I believe that is the same as using `zap` and I'm sure you'll let me know one way or another.

HOWEVER, this is always how I have upgraded Thunderbird but this is the first time my default profile was outright deleted.  And not on one machine, but others as well.

I'm not saying it HBC... or the script.  Just curious why this particular update deleted the profile and if anyone else has experienced this.

If it's the new norm with the TB updates, then I'd like to be better prepared before upgrading in the future.

**Comment by vitorgalvao** [comment]
> @vitorgalvao Always quick to close issues I notice.

I am when they’re unlikely to be related to us, yes. There’s no point in keeping them open, and I frankly don’t comprehend the others projects who just leave unrelated and old issues open indefinitely. They become untenable, maintainers burnout, and the projects are abandoned.

HBC was already close to such a state, being proficient in closing issues as they’re no longer relevant makes sure a project doesn’t stagnate. We’re not tech support. If it isn’t related to us, there’s no obligation to spend resources fixing. That’s even detrimental, I’d say.

Closing does not mean the conversation is over. I can just as easy reopen the issue

> I uninstalled using `brew cask uninstall --force thunderbird`
>
> I believe that is the same as using `zap` and I'm sure you'll let me know one way or another.

No, it is not the same.

> HOWEVER, this is always how I have upgraded Thunderbird but this is the first time my default profile was outright deleted. And not on one machine, but others as well.
>
> I'm not saying it HBC... or the script. Just curious why this particular update deleted the profile

Since the *only* thing we do is remove the app, that’s a question for the thunderbird team, not us.

> and if anyone else has experienced this.

They haven’t. We have no other reports of this.

> If it's the new norm with the TB updates, then I'd like to be better prepared before upgrading in the future.

And again, that’s a question for them, not us. We have no control over how they manage their software.
