### ISSUE TITLE
Feature request: No trials

### ISSUE THREAD

**Issue by mindbs** [caskroom/homebrew-cask#30028]
### Description of feature/enhancement

Remove trials or rename the formulas so it's clear they state so.

### Justification

Since there's consistently no transparency whether some software is available "free" but as trial (not even in the vendor website) it's annoying to just type it in the command, be happy that a cask exists for it, and then be bugged with a "your trial expires.." window.
Want to be a package manager or a half-package manager?

### Example use case

brew cask install some-software--trial

**Comment by vitorgalvao** [comment]
> Want to be a package manager or a half-package manager?

Hurling insults won’t get you much sympathy, I’d gather.

Also, we’ve been making clear for years [we’re not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md) and have [clear rules regarding trials](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#trial-and-freemium-versions).

I ask that next time first you ask or try to understand our rules instead of — as a user who has never before contributed or was engaged in discussion with the project — imposing your views on how it should be managed. Especially when referring to something most users have no problems with.
