### ISSUE TITLE
Bug report: paragon-extfs 

### ISSUE THREAD

**Issue by Manouchehri** [caskroom/homebrew-cask#30385]
```bash
Davids-MacBook-Pro:Downloads dave$ brew cask install paragon-extfs
==> Downloading http://dl.paragon-software.com/demo/extmac10_trial.dmg
######################################################################## 100.0%
==> No checksum defined for Cask paragon-extfs, skipping verification
==> Running installer for paragon-extfs; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are i
Error: pkg source file not found: '/usr/local/Caskroom/paragon-extfs/latest/FSInstaller.app/Contents/Resources/Paragon ExtFS for Mac OS X.pkg'
Error: nothing to install
```

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by Manouchehri** [comment]
It's literally two lines of error messages. Didn't think I could simplify it much more.

Anyway, thanks for opening the new ticket.

**Comment by vitorgalvao** [comment]
> It's literally two lines of error messages.

That you could’ve fixed yourself if you followed the guide, since it teaches you how to.
