### ISSUE TITLE
Bug report: [phd2 The requested URL returned error: 403 Forbidden]

### ISSUE THREAD

**Issue by rbarcellona** [caskroom/homebrew-cask#31020]
brew install  Caskroom/cask/phd2
==> brew cask install Caskroom/cask/phd2
==> Downloading http://openphdguiding.org/PHD2-v2.4.1-OSX.zip

curl: (22) The requested URL returned error: 403 Forbidden
Error: Download failed on Cask 'phd2' with message: Download failed: http://openphdguiding.org/PHD2-v2.4.1-OSX.zip
The incomplete download is cached at /Users/darkfire/Library/Caches/Homebrew/Cask/phd2--2.4.1.zip.incomplete
Error: nothing to install

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.
