### ISSUE TITLE
Bug Report: 'brew cask install mqttfx' fails, the App source is not there

### ISSUE THREAD

**Issue by jaguarondi** [caskroom/homebrew-cask#31682]
The install of mqttfx fails with the following message: ```Error: It seems the App source '/usr/local/Caskroom/mqttfx/1.3.1/MQTT.fx.app' is not there.```

It seems the formula is looking for 'MQTT.fx.app' while the file in the package is 'MQTT.fx Installer.app', see below. I don't know how to fix this though.

Here's the log:
```
$ brew update
Updated Homebrew from 676c4a9 to 1ba4010.
No changes to formulae.
$ brew cask install mqttfx
==> Downloading http://www.jensd.de/apps/mqttfx/1.3.1/mqttfx-1.3.1-macos.dmg
Already downloaded: /Users/david/Library/Caches/Homebrew/Cask/mqttfx--1.3.1.dmg
==> Verifying checksum for Cask mqttfx
Error: It seems the App source '/usr/local/Caskroom/mqttfx/1.3.1/MQTT.fx.app' is not there.
Error: nothing to install

$ brew cask cat mqttfx
cask 'mqttfx' do
  version '1.3.1'
  sha256 'c9d4d1c862e5aab194338f3508f166d20a9116c9ba2be70e1e4341bad6c96070'

  # jensd.de/apps/mqttfx was verified as official when first introduced to the cask
  url "http://www.jensd.de/apps/mqttfx/#{version}/mqttfx-#{version}-macos.dmg"
  name 'MQTT.fx'
  homepage 'http://mqttfx.jfx4ee.org/'

  app 'MQTT.fx.app'
end

$ ls /Volumes/mqttfx/
MQTT.fx Installer.app
```

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.
