### ISSUE TITLE
Bug report: Problem uninstalling adobe-air cask

### ISSUE THREAD

**Issue by blogabe** [caskroom/homebrew-cask#31707]
Seems to be a problem with the adobe-air uninstaller.  If I try to uninstall manually, I receive a `too many arguments` message.  Also tried uninstalling manually using `sudo ./Adobe\ AIR\ Installer -uninstall`.  While that didn't give me a too many arguments message, it still failed in uninstall.

```
$ brew cask uninstall --force adobe-air
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/25.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall

==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 34754 exit 7>
$ brew cask install --force adobe-air
==> Downloading https://airdownload.adobe.com/air/mac/download/25.0/AdobeAIR.dmg
######################################################################## 100.0%
==> No checksum defined for Cask adobe-air, skipping verification
==> Running installer script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
Password:
==> Version 25.0.0.134 is current; no actions to take
==> done
🍺  adobe-air was successfully installed!
$ brew cask uninstall --force adobe-air
==> Running uninstall process for adobe-air; your password may be necessary
==> Running uninstall script Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer
==> Uninstalling Adobe AIR (all versions)
==> failed (consult log)
Error: Command failed to execute!

==> Failed command:
#<Pathname:/usr/local/Caskroom/adobe-air/25.0/Adobe AIR Installer.app/Contents/MacOS/Adobe AIR Installer> -uninstall

==> Standard Output of failed command:
Uninstalling Adobe AIR (all versions)
failed (consult log)


==> Standard Error of failed command:


==> Exit status of failed command:
#<Process::Status: pid 34881 exit 7>
```

**Comment by vitorgalvao** [comment]
From the [issue template](https://github.com/caskroom/homebrew-cask/blob/master/.github/ISSUE_TEMPLATE.md) that shows when opening a new issue:

> Before opening your issue **you must check our instructions** for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (…) [it] has several links to help diagnose and fix common issues.
> (…)
> **if it is apparent you ignored the instructions for reporting issues, we may close the issue without review**.

That seems to be the case, which is why I closed this issue. We worked hard  on those guides to keep things running smoothly, so I ask that you go back and follow them. It is OK to open a new issue for that.

If I was wrong in closing this issue, please do reply stating why! Closing an issue does not mean the conversation is over.

I understand sometimes we’re tired and don’t want to sift through a guide to make what we feel is a simple bug report. But when each user ignores the guides to save a few minutes, maintainers lose hours and get fatigued. I ask you take that into consideration.

Thank you for understanding.

**Comment by blogabe** [comment]
Um, you just asked me to create this issue?!?!?!  I did follow the guide.  The issue isn't listed there.

**Comment by vitorgalvao** [comment]
We need the other information in the template, such as `brew cask doctor`, and the others.
