### ISSUE TITLE
Feature request: `unverified` caveat

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#34584]
Discussion started in https://github.com/caskroom/homebrew-cask/pull/34374#issuecomment-302877634

### Description of feature/enhancement

For casks that cannot be verified, add a `unverified` [`caveat`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl/caveats.rb).
```ruby
def unverified(discussion_url)
  puts <<-EOS.undent
    #{@cask}'s sha256 was updated WITHOUT verification.

    As with any app, use at your own risk.

      #{Formatter.url("#{discussion_url}")}

  EOS
end
```
```ruby
  caveats do
    unverified 'https://github.com/caskroom/homebrew-cask/pull/34063'
  end
```
```
brew cask info mnemosyne
mnemosyne: 2.4.1
http://mnemosyne-proj.org/
Not installed
From: https://github.com/caskroom/homebrew-cask/blob/master/Casks/mnemosyne.rb
==> Name
Mnemosyne
==> Artifacts
Mnemosyne.app (app)
==> Caveats
mnemosyne's sha256 was updated WITHOUT verification.

As with any app, use at your own risk.

https://github.com/caskroom/homebrew-cask/pull/34063

```

### Justification

Allows for cases where the the checksum has changed and the developer cannot be contacted.

**Comment by vitorgalvao** [comment]
I’d like a bit more clarification on the `caveat` itself, like linking to the relevant documentation and mentioning that we tried to get verification but the developer did not reply to our request it. Also that we waited a reasonable amount of time (say, a week) between said request and the merging.

It just occurred to be that even better would be if casks with this `caveat` could be made to fail when `--require-sha` is set.

Pinging @caskroom/maintainers.

**Comment by commitay** [comment]
Does `#{discussion_url}`  need to be a complete URL or can something like this work?
```
#{Formatter.url("https://github.com/caskroom/#{tap}/pull/#{number}")}
```

**Comment by vitorgalvao** [comment]
@commitay I see no issue with using the latter.

**Comment by commitay** [comment]
```
#{Formatter.url("https://github.com/caskroom/#{tap}/pull/#{number}")}
```

Can't get this to work. There are several different ways `"tap"` is referred to: `(repo_info)`, `{remote_tap.default_remote}`, `{tap}`, etc. Not sure which one I should be using.

**Comment by vitorgalvao** [comment]
We can live as is. Your suggestion on the top post looks fine (I’ve made a few tweaks).

**Comment by commitay** [comment]
@vitorgalvao Should I start PRs for [caveats.rb](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cask/lib/hbc/dsl/caveats.rb) and [caveats.md#caveats-mini-dsl](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/caveats.md#caveats-mini-dsl)?

**Comment by vitorgalvao** [comment]
@commitay Yes, please.

But I’d still like to know if [this](https://github.com/caskroom/homebrew-cask/issues/34584#issuecomment-302926226) is (easily) feasible, @reitermarkus:

> even better would be if casks with this `caveat` could be made to fail when `--require-sha` is set.

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/34812

https://github.com/Homebrew/brew/pull/2674

**Comment by commitay** [comment]
> mentioning that we tried to get verification but the developer did not reply to our request it. Also that we waited a reasonable amount of time (say, a week) between said request and the merging.

Forgot about this. Where should it be added to?

**Comment by vitorgalvao** [comment]
@commitay To the `caveat`, perhaps (no strong feelings).

**Comment by miccal** [comment]
To quote @MikeMcQuaid:

> I also agree that we should not be shipping changes unverified. If we can consistently not verify a package and there's not another security mechanism we can rely on (code or GPG signing) it should be removed from Homebrew Cask. A couple of lines of text are not sufficient notice to the user that it may be malware and they are not enough for us to not be partly responsible if we ship malware to users as a result.

I tend to agree, and I do not believe this is a `caveat` we should use.

**Comment by commitay** [comment]
I'm not against deleting casks, only suggested the `caveat` as a CYA alternative to deleting and (possibly) re adding casks. 

@vitorgalvao Should I close the PRs?

**Comment by miccal** [comment]
@commitay I am not really sure why to do in this case to be honest - deleting and re-adding Casks is not a viable option I don't think, but if the developer(s) do not respond I do not know of a decent alternative.

**Comment by MikeMcQuaid** [comment]
> deleting and re-adding Casks is not a viable option I don't think, but if the developer(s) do not respond I do not know of a decent alternative.

I agree that if you cannot offer a secure way of distributing their software you should not do so.

**Comment by vitorgalvao** [comment]
> if you cannot offer a secure way of distributing their software you should not do so.

While I agree in principle, at some point the logic breaks down. Where do we define the turning point? Casks with a `sha256 :no_check` are no more secure than a cask with a changed `sha256`. If an attacker compromises a server, it’s game over on those two accounts, and even easier on `:no_check`. A checksum is great for seeing if the download is correct, not so much for guaranteeing legitimacy.

And if an attacker compromises a server, they could introduce their malware and then change the HTML on the page to fake a version bump, which we also have no way to verify unless we ask every developer about every version bump. That is undoubtedly a losing battle, and there’s no way HBC could continue to exist. This is an easier task with open-source than with closed source, and much of the value of HBC is its support for closed-source.

We also have a specific [policy for casks that bundle malware](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/apps_with_malware.md) because it was deemed worth to have one.

Simply, in the past we’ve come to the conclusion that policing is a losing battle. What seems to work, though, is *granularity  of options*. That is why `--require-sha` exists, meaning “don’t install if it has `:no_check`”, and why we also want to extend options to “don’t install if it’s not `https`”. I’m even in favour of at some point reversing this, and making users use the flags when they want to risk the insecurity.

This is the same case. If, [as mentioned](https://github.com/caskroom/homebrew-cask/issues/34584#issuecomment-302926226), this `caveat` can work in tandem with `--require-sha`, it is a perfectly valid `caveat` to exist. Because if it’s not, then neither are any `:no_check` casks.

---

On another note, removal of the offending casks does not make much sense. At some point the app will get a version bump, and everything will be fine. This means a constant removal and readding of casks that will muddy our issue history. We’ll no longer be able to distinguish an “oh right, this cask was removed in the past due to that legitimate issue, so it should stay removed” from “it was just removed because the `sha256` changed”.

**Comment by vitorgalvao** [comment]
In addition, note [I do have a plan](https://github.com/caskroom/homebrew-cask/pull/34740#issuecomment-303419323) for a system that amongst other things could make `:no_check` obsolete.

But the rest of the point still stands.

**Comment by vitorgalvao** [comment]
@MikeMcQuaid’s also note I’ve grabbed on your quote for my reply, but I mean nothing by it. The sentiment in the issue was agreement with it, and I used it as a basis because it perfectly encapsulates the point in a few words.

You have a true skill for it, and I even have some bookmarks of points you made ([most recently from twitter](https://twitter.com/MikeMcQuaid/status/864846443584139264)) because they’re so short and clear, they make great arguments to explain a point.

**Comment by MikeMcQuaid** [comment]
> While I agree in principle, at some point the logic breaks down. Where do we define the turning point? Casks with a sha256 :no_check are no more secure than a cask with a changed sha256. If an attacker compromises a server, it’s game over on those two accounts, and even easier on :no_check. A checksum is great for seeing if the download is correct, not so much for guaranteeing legitimacy.

Personally, I don't feel `:no_check` is a responsible way to distribute software without some form of additional checks (e.g. verifying it has been digitally signed after extraction). I don't run Homebrew Cask though so obviously I defer to you there.

> And if an attacker compromises a server, they could introduce their malware and then change the HTML on the page to fake a version bump, which we also have no way to verify unless we ask every developer about every version bump.

With security in general the issue isn't so much known attacks as attacks you didn't know had happened. In a case like this, the original author would notice and respond much quicker. Additionally, it increases the effort required for an attack. Without being too mean here, I'd also argue that's the slippery slope fallacy; I don't see anyone here advocating for that change.

> In addition, note I do have a plan for a system that amongst other things could make :no_check obsolete.

https://github.com/homebrew/homebrew-livecheck may be of interest to you. It would be interesting to see if we can share any resources here.

> We also have a specific policy for casks that bundle malware because it was deemed worth to have one.

Again, it's up to you but I do think intentionally distributing malware puts the onus on less technical users to know how to secure their system. It's not about being a gatekeeper as much as protecting people with sensible defaults.

> making users use the flags when they want to risk the insecurity.

This seems like a good idea. Then again, be aware that blog posts/stackoverflow will tell people to just set these options and they will do so blindly.

> On another note, removal of the offending casks does not make much sense. At some point the app will get a version bump, and everything will be fine.

I'm fine with not removing them as long as they fail to install when the checksum doesn't match and it doesn't just get bumped without upstream confirmation.

> @MikeMcQuaid’s also note I’ve grabbed on your quote for my reply, but I mean nothing by it. The sentiment in the issue was agreement with it, and I used it as a basis because it perfectly encapsulates the point in a few words.

No worries, there's no personal hard feelings here either way between us (and thanks for the kind words ❤️). We can disagree amicably on this stuff.
