### ISSUE TITLE
QtCreator with QWT plugins integrated

### ISSUE THREAD

**Issue by hector** [caskroom/homebrew-cask#3653]
It would be nice that if you have qwt installed via homebrew and you install Qt-Creator with Cask it automatically loads the widgets for the designer.

In theory symlinking like this should work:

    cd /opt/homebrew-cask/Caskroom/qt-creator/3.0.1/Qt Creator.app/Contents/PlugIns/designer
    ln -s /usr/local/Cellar/qwt/6.1.0/plugins/designer/libqwt_designer_plugin.dylib

Even though this worked for the Designer.app that comes with hombrew's Qt it did not work for cask's Qt-Creator. It could because the Qt-Creator you are providing is not compiled with homebrew's version of Qt.

Some links with info:
http://doc.qt.digia.com/qtcreator-2.4/adding-plugins.html#configuring-qt-designer-plugins-on-mac-os
https://github.com/Homebrew/homebrew/issues/27692

**Comment by vitorgalvao** [comment]
This would require interoperability with `homebrew`, which we since separated from, or at least making some sort of manual check to see if the formula is installed and where.

This is over a year old and seems to have not gathered further interest. Are *you* still interested in this? Do you think you could accomplish everything robustly with a [`postflight`](https://github.com/caskroom/homebrew-cask/blob/master/doc/CASK_LANGUAGE_REFERENCE.md#postflight-stanza-details)?

**Comment by hector** [comment]
I guess I can just do it manually. And I'm sorry but I don't know about 'postflight'.

**Comment by vitorgalvao** [comment]
The documentation to `postflight` was linked. It's a way to run arbitrary commands after a cask has been installed.
