### ISSUE TITLE
SUPPORT File

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#37103]
>You can create a SUPPORT file to let people know about ways to get help with your project.

> To direct people to specific support resources, you can add a SUPPORT file to your repository's root, docs, or .github folder. Then, whenever someone creates an issue in your repository, they will see a link to your project's SUPPORT file.

https://help.github.com/articles/adding-support-resources-to-your-project/

**Comment by vitorgalvao** [comment]
This seems to be basically the same as CONTRIBUTING.md (which most people already ignore, anyway). What info do you envision we would stick there?

**Comment by vitorgalvao** [comment]
But we already link to reporting-bugs from the issue template.

Seems to me SUPPORT is just CONTRIBUTING (which we have) with a different name. Even the message at the top of an issue is the same. And thing is, no one notices that message; it looks like a banner you can ignore without consequences.

The only thing I ever saw actually work are the issue and PR templates, because they’re there in your face so they are hard to ignore. And if a user ignores it or even deletes it (both happen), that’s an easy justified close without review.

I’m open to having SUPPORT if more maintainers see it useful, but I don’t see the point myself.

**Comment by commitay** [comment]
> it looks like a banner you can ignore without consequences.

Good point, it won't actually do any good.

I'll leave this open for a couple of days if other maintainers want to comment.
