### ISSUE TITLE
lego-digital-designer doesn't get properly zapped

### ISSUE THREAD

**Issue by adius** [caskroom/homebrew-cask#38268]
When I run `brew cask zap lego-digital-designer` the `/Users/adrian/Library/Application Support/LEGO Company` directory doesn't get deleted. It should be, right?

**Comment by vitorgalvao** [comment]
> It should be, right?

No, because that cask does not have a [`zap` stanza](https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), hence *nothing* gets zapped.

For things to be deleted, the stanza needs to be added to the cask. PRs are welcome.

I won’t leave the issue open since this is true of a ton of casks. `zap`s are added as they are contributed.
