### ISSUE TITLE
Pull requests that only update the appcast `checkpoint` 

### ISSUE THREAD

**Issue by commitay** [caskroom/homebrew-cask#38376]
I realise contributors may be submitting PRs for `checkpoint` updates as part of scripts they have to automate the update process but I don't see any value in a PR that only updates the `checkpoint`.

With Travis CI wait times getting longer I also think it is a bad use of CI time to be running builds that only update the `checkpoint`.

/cc @vitorgalvao

**Comment by vitorgalvao** [comment]
Agreed, but when we once again have our own scripts for it, they’ll do the same.

Do you have a suggestion for this? Ignoring those cases won’t work too well since then they’ll just fire every time until there’s a real update.

In truth I do have a better idea, for a tool that’d make appcasts obsolete: an outside tool tailored for every cask individually. But that’s a huge undertaking, and since I’m currently not earning any revenue, I can’t yet justify the time commitment as of now.

**Comment by commitay** [comment]
Apologies, my post is missing a sentence. 

I would like to close `checkpoint` only PRs and cancel their CI builds.

There are only a few contributors who submit `checkpoint` PRs so I'm hoping that if we close the PRs with an explanation as to why it will eventually catch on. 

> In truth I do have a better idea, for a tool that’d make appcasts obsolete: an outside tool tailored for every cask individually.

Very interested in hearing more about your ideas for this.

I think [homebrew-livecheck](https://github.com/Homebrew/homebrew-livecheck) performs a similar function for finding outdated formula that can be tailored individually, would it be worthwhile trying to adapt it?

**Comment by reitermarkus** [comment]
So what will happen to those Casks we ignore? We have to check them even more, since we now eliminated the knowledge that “this appcast is up-to-date, even though there is no new version”. The endgame here is essentially that all Casks are up-to-date when all appcasts are up-to-date.

> an outside tool

I‘d rather have an “inside” tool. 😉 But I don‘t know how it would work, so maybe it can only be an outside tool.

**Comment by vitorgalvao** [comment]
> So what will happen to those Casks we ignore? We have to check them even more, since we now eliminated the knowledge that “this appcast is up-to-date, even though there is no new version”. 

Precisely.

> I‘d rather have an “inside” tool. 😉

What I mean by that is something that would work outside of HBC’s core functionality. So something users are never supposed to see.

> I think homebrew-livecheck performs a similar function for finding outdated formula that can be tailored individually, would it be worthwhile trying to adapt it?

That is a command that is user-facing, it seems. To expand a bit more on the idea:

1. We get rid of `appcast`s.
2. A sister project has definitions for every app and accurately detects when they have updates, the version number and url.
3. Said project runs automatically and feeds its results to `cask-repair` (or whatever), so updates to casks are not only discovered automatically but *submitted* automatically.

This can be done since *every single app* will have a tailored definition for its specific case.

**Comment by claui** [comment]
> A sister project has definitions for every app

By _definitions,_ do we mean the per-app URLs, the checkpoint states, or both?

**Comment by vitorgalvao** [comment]
> By definitions, do we mean the per-app URLs, the checkpoint states, or both?

Everything we deem necessary. Picture the sister project as something that can exist separate from HBC<sup>1</sup> that simply shows you a list of every app with their respective latest version numbers and download URL. If those are extracted from appcasts, HTML pages, or even HTTP requests, it’d depend on the app.

---

<sup>1.</sup> Though in practice the result would be tailored for us.

**Comment by commitay** [comment]
Apologies for the wall of text.

> So what will happen to those Casks we ignore? We have to check them even more, since we now eliminated the knowledge that “this appcast is up-to-date, even though there is no new version”. The endgame here is essentially that all Casks are up-to-date when all appcasts are up-to-date.

A lot of appcasts are always outdated and trying to keep them updated is a losing battle. An example of this are the `brave` and `vimr` Casks that publish a "beta" / "snapshot" release every couple of days but only have a stable release every week or two.

Appcasts also seem to change if upstream edits release notes, retags without making changes to the macOS release or makes changes to their website. The most stable appcasts seem to be sparkle  and single line plain text files as they only change if an update is published.
___

> We get rid of `appcast`.

> A sister project has definitions for every app and accurately detects when they have updates, the version number, and url.

No objection to getting rid of `checkpoint` (or making it external to the Cask) but I'd favour keeping the "appcast" (whatever the source of the update information is) unified with the Cask. I think keeping this in the Cask makes it more "complete" and having PRs for new Casks include the update source would be simpler.

Being able to access this information via HBC is also very helpful.

I have this in my dotfiles that I use when checking for updates and reviewing PRs.
```
appcast() {
	open $(brew cask _stanza appcast "$@" | sed -e 's|releases.atom|releases|')
}
```
___

> What I mean by that is something that would work outside of HBC’s core functionality.

> Picture the sister project as something that can exist separate from HBC

Absolutely agree with the tool being an external / sister project as I think that would allow much greater flexibility for changes and quicker updates rather than being integrated into the Homebrew "core". 

I mentioned `homebrew-livecheck` as it's an tappable external command and it seems to be similar to want we would want (read a URL and match a definition).

```
class Unrar
  livecheck :url => "http://www.rarlab.com/rar_add.htm",
            :regex => %r{href="http://www.rarlab.com/rar/unrarsrc-([0-9,\.]+).tar}
end
```

Adapting `livecheck` (or forking it) may more effort than it's worth but the basic concept seemed worth mentioning as a jumping-off point.

**Comment by vitorgalvao** [comment]
> A lot of appcasts are always outdated and trying to keep them updated is a losing battle. An example of this are the `brave` and `vimr` Casks that publish a "beta" / "snapshot" release every couple of days but only have a stable release every week or two.

Ideally we’d have a bot that’d check for new PRs, and if those changed *only* `checkpoint`, it’d auto-merge them (not even necessary for Travis to pass).

> No objection to getting rid of `checkpoint` (or making it external to the Cask) but I'd favour keeping the "appcast"(…)

Agreed with your points.

> I have this in my dotfiles that I use when checking for updates and reviewing PRs.

Regarding the “checking for updates” part, I’m not sure if you know but `cask-repair` already does that. If you tell it to open the appcast and it’s a Github releases atom feed, it open the webpage instead of the feed.

> Adapting `livecheck` to work with Cask (or forking it) may more effort than it's worth but the basic concept seemed worth mentioning as a jumping-off point.

Agreed again.

> found this which also seems to do what we want

Pinging @victorpopkov.

**Comment by commitay** [comment]
> I’m not sure if you know but `cask-repair` already does that

```
  -o, --open-home                        Open the homepage for the given cask.
  -a, --open-appcast                     Open the appcast for the given cask.
```

I didn't know about `appcast` or `homepage`, thanks for mentioning that! 😃

**Comment by commitay** [comment]
Closing this as the issue has served its purpose.
___
I'd like to continue discussing the update tool but should it be an issue in this repo or somewhere else?
