### ISSUE TITLE
Failed to install andoird-sdk

### ISSUE THREAD

**Issue by thynson** [caskroom/homebrew-cask#39213]
#### General troubleshooting steps

- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue
Install `android-sdk` failed on macOS High Serria with case-sensitive APFS filesystem.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#reinstall
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT=/usr/local/share/android-sdk'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/lanxingcan/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Downloaded to -> /Users/lanxingcan/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/lanxingcan/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/lanxingcan/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/lanxingcan/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.1.zip", "/var/folders/zy/h78_msp15cb_k8c9t25hqp780000gn/T/d20171002-24649-r0fpb1"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20171002110549.455.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.1/20171002110549.455/Casks.
==> Installing artifacts
==> Determining which artifacts are present in Cask android-sdk
==> 47 artifact/s defined
preflight (Preflight Block)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aapt (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aapt2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aarch64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/aidl (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/arm-linux-androideabi-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/bcc_compat (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/dexdump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/dx (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/i686-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/llvm-rs-cc (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/mainDexClasses (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/mipsel-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/split-select (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/x86_64-linux-android-ld (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/build-tools/26.0.1/zipalign (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/e2fsck (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/fsck.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/mkfs.ext4 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/resize2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/bin64/tune2fs (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator-check (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-arm (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-crash-service (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-mips (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/emulator64-x86 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/emulator/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/adb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/dmtracedump (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/etc1tool (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/fastboot (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/hprof-conv (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/platform-tools/systrace/systrace.py (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/android (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/archquery (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/avdmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/jobb (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/lint (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/monkeyrunner (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/screenshot2 (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/uiautomatorviewer (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/mksdcard (Binary)
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/monitor (Binary)
postflight (Postflight Block)
uninstall_postflight (Postflight Block)
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.1"]
==> Exception in thread "main" 
==> java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
==> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
==> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
==> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
==> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
==> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
==> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
==> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
==> 	... 5 more
==> Purging files for version 3859397,26.0.1 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397,26.0.1/tools/bin/sdkmanager tools platform-tools build-tools;26.0.1

==> Standard Output of failed command:


==> Standard Error of failed command:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more


==> Exit status of failed command:
#<Process::Status: pid 24775 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:65:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:68:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:44:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:28:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:121:in `reinstall'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:10:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/reinstall.rb:5:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```

#### Output of `brew cask doctor`

```
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.

```

**Comment by commitay** [comment]
Please post `brew cask doctor` not `brew doctor`

**Comment by thynson** [comment]
```
==> Homebrew-Cask Version
Homebrew-Cask 1.3.4-53-ge7cf509
caskroom/homebrew-cask (git revision 5b883; last commit 2017-10-02)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (20 files, 2.9GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3754 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1117 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="zh_CN.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
Could you post `brew config` too please?

**Comment by miccal** [comment]
@commitay it is very likely that this is causing the issue:
```
Warning: The filesystem on / appears to be case-sensitive.
The default macOS filesystem is case-insensitive. Please report any apparent problems.
```

**Comment by thynson** [comment]
Sorry for my late.
Output of `brew config`:
```
ORIGIN: https://github.com/Homebrew/brew
HEAD: e7cf509cfb5891ad32eebf8d2ec58bd936af6694
Last commit: 3 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 797a92759237dfd613247ef3e1356370a4059eb0
Core tap last commit: 25 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.3.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 9.0 build 900
Git: 2.13.5 => /Library/Developer/CommandLineTools/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: 9
macOS: 10.13-x86_64
Xcode: N/A
CLT: 9.0.0.0.1.1504363082
X11: N/A
```
I used brew cask to install android-sdk on mac Serria. It works fine on case-sentitive HFS+ file system. After upgrading the system, it doesn't work now.

**Comment by commitay** [comment]
I get the same error with Java 9, please retry with Java 8.

**Comment by thynson** [comment]
Indeed.  Successfully reinstalled with java8 from caskroom/version. Might be a bug of Android team.

**Comment by TheInternet** [comment]
I'm still having this problem, but wanted to confirm I correctly reinstalled with java8.  Let me know if I should open this as a new issue:

Installing Java 8:
`Thomass-MacBook:~ thomasdonahoe$ brew cask install caskroom/versions/java8
==> Caveats
This Cask makes minor modifications to the JRE to prevent issues with
packaged applications, as discussed here:

  https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

If your Java application still asks for JRE installation, you might need
to reboot or logout/login.

Installing this Cask means you have AGREED to the Oracle Binary Code
License Agreement for Java SE at

  https://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Satisfying dependencies
==> Downloading http://download.oracle.com/otn-pub/java/jdk/8u152-b16/aa0333dd3019491ca4f6ddbe78cdb6d0/jdk-8u152-macosx-x64.dmg
Already downloaded: /Users/thomasdonahoe/Library/Caches/Homebrew/Cask/java8--1.8.0_152-b16,aa0333dd3019491ca4f6ddbe78cdb6d0.dmg
==> Verifying checksum for Cask java8
==> Installing Cask java8
==> Running installer for java8; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
==> installer: Package name is JDK 8 Update 152
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  java8 was successfully installed!`

Double checking it is version 8 installed:
`Thomass-MacBook:~ thomasdonahoe$ /Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)`

Trying to install android sdk again:
`Thomass-MacBook:~ thomasdonahoe$ brew cask install android-sdk --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
android-sdk requires Java 8. You can install it with

  brew cask install caskroom/versions/java8

We will install android-sdk-tools, platform-tools, and build-tools for you.
You can control android sdk packages via the sdkmanager command.
You may want to add to your profile:
  'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"'

This operation may take up to 10 minutes depending on your internet connection.
Please, be patient.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://dl.google.com/android/repository/sdk-tools-darwin-3859397.zip
Already downloaded: /Users/thomasdonahoe/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Downloaded to -> /Users/thomasdonahoe/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Verifying download
==> Determining which verifications to run for Cask android-sdk
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask android-sdk
==> SHA256 checksums match
==> Installing Cask android-sdk
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/thomasdonahoe/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip"]
==> Checking container class Hbc::Container::SevenZip
==> Checking container class Hbc::Container::Sit
==> Checking container class Hbc::Container::Rar
==> Checking container class Hbc::Container::Zip
==> Using container class Hbc::Container::Zip for /Users/thomasdonahoe/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip
==> Executing: ["/usr/bin/ditto", "-x", "-k", "--", "/Users/thomasdonahoe/Library/Caches/Homebrew/Cask/android-sdk--3859397,26.0.2.zip", "/var/folders/y7/1qnc46d17d5ch7z2ppz5p7sm0000gn/T/d20171024-29967-1iow45h"]
==> Creating metadata directory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.2/20171024163554.085.
==> Creating metadata subdirectory /usr/local/Caskroom/android-sdk/.metadata/3859397,26.0.2/20171024163554.085/Casks.
==> Installing artifacts
==> 47 artifact/s defined
#<SortedSet:0x007fdbccb5e488>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/sdkmanager", "tools", "platform-tools", "build-tools;26.0.2"]
==> Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
==> 	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
==> 	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
==> 	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
==> 	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
==> Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
==> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
==> 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
==> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
==> 	... 5 more
==> Purging files for version 3859397,26.0.2 of Cask android-sdk
Error: Command failed to execute!

==> Failed command:
/usr/local/Caskroom/android-sdk/3859397,26.0.2/tools/bin/sdkmanager tools platform-tools build-tools;26.0.2

==> Standard Output of failed command:


==> Standard Error of failed command:
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:117)
	at com.android.sdklib.tool.SdkManagerCli.main(SdkManagerCli.java:93)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 5 more


==> Exit status of failed command:
#<Process::Status: pid 30098 exit 1>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:76:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:80:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:191:in `block in install_artifacts'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:183:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:97:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:19:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:13:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:97:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:167:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:172:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:155:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:131:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'`

And just in case, here is my brew cask doctor:
`Thomass-MacBook:~ thomasdonahoe$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.3.6-83-gcd61430
caskroom/homebrew-cask (git revision 648de; last commit 2017-10-24)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 329.3MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3771 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (173 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Gems/2.3.0/gems/did_you_mean-1.0.0/lib
/Library/Ruby/Site/2.3.0
/Library/Ruby/Site/2.3.0/x86_64-darwin17
/Library/Ruby/Site/2.3.0/universal-darwin17
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby/2.3.0/universal-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/x86_64-darwin17
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin17
==> Environment Variables
LANG="en_US.UTF-8"
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
`

**Comment by TheInternet** [comment]
Was helped on another thread and found the solution. I had uninstalled Java9 wrong.

Here was the command that worked to uninstall java9 and reinstall java8:
`brew cask uninstall --force java && brew cask reinstall java8`
