### ISSUE TITLE
iterm2.rb: add option to install Shell Integration

### ISSUE THREAD

**Issue by ahmetb** [caskroom/homebrew-cask#39439]
[iterm2.rb(https://github.com/caskroom/homebrew-cask/blob/master/Casks/iterm2.rb) currently only installs iTerm2. However to enable things like [Touch Bar support](https://www.iterm2.com/documentation-touch-bar.html) one must install the [Shell Integration](https://www.iterm2.com/documentation-shell-integration.html) manually, by running:

    curl -L https://iterm2.com/misc/install_shell_integration.sh | bash

Having this installed separately (and not declaratively, i.e. in a Brewfile) defeats the purpose of automating things with Brew/Cask. I think we must have a flag:

    brew cask install iterm2 --with-shell-integration

Thoughts?

**Comment by vitorgalvao** [comment]
> Having this installed separately (and not declaratively, i.e. in a Brewfile) defeats the purpose of automating things with Brew/Cask.

I disagree. And I guess most other users do as well, since this has never come up as an issue.

> Thoughts?

We don’t support install flags, so your suggestion is not an option. We’re also not going to auto-run that install step when most users presumably do not want/need it.

Your only bet at this time is to add that command to your script/install step, I’m afraid.
