### ISSUE TITLE
Casks with dead homepage but functioning url

### ISSUE THREAD

**Issue by miccal** [caskroom/homebrew-cask#39571]
The following Casks have a dead `homepage` but a functioning `url`:

- [ ] [bleep](https://github.com/caskroom/homebrew-cask/blob/master/Casks/bleep.rb)
- [ ] [cachewarmer](https://github.com/caskroom/homebrew-cask/blob/master/Casks/cachewarmer.rb)
- [ ] [neutrinometrics](https://github.com/caskroom/homebrew-cask/blob/master/Casks/neutrinometrics.rb)
- [ ] [stretchlink](https://github.com/caskroom/homebrew-cask/blob/master/Casks/stretchlink.rb)

@commitay can you confirm that the `homepage`'s are dead?

**Comment by commitay** [comment]
- cctalk: works
- story-writer: works

- stretchlink: dead

The rest have DNS issues so I'm not sure if they are dead or not.

**Comment by commitay** [comment]
- bleep: dead 
- cachewarmer: not sure if this is the same thing? https://www.cache-warmer.com/
- cctalk: works
- neutrinometrics: dead
- story-writer: works
- stretchlink: dead 
- zest: homepage could be changed to https://zestdocs.github.io/

**Comment by miccal** [comment]
Thanks @commitay - I cannot verify if your link for `cachewarmer`is for the same app, since it requires a registration.

**Comment by commitay** [comment]
`cachewarmer` and https://www.cache-warmer.com/ are different, so I guess we can remove it.

**Comment by miccal** [comment]
But the issue is `brew cask fetch` work for all four of them.

**Comment by vitorgalvao** [comment]
When the homepage is dead, I’m more inclined to remove the cask, *after trying to contact the developers*.

My logic being that one of the major reasons we remove/refuse casks is they’re not auditable (e.g. walled downloads). If an app does not have a homepage, then it’s like it’s walled: technically `homepage` and `url` do not match, because `homepage` is `null`. Downloading from a source without a homepage (even if one existed at one point) feels the same as downloading from a random person’s FTP server, i.e., untrustworthy.

That’s why I’d remove it *after trying to contact the developers*, to make sure the dead homepage isn’t a temporary fluke.

**Comment by miccal** [comment]
@vitorgalvao agreed.

I am not on Twitter/Facebook/any social media, so I am not sure what is the best way to chase these up?

**Comment by vitorgalvao** [comment]
@miccal Since we don’t have a website to check for contacts, I’d either do a quick web search or search Twitter (you can do so without an account) as it’s common for companies to have contact info on their bio.

For example bleep seems pretty dead. [People are asking about it on Twitter](https://twitter.com/search?q=bleep%20bittorrent&src=typd); [the iOS app](https://itunes.apple.com/us/app/bittorrent-bleep/id941305420) was last updated over a year ago; [the blog](http://blog.bittorrent.com/tag/bleep/) last mentions it over two years ago.

**Comment by vitorgalvao** [comment]
Neutrinometrics [has a single tweet](https://twitter.com/neutrinometrics) and I can’t find much more about them. Ditto with the other two.

I think it’s safe to remove them all.

**Comment by miccal** [comment]
Thanks @commitay and @vitorgalvao for the help.
