### ISSUE TITLE
Is it possible to add a launchd service to a cask formula?

### ISSUE THREAD

**Issue by szdavid92** [caskroom/homebrew-cask#40931]
This question crops up with the Emacs cask for me. It work perfectly fine, but I want to use Emacs in daemon mode as well. The ideal experience for me would be a launchd service. The bottle version has support for this, and I wonder if it'd make sense to add it the cask version as well? I tried editing the formula but brew says:
```
Warning: Unexpected method 'plist_options' called on Cask emacs.
```

**Comment by vitorgalvao** [comment]
> I tried editing the formula but brew says

Because it’s not a formula; it’s a cask. They are different formats with different capabilities: you can’t just grab from one to the other.

The need for this in HBC is extremely *limited*. There’s virtually no demand, and it’s not something worth spending time on, as of now.

Why don’t you use the formula? It has a flag to build the cocoa app.
