### ISSUE TITLE
Feature request: "incompatibility" caveat

### ISSUE THREAD

**Issue by duncdrum** [caskroom/homebrew-cask#41632]
### Description of feature/enhancement
The stanza would be `true/false`. It should include a link that maintainers provide to e.g. documentation, release notes, upgrade guides etc.  

If set to true, installation of the cask requires user confirmation, before proceeding. 

### Justification
some applications write data in application specific formats to the users disc. That means that every now and then an update comes along that requires user intervention in order for the new app to work properly with data written by the old app.

### Example use case
The result would look something like this:
```bash
$ brew cask install awesome-app …

awesome-app 3.8 is NOT backwards compatible. 
If you want to use this app with data created by older versions, see:
http://www:awesome-app.com/release-notes.html before continuing.

$ Continue with installation (Y/n): 
```

Alternatively the caveat could be restricted to ``brew cask upgrade/reinstall`` instead of ``install``

**Comment by vitorgalvao** [comment]
This falls within the scope of “[not a discoverability service](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/not_a_discoverability_service.md)”:

> users are expected to have reasonable knowledge about the apps they’re installing through us before doing so.

**Comment by vitorgalvao** [comment]
You proposed solution wouldn’t work for your problem. A stanza alone is insufficient for this.

Picture this: we’re both at version 3.9 and a backwards-incompatible 4.0 is released with the stanza. You upgrade by I don’t (I missed it). Then a version 4.1 is released. Do we remove the stanza? Because if you don’t, you’ll still have it there and get the same (wrong) warning. But if you do, I won’t get the warning when I upgrade.

Then we have to enter the realm of making the stanza accept a version number, but then we change the format, ….

We toyed with a similar idea in the past. It’s not worth the trouble.
