### ISSUE TITLE
Version numbers in casks without a version in the download url

### ISSUE THREAD

**Issue by brianmorton** [caskroom/homebrew-cask#43822]
Consider the file in this PR: https://github.com/caskroom/homebrew-cask/pull/43818

I have seen a few casks like this where there is a version defined (not `:latest`), however the download `url` has no versioning. There is usually an appcast, but I'm not sure I can see the relevance here. Should these just be updated to `:latest`?

**Comment by commitay** [comment]
It has an appcast?

**Comment by brianmorton** [comment]
I think so? (below is the output of the file in the PR, for reference)

```
cask 'integrity' do
  version '6.12.0'
  sha256 '35b1ed9b60d232e0d261f9676f13e6e4bdb401f322e136fac84ac461e1aac136'

  # peacockmedia.co.uk/integrity was verified as official when first introduced to the cask
  url 'http://peacockmedia.co.uk/integrity/integrity.dmg'
  appcast 'http://peacockmedia.software/mac/integrity/version_history.html',
          checkpoint: '270cde964ce48efcff18858908bd92d9531851d4c20fc69871fe1d459db02b30'
  name 'Integrity'
  homepage 'http://peacockmedia.software/mac/integrity/'

  app 'Integrity.app'

  zap trash: [
               '~/Library/Application Support/Integrity',
               '~/Library/Caches/com.peacockmedia.integrity',
               '~/Library/Cookies/com.peacockmedia.integrity.binarycookies',
               '~/Library/Preferences/com.peacockmedia.integrity.plist',
             ]
end
```

**Comment by commitay** [comment]
Yes, it has an appcast.

> but I'm not sure I can see the relevance here

I don't understand what you mean by this?

**Comment by brianmorton** [comment]
How does the appcast help? Since the download link is the same for all versions, what does the version number (or appcast) matter?

**Comment by commitay** [comment]
The majority of users prefer versioned Casks so if a suitable appcast is available we use it to version Casks that would otherwise be `latest`.

**Comment by brianmorton** [comment]
heh ok... I guess my point is that if you run `brew cask install integrity` before or after a new version is available, you will still get the latest, however homebrew might not match the version you have installed depending on when the formula was last updated.

So to me it doesn't really make sense to have a version number for the cask if the download url is not also versioned.

**Comment by commitay** [comment]
> if you run brew cask install integrity before or after a new version is available, you will still get the latest, however homebrew might not match the version

The checksum won't match (install will fail) if the upstream download has changed.

**Comment by brianmorton** [comment]
OK. I personally would prefer `:latest` and `:no_check` but I can at least understand why this repo does this now.

**Comment by commitay** [comment]
It all depends on the Cask.

If they break really frequently we might change them back to latest or make them versioned with 
 sha256 `:no_check`.

Occasionally we refuse PRs changing latest to versioned (with and without appcast) because they are updated too frequently or the versioned download isn't public.

A few examples: https://github.com/caskroom/homebrew-cask/pull/37915, https://github.com/caskroom/homebrew-cask/pull/37090, https://github.com/caskroom/homebrew-cask/pull/41520, https://github.com/caskroom/homebrew-cask/pull/37125, https://github.com/caskroom/homebrew-versions/pull/4823

Closing as the question has been answered but feel free to keep talking if you have any questions.

**Comment by vitorgalvao** [comment]
> OK. I personally would prefer `:latest` and `:no_check` but I can at least understand why this repo does this now.
>
> EDIT to clarify: as when I install I'd rather just get the latest than a checksum error... less friction when all I really wanted was the cask installed.

Like yourself, at the time of the initial discussion I preferred `:latest`. But you missed the boat on that one. When we asked users about it, the answer was overwhelming in favour of having versioned casks, in large part for security reasons. So much so, we eventually even added an install flag that prevents the installation of casks without a checksum.

As stated, we don’t version casks with unversioned URLs because they tend to break with some frequency. The reason we still version casks with an appcast but unversioned URL is that with an (eventual) automated system in place, we’ll catch those updates more frequently, and the cask won’t break as much.
