### ISSUE TITLE
Silence the cleanup

### ISSUE THREAD

**Issue by lexfrei** [caskroom/homebrew-cask#44254]
Hello!
Could you please silence the cleanup action if nothing to do?
```
sviridkin@mbp:~$ brew cask cleanup
==> Removing cached downloads
Nothing to do
✓ @ Fri Feb 23 13:55:48 MSK 2018
sviridkin@mbp:~$ brew cleanup
✓ @ Fri Feb 23 13:55:56 MSK 2018
```
My arguments:
- The brew works differently.
- >Rule of Silence
Developers should design programs so that they do not print unnecessary output. This rule aims to allow other programs and developers to pick out the information they need from a program's output without having to parse verbosity.
Eric Raymond

**Comment by vitorgalvao** [comment]
I disagree we should print nothing. It’s not unnecessary information to know *the command ran correctly, and the outcome of that correct action is to do nothing*. That is preferable to running something and be left to wonder if it worked at all.

Our usage also does not conflict with the Rule of Silence, as it specifically states (emphasis added): “to allow other programs and developers to pick out the information they need **from a program's output** without having to parse verbosity”. There’s no verbosity to parse from the program’s output, because if there’s nothing to do that message is output to `stderr`, not `stdout`. On the other hand, if there is indeed something to do, the information is output instead to `stdout`.

So there’s no conflict, here. The distinction between having done something or not is clear in the flow of automating.

I do agree that we should be consistent with non-cask brew, but in this case I think we have the correct behaviour.

**Comment by smoreg** [comment]
I think empty output enough to understand `brew cask cleanup` result. For something more `-v` can be used.

**Comment by vitorgalvao** [comment]
@smoreg `brew cleanup -v` results in no more output when there’s nothing to do, so adding a `-v` flag does not solve the issue (it’d need to be added in both cases).

Also, it’s a worse experience. No wants to think “there’s no output, I don’t know if it ran correctly or not, let me blindly add a `-v` flag or dig into the documentation”. Especially since not all tools have an option for verbose output, and you’re never sure if `-v` means “be verbose” or “show me the installed version”.

**Comment by commitay** [comment]
Closing as per https://github.com/caskroom/homebrew-cask/issues/44254#issuecomment-367995800
