### ISSUE TITLE
Use axel for downloading?

### ISSUE THREAD

**Issue by zhigang1992** [caskroom/homebrew-cask#5552]
It's really slow right now...

**Comment by vitorgalvao** [comment]
I see adding `axel` as a really bad idea. It’s latest stable release is almost 5 years old, and after trying it extensively in real situations with download urls present in casks, I can say that the amount of times the “too many redirects” error occurs is absolutely ridiculous (lots of similar found only, without any resolutions). [`aria2`](http://aria2.sourceforge.net/) is always mentioned as the superior alternative.

Alternatives aside, the point is we’re just going to create more issues<sup>1</sup>. The [opinions](https://github.com/Homebrew/homebrew/issues/14855#issuecomment-8468354) [expressed](https://github.com/Homebrew/homebrew/pull/16204#issuecomment-12477422) in homebrew seem extremely valid, to me.

If any maintainer feels strongly about including this, feel free to reopen it. I say we [wait and see](https://github.com/Homebrew/homebrew/pull/16204#issuecomment-12478045).

---

<sup>1</sup>Issues that are incredibly difficult to debug. `curl` is predictable down to its version, because it comes with OS X. Third-party downloaders are the extreme opposite.
