### ISSUE TITLE
Search results indicate app store non-cask apps

### ISSUE THREAD

**Issue by focusaurus** [caskroom/homebrew-cask#5779]
Suggestion for `brew cask search` to list specific casks that are known but will not be added to the official repo due to the trial version/app store policy.

I started to build a cask for BusyCal before I found the policy about App Store re-downloads and researched to discover BusyCal would fall under that category. My suggestion is that `brew cask search busycal` report something like `BusyCal is not available as a cask. Please purchase and install via the Mac App Store` or something along those lines with a link to the app store page and relevant cask docs on the policy perhaps.

**Comment by vitorgalvao** [comment]
I’ve reread the whole issue, and it seems no actual decision has been made. We should either refuse the idea and close this, or accept it, close this, and create a new issue outlining what needs to be done.

As someone who reads every issue and submission, I don’t think this is such a big issue, and the MAS rule seems to be fairly well known amongst contributors, even new ones. Realistically, perhaps most contributors don’t read through [CONTRIBUTING.md](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md), but they really should, especially since we have a section named “[finding a home for your cask](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#finding-a-home-for-your-cask)”, with [the policy on MAS apps clearly stated](https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#trial-versions).

There seems to be consensus that maintaining a file referencing every app that shouldn’t be included is more trouble than it’s worth, but the alternative — printing a generic message *every time a user doesn’t find something* — seems nonsensical, to me: we’d just be rehashing what’s in the documentation already. Sure, some things need to be explicit in more than one place for the benefit of the user, but if we start adding every possibility, every “this might happen”, the user will be overwhelmed with messages and will care for none of them. We have to draw the line somewhere — the rule is stated clearly under the appropriate section, on the document accessible every time the “New issue” button is clicked, that is on the root of the project, with a standard name for github projects, in all caps. What more can we ask, here? Some rules are more important than others, and judging by the huge decline in submissions of MAS apps, this one seems very well covered.

I’ll close the issue on those grounds, but if any other maintainer disagrees, please reopen it so we can outline the next steps we need to take.
