### ISSUE TITLE
Cask TrueCrypt fails to install on Yosemite

### ISSUE THREAD

**Issue by holtkamp** [caskroom/homebrew-cask#7693]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/truecrypt.rb

Due to a whacky version check, the installer thinks OSX 10.10.1 is not above 10.4:

```
==> installer: Error - TrueCrypt requires Mac OS X 10.4 or later.
```

Also see: 
http://tips.tinyiron.net/yosemite-to-truecrypt-never-gonna-get-it/
https://stefansundin.com/blog/656

Adding this line to the installation script might fix it:

```
sed -i '' 's/<installation-check .*>//' 'TrueCrypt 7.1a.mpkg/Contents/distribution.dist'
```

PS: I am new with brew / cask and do not feel confident enough Cask to come up with a PR...

**Comment by alebcay** [comment]
Perhaps I'll consider building this into `alehouse` and provide a Yosemite-compatible fork available via `caskroom/unofficial`.

**Comment by vitorgalvao** [comment]
I’ve made some tests with the `sed` hack, and it didn’t solve the issue. Following @DomT4’s suggestion might be the best solution, or even [installing it manually](http://tips.tinyiron.net/yosemite-to-truecrypt-never-gonna-get-it/). I’ve found numerous solutions for how to do it in this manner, and since this is a piece of software that will only decline in usage and whose only reason to install it is to move your data somewhere else, spending time on trying to make it work with automation is a bit of a waste.

Either way, I understand the desire to have this at least until the next OS X release, and if someone does indeed want to take a stab at fixing it (not going to happen, I bet), [the issue is referenced in the appropriate repo](https://github.com/caskroom/homebrew-unofficial/issues/42).

**Comment by trinitronx** [comment]
@vitorgalvao:  How is TrueCrypt dangerous to use still?  Since the original developer's strange disappearing act and unsubstantiated claim that it was unsafe, it has now gone through [an official 3rd party audit][1], and has come away with an overall clean bill of health.  Only a couple very minor flaws were found as reported on multiple news & blog sites (e.g.: [ArsTechnica][2], [The Register][3], [Cryptography Engineering Blog][4], [Is TrueCrypt Audited Yet][5], [GRC][6]).   As mentioned the largest potential flaw found was an unlikely special case where the Windows Crypto API _may_ fail and TrueCrypt would not issue a security warning, but overall the other flaws found are minor and the consensus is that it's still safe to use.  Perhaps the best thing that happened to TrueCrypt is that the author abandoned it... for it gave reason for people to take notice & actually give it an audit.  We now have enough conclusive evidence to reasonably determine it is safe to use to provide sufficient protection for sensitive data.

[1]: https://opencryptoaudit.org/reports/iSec_Final_Open_Crypto_Audit_Project_TrueCrypt_Security_Assessment.pdf
[2]: http://arstechnica.com/security/2015/04/truecrypt-security-audit-is-good-news-so-why-all-the-glum-faces/
[3]: http://www.theregister.co.uk/2015/04/02/truecrypt_security_audit/
[4]: http://blog.cryptographyengineering.com/2015/04/truecrypt-report.html
[5]: http://istruecryptauditedyet.com/
[6]: https://www.grc.com/misc/truecrypt/truecrypt.htm

**Comment by vitorgalvao** [comment]
@trinitronx I don’t remember everything from this thread, and quite frankly I don’t intend to reread it, or the links you’ve posted (thank you for taking the time for doing the research, though). I still read my last comment, to see if I can get some modicum of context. I doubt there’s anything left to add. As far as I’m concerned, this issue is closed (in all senses).

Truecrypt is a broken cask whose use will only decline. There is no desire from any of the (all volunteer) maintainers in wasting (and I do mean waste) time fixing it, and I do not think any of us should. The cask [still exists](https://github.com/caskroom/homebrew-unofficial/blob/master/Casks/truecrypt.rb) in [an alternate repo](https://github.com/caskroom/homebrew-unofficial), and anyone can create [a tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/brew-tap.md) for it. If you wish to [fix it](https://github.com/caskroom/homebrew-unofficial/issues/42), submit a PR and we’ll accept it (on that repo, not the main one) and may even keep it around longer; otherwise, the plan stays the same.

**Comment by alebcay** [comment]
Even if the Cask itself is fixed, I must add that the software is no longer actively maintained. If you need a successor to TrueCrypt, I suggest looking into [VeraCrypt](https://veracrypt.codeplex.com/), which seems somewhat promising (and we should probably get a Cask for it soon).

**Comment by trinitronx** [comment]
@alebcay:  I realize it's sadly no longer maintained.  However, it is still useful software and I'm sure not alone in still wanting to use it.  I haven't played around with VeraCrypt yet and it looks promising, but I was used to using Truecrypt from homebrew and really wanted something still installable via homebrew.  So I took @vitorgalvao 's advice.

For those stubborn folks like me who still want to use the trusty old Truecrypt:

I've managed to create a [homebrew Cask Tap for Truecrypt 7.1a][1] (after working around an installer bug on OS X Yosemite)

[1]: https://github.com/trinitronx/homebrew-truecrypt

**Comment by vitorgalvao** [comment]
Thumbs up to that, your tap looks great! Way better than anything we’d have here, even if we fixed it. Very informative, as this case warrants. Any future truecrypt issues shall be redirect to your tap.

Thank you.

**Comment by nunocalaim** [comment]
So there is still no cask for veracrypt?

**Comment by vitorgalvao** [comment]
> So there is still no cask for veracrypt?

Clearly there’s no demand for it. You’re free to submit it for review, as no one is working on it (or even thinking about it, I’d say).

**Comment by nunocalaim** [comment]
I see, this must mean that people use another software for encryption? Or
cask users do not encrypt at all?

**Comment by vitorgalvao** [comment]
> Or cask users do not encrypt at all?

This would be a big generalisation, and I do know it’s not the truth.

Why no one ever submitted that cask, however, I do not know.

**Comment by trinitronx** [comment]
Sorry to resurrect an old thread... but I thought I'd add this info here for those following or interested.

It appears that there was an opened [pull request for VeraCrypt][1] in caskroom/homebrew-cask#12736, but it could not be accepted due to unverifiable URL, and that it did not use GPG or PGP signature verification on the `dmg`.  This appears totally feasible, as the links are there for both [VeraCrypt DMG][2], and [VeraCrypt DMG Signature][3].  Although there is no guarantee by CodePlex that these `/get/xxxxxx` numbered URLs will always be reliable as permalinks... they appear to at the very least be specific to a single release, and therefore may be used together to guarantee that the Signature & DMG match, and _should_ also match a hardcoded `sha256sum`.

I think the main point I would make given the discussion above (and the reality of how OSS is developed), is that although Vítor says above:

> Clearly there’s no demand for it. You’re free to submit it for review, as no one is working on it (or even thinking about it, I’d say).

There is a very slight difference between "demand" for something and "supply" & willingness of people in the community to actually create the supply of it.  Luckily in software, only one person has to create it and then it can be shared with everyone & copied indefinitely and infinitely in a manner which is only limited by physical storage & machines to run the software.

So like Vítor says, anyone is free to work on it & collaborate to create it... it just hasn't been fully completed yet in a manner that passes quality & security concerns of the community.  It's totally doable, but due to limitations on time, and since I still use [TrueCrypt from my tap][4], I have no need for it, there is no other reward financially or otherwise for me to do it (If you haven't noticed, [I am paid $0.0][5] for any of the OSS I have worked on), and I have no desire to maintain yet another project which I won't use that much.

Just thought I'd help give the community & people interested in this the links & resources necessary for it's creation, in case there is still interest & demand.  Feel free to create a fork from my tap & use it as a reference on how to create one for VeraCrypt.  Who knows... if there's enough interest or if it gets put on bountysource, I may take a couple hours to see if I can do it.

[1]: https://github.com/caskroom/homebrew-cask/pull/12736
[2]: https://veracrypt.codeplex.com/downloads/get/1537180
[3]: https://veracrypt.codeplex.com/downloads/get/1537183
[4]: https://github.com/trinitronx/homebrew-truecrypt
[5]: https://gratipay.com/~trinitronx/
[6]: https://www.bountysource.com

**Comment by trinitronx** [comment]
@vitorgalvao :  On a side note... I wanted to ask what the process is to become a collaborator on homebrew & homebrew cask?

**Comment by alebcay** [comment]
> there is no guarantee by CodePlex that these /get/xxxxxx numbered URLs will always be reliable as permalinks... they appear to at the very least be specific to a single release, and therefore may be used together to guarantee that the Signature & DMG match, and should also match a hardcoded sha256sum.

[Unfortunately, this is not the case.](https://github.com/caskroom/homebrew-cask/issues/6618)

**Comment by vitorgalvao** [comment]
@trinitronx We know what demand looks like. Some apps, people keep asking for them even after they’re added or submitting pull requests after they have already been rejected multiple times. This app has no demand. Simple.

It’s unlikely we will ever get boutysources for casks. For core features perhaps, but for casks that’s a bit much.

We have no managerial relationship with homebrew. They do it they’re way, we do it ours. We have different needs, different rules to conform to those needs, different teams, different approaches. We also agree the other is doing a good job and plan to keep this separation of how to do things. I have no idea how they pick people to join their team, but I guess they might do it the same as we do.

For us, quite frankly I currently don’t believe you’d be able to become a good fit. Quite briefly, to become a core maintainer we invite you, not the other way around.

For us to notice your good work, you actually need to do good continuous good work as a contributor, triaging issues, helping users, contributing to the core (which we need more core maintainers for) or to casks (which current maintainers have well covered). For that, you need availability, which at the moment it seems like that’s not something you have.

**Comment by vitorgalvao** [comment]
Good news, @nunocalaim. See https://github.com/caskroom/homebrew-cask/pull/20386.
