### ISSUE TITLE
Alfred 2.4+ detected, but local preferences file not found

### ISSUE THREAD

**Issue by alexlouden** [caskroom/homebrew-cask#8052]
I'm having the same error as #7216 - see [my comment there](https://github.com/caskroom/homebrew-cask/issues/7216#issuecomment-66618568).

As requested, I've run the link command with the debug flag:

```bash
❯ brew cask alfred link --debug                            
==> Creating directories
==> Reading Alfred primary preferences
==> Executing: ["/usr/bin/defaults", "read", "com.runningwithcrayons.Alfred-Preferences", "version"]
==> Reading Alfred primary preferences
==> Executing: ["/usr/bin/defaults", "read", "com.runningwithcrayons.Alfred-Preferences", "syncfolder"]
==> 2014-12-12 14:02:17.573 defaults[38188:333772] 
==> The domain/default pair of (/Users/alex/Library/Preferences/com.runningwithcrayons.Alf
Error: Alfred 2.4+ detected, but local preferences file not found. Try running Alfred first.
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/alfred.rb:50:in `assert_installed'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/alfred.rb:56:in `link'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli/alfred.rb:33:in `run'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli.rb:81:in `run_command'
/usr/local/Cellar/brew-cask/0.50.0/rubylib/cask/cli.rb:121:in `process'
/usr/local/bin/brew-cask.rb:42:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:59:in `require?'
/usr/local/Library/brew.rb:142:in `<main>'
```

Here are my alfred preferences - there seems to be no `syncfolder`?
```bash
~/Library/Preferences  
❯ defaults read com.runningwithcrayons.Alfred-Preferences
{
    NSNavLastRootDirectory = "~/Applications";
    NSNavPanelExpandedSizeForOpenMode = "{750, 480}";
    "NSToolbar Configuration com.apple.NSColorPanel" =     {
        "TB Is Shown" = 1;
    };
    "NSWindow Frame alfredpreferences" = "79 115 1100 662 0 0 1280 777 ";
    lastTab = appearance;
    lastTabBuild = 308;
    lastTabTS = "439999406.510222";
    version = "2.5.1";
}
```

Perhaps because I haven't synced my Alfred:
![screen shot 2014-12-12 at 2 05 37 pm](https://cloud.githubusercontent.com/assets/1332954/5407767/50a8fd66-8208-11e4-9e03-787b8214a580.png)

**Comment by Coaxial** [comment]
Yes, adding that users can manually add `/opt/homebrew-cask/Caskroom` to the searched folders would help. This fixed it for me but it took some time to find.

**Comment by toolbear** [comment]
FWIW, I had a [short twitter dialog with @alfredapp](https://twitter.com/toolbear74/status/554041867294085120) suggesting Alfred find symlinked apps in their search scope, which naturally includes `/Applications` by default.

I think this is a failing on Alfred's part not Cask's when out of the box Spotlight (at least on Yosemite) has the right behavior and Alfred doesn't (where "right behavior" is finding installed apps). In Spotlight's case, it finds the original, not the symlink. Since one of Alfred's core features is reduced search scope, I suggested the symlink thing. Were Alfred a little smarter wrt symlinked apps, then `brew cask alfred` could go away entirely. It also wouldn't matter which installer I used as long as it created a symlink.

In terms of error message for non-paid users, perhaps reference the link to [Alfred's own kb article](http://support.alfredapp.com/kb:symlinked-apps) (which sparked my Twitter snark).

**Comment by preppeller** [comment]
Hey there, just thought I'd pop a little response in here...

The syncfolder is only ever set if the user has set a sync folder, which may be never. If a syncfolder has never been set (or the user is a non Powerpack user), you can just assume that Alfred.alfredpreferences will be located in /Library/Application Support/Alfred 2/

Alfred, by design, has a more limited search scope than Spotlight to give more relevant and focused results with higher performance, as such, things like homebrew have unfortunately been left out of this (as the homebrew folder may be different per user). [Deep] Indexing symlinks is a huge headache for various reasons... So to flip this around a little bit, is there an easy way Alfred can find where a user's homebrew Cellar folder is? This way, I could add an option (enabled by default) which automatically includes the homebrew Cellar folder as part of Alfred's default search scope if installed.

Cheers,
Andrew

**Comment by vitorgalvao** [comment]
Thank you for stopping by, Andrew.

Adding the default directories for the Cellar (`/usr/local/Cellar`) and the Caskroom (`/opt/homebrew-cask/Caskroom`) would already be a great step. It would solve the issue for most people with the least amount of work, and if the directories don’t exist at those locations, no harm done<sup>1</sup>.

As for detecting the location of those directories, that could be a pain since you couldn’t just `brew --cellar` or `/usr/local/bin/brew --cellar`, since the idea is exactly that you don’t know where `brew` is, if installed to a custom location. It could require you to read the user’s PATH, but to do that you’d need to know what their shell is (I [do it](https://github.com/vitorgalvao/alfred-workflows/blob/1e188e21e40dabde61cf60c683bc289d9327b111/RunCommand/runcommand#L6-23) as part of an Alfred Workflow, but that’s not entirely ideal for this case). Automatically firing a terminal won’t really work because we couldn’t be sure even then<sup>2</sup>.

All that said, to find homebrew’s Cellar you can `brew --cellar`, while to find the Caskroom you’d (currently) have to do a bit of trick like `brew cask doctor | grep -A 1 'Staging Location' | tail -1`.

I’ll reiterate, however, that just including their default directories in Alfred’s results by default might be the best solution for the amount of work it requires.

---

<sup>1</sup>Yes, there could still exist user-created directories in those exact locations with those exact highly-specific names, but that is extremely unlikely.

<sup>2</sup>My default terminal application is iTerm, while I keep Terminal pristine on purpose for when I need to check if something is working/failing due to my custom configurations or not. Yes, Alfred does have the option to pick a default terminal, but it seems to be limited to those two and that assumes the user had actually changed that setting.

**Comment by toolbear** [comment]
Yes, cheers @preppeller.

> I’ll reiterate, however, that just including their default directories in Alfred’s results by default might be the best solution for the amount of work it requires.

This would probably solve it for 80% or more of homebrew and cask users. The odds that non-homebrew `/usr/local/Cellar` & `/opt/homebrew-cask/Caskroom` exist **and** contain apps **and** users don't wish them found are indeed pretty low.

This would have solved it for all but one of my problem apps. Only `Emacs.app` wouldn't be found by default and only because I install it with vanilla `brew` instead of `brew cask` and only because my Homebrew is at a non-standard location (via @boxen). An edge case that I'm willing to accept as my responsibility.

One potential snag is that Alfred's default search scope applies to more than just applications. The out-of-the-box defaults are pretty safe, but users that include *Extras* like *Archives*, *Images*, or *Text Files* may dislike that internal files from tools like `git`, `node`, or `python` are in their Alfred search results. Ideally it would only search `Cellar` for apps, but that's not how Alfred's search scope works today. That said, users would be no worse off than when they manually add `Cellar` today; if they would be unhappy with the new defaults they could remove `Cellar` from their search scope.

**Comment by preppeller** [comment]
Cool, thanks for the info! I'll just add these two folders to Alfred's default search scope in 2.6... people can always remove these if they don't want Alfred finding stuff in there.

It's worth noting that this will only affect Alfred's default search scope... if somebody has modified their search scope (added or removed items), they won't see these paths added. It will help for all new Alfred users, and all users who haven't changed Alfred's default scope.

Hope this helps :)

Cheers!
Andrew

**Comment by pbowyer** [comment]
Definitely :) Thanks Andrew!

On 12 January 2015 at 00:05, Andrew Pepperrell <notifications@github.com>
wrote:

> Cool, thanks for the info! I'll just add these two folders to Alfred's
> default search scope in 2.6... people can always remove these if they don't
> want Alfred finding stuff in there.
>
> It's worth noting that this will only affect Alfred's default search
> scope... if somebody has modified their search scope (added or removed
> items), they won't see these paths added. It will help for all new Alfred
> users, and all users who haven't changed Alfred's default scope.
>
> Hope this helps :)
>
> Cheers!
> Andrew
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/caskroom/homebrew-cask/issues/8052#issuecomment-69518811>
> .
>



-- 
Maple Design Ltd
http://www.mapledesign.co.uk
+44 (0)845 123 8008

Reg. in England no. 05920531

**Comment by preppeller** [comment]
I've now added these folders into Alfred's 2.6 default search scope. 2.6 should be out in a few weeks or so...

![homebrew](https://cloud.githubusercontent.com/assets/3470746/5702484/cddd9fc8-9a52-11e4-90b8-3f82ebbdc3ab.png)

Cheers,
Andrew :)

**Comment by toolbear** [comment]
🍻

**Comment by jeremybradbury** [comment]
Adding to the list isn't quite easy. 

Until 2.6 comes out... this works well in the standard Mac terminal if you only have one UID. 

```shell
nano "~/Library/Application Support/Alfred 2/Alfred.alfredpreferences/preferences/local/$(ls ~/Library/Application\ Support/Alfred\ 2/Alfred.alfredpreferences/preferences/local)features/defaultresults/prefs.plist"
```
add these to the scope:
```xml
		<string>/usr/local/Cellar/</string>
		<string>/opt/homebrew-cask/Caskroom</string>
```

**Comment by josegonzalez** [comment]
You can also manually drag folders onto that list.

**Comment by jeremybradbury** [comment]
yes, thanks for mentioning that. 

however it isn't a command line tool (which i need for scripting) AND not everyone knows how to easily access those folders in finder. =)
