### ISSUE TITLE
docs and tests for `:bsexec` parameter to command.run

### ISSUE THREAD

**Issue by rolandwalker** [caskroom/homebrew-cask#8067]
This param is exposed in `installer :script` and so must be documented.

refs: #7957

**Comment by reitermarkus** [comment]
@caskroom/maintainers, was this parameter ever used? If not, I vote for removing it.

**Comment by vitorgalvao** [comment]
I’m fine with removal.

**Comment by claui** [comment]
Yes, there was a short window (Dec 2014 – Feb 2015) where we used this as a non-intrusive fix for #7132. (The alternative would been to enforce `sudo` for every DMG-related operation.) The change was ultimately pulled in #9491 because of a change on Apple’s side, which would require `sudo` for `launchctl bsexec` since 10.10.3.

@rolandwalker wrote a concise summary of the current situation in [#9448 (comment)](https://github.com/caskroom/homebrew-cask/issues/9448#issuecomment-73322199):

> Fairly recently, we started using :bsexec to mount disk images (#7957). Apple has been changing how :bsexec works recently. There could be new changes, and it could be that :bsexec doesn't give us all the needed capabilities anymore.

I tend to concur. Even if someone’s going to fix #7132 one day, I feel the fix is going to be based on something else than `bsexec`.

**Comment by reitermarkus** [comment]
Ok, I will remove it then.
