### ISSUE TITLE
`depends_on :cask` follow-ups

### ISSUE THREAD

**Issue by ndr-qef** [caskroom/homebrew-cask#8492]
Post-release of #8491, we are free to proceed with:
- [x] **Adding dependencies to compatible Casks**  
  In the main repository:
  - [x] cryptol
  - [x] qgis
  - [x] sshfs

Note that Cask dependencies are only available in master, and caveats concerning dependencies must remain intact until release of v0.52.0.

- [ ] **Metacasks** (open to debate)  
Hard Cask dependencies can be used to create “metacasks” (#2001), which would be artifact-less Casks solely bundling other Casks. Such metacasks would serve the purpose of both automation (#6537, #5427) and unification of fragmented upstream packages (#1999).

**Comment by nicolas-brousse** [comment]
I'm not sure if it's the right place, but there is a problem with the `onyx` cask.

It appear the problem is on line `15` in `/usr/local/Cellar/brew-cask/0.52.0/rubylib/hbc/cask_dependencies.rb` file.
`deps` return `nil:NilClass`.

```bash
Error: undefined method `each' for nil:NilClass
```

I have tried with this `https://gist.github.com/nicolas-brousse/fb3edb9815a8ad03cf00` cask.

```bash
$ brew cask install https://gist.githubusercontent.com/nicolas-brousse/fb3edb9815a8ad03cf00/raw/b5d076f1efaab3ec684b952fe12723c5a50a94cc/common-group.rb.
```

**Comment by vitorgalvao** [comment]
@nicolas-brousse Definitely not the right place, please [open a new issue](https://github.com/caskroom/homebrew-cask/issues/new). Your syntax is wrong on the gist, though. It should be `depends_on :cask => <cask-name>`.

**Comment by nicolas-brousse** [comment]
@vitorgalvao Ok. Sorry and thank you.

**Comment by nicolas-brousse** [comment]
In my opinion `metacasks` and `brew bundle` are two different things.

**metacask**
`metacasks` are only group of casks. It could be very useful for company usage (mainly). With it, installing a new computer could be very simple by choosing what kind of metacask you want to install (`devops-matacask` for example). And like this it's also an easy way to have computer up-to-date by "groups". Like I explain it into [#4973 (comment)](https://github.com/caskroom/homebrew-cask/issues/4973#issuecomment-46482729), with this tool it could be very simple to add a software into the company's workflow.

Sure there is some other tools to do something like that but I found these others tool more fat than caskroom.io his. Homebrew cask is very lite and simple, it is so enough :)

**`brew bundle`**
`brew bundle` is also useful for project I think. Sure homebrew have removed it, but I continue to use it. Because for project I found nice to have a file who list the needed packages. For example if for a specific project we need to use `memcached` or `imagemagick`, we can add it in `Brewfile` and be sure the team know what is needed.
It's just my opinion for `brew bundle`.

So for me it's not a replacement but something additional to Homebrew cask.

**Comment by B-Rass** [comment]
"than caskroom.io is"

**Comment by B-Rass** [comment]
"is very light and simple"

**Comment by vitorgalvao** [comment]
I still see absolutely no value in `brew bundle`. There’s nothing it does that can’t be accomplished just as well (and fast) with a simple shell script.

bundle() {
  sed '/^\s*$/d;s/^/brew /' "$1" | sh
}

There. A bash function that’ll take a file as an argument, and do what `brew bundle` did.

**Comment by nicolas-brousse** [comment]
Yes, you are right for `brew bundle`. It could be on an `install.sh` file at the root of the project.

It's not really on this part I am attached but I am on the `metacasks` part.

**Comment by mikemcquaid** [comment]
Again, I recommend https://github.com/andrew/brewdler. I'm going to work on making getting this more officially supported soon.

It uses a decent DSL which describes what the result should be rather than just a stupid list of commands. The previous approach was extremely error-prone and I'd really recommend against implementing anything similar in future.

Metacasks solve a problem but they aren't really a elegant solution. What you really want is something like a `Brewfile` that lives in a repository root and can be used to bootstrap the contents of a project. IMO telling people in the docs to manually run `brew cask install metafoo` is a bit of a smell.

**Comment by jawshooah** [comment]
Agreed. As long as it continues to be actively maintained, I'm all for letting Brewdler do the legwork here.

**Comment by vitorgalvao** [comment]
> It uses a decent DSL which describes what the result should be rather than just a stupid list of commands.

That is good to know. That way I can see value in it.

> Metacasks solve a problem (…)

Well, they solve two, actually, but lets outsource one of those to `brewdler`<sup>1</sup> and focus on the other one. They also allow an easy way to bundle casks that would many times be desirable together. Among them [families of typefaces](font Google Cousine) and [scripts that work well together](https://github.com/caskroom/homebrew-cask/pull/8698) (but don’t necessarily require each other to work). Those should be included in the official repos, not used as personal files.

[Having said that](http://youtu.be/ENHVQ2gslp8), I don’t really care much either way for metacasks and would be fine with either decision. I’m simply pointing out they do have a utility.

---

<sup>1</sup> [I don’t really think metacasks are a replacement for `bundle`, either](https://github.com/caskroom/homebrew-cask/issues/8492#issuecomment-68950848)

**Comment by mikemcquaid** [comment]
Think we're agreed here :+1:

**Comment by vitorgalvao** [comment]
Another use case for metacasks: cask aliases. Referenced in https://github.com/caskroom/homebrew-cask/issues/8938#issuecomment-71541703 and (to an extent, maybe) https://github.com/caskroom/homebrew-cask/pull/9174.

**Comment by mikemcquaid** [comment]
We now have an officially blessed Homebrew implementation that also has `cask` support: https://github.com/Homebrew/homebrew-brewdler

**Comment by adityadalal924** [comment]
https://github.com/Homebrew/homebrew-bundle has Cask support, as @mikemcquaid stated, which fulfills the purpose of "Metacasks" (and closes out discussion on this issue)
