### ISSUE TITLE
brew cask uninstall says software is not installed 

### ISSUE THREAD

**Issue by jitendravyas** [caskroom/homebrew-cask#8644]
![1 zsh nkzv5](https://cloud.githubusercontent.com/assets/77309/5609158/1c930836-94bf-11e4-8517-286a50372078.jpg)

Brew cask is updated to latest version

**Comment by ndr-qef** [comment]
In this case, the solution is to run `brew cask uninstall --force xmind`, which removes all versions of xmind.

The underlying issue is long-standing (#2988), and stems from the fact that we do not yet track packages across versions. When you issue `brew cask uninstall xmind`, the command looks up the *current* definition of the `xmind` Cask, which may not match the one you originally installed.

**Comment by jitendravyas** [comment]
Thanks when I try brew cask uninstall --force xmind it seems to my that it just delete the symlink not a app files.
![1 zsh 1pozx](https://cloud.githubusercontent.com/assets/77309/5610262/f279290c-94d9-11e4-83b1-83572dffb793.jpg)

**Comment by ndr-qef** [comment]
The message only mentions the symlink, but the files staged at `/opt/homebrew-cask/Caskroom/xmind` should also have been removed, along with the folder itself. (You are right that the output is rather unclear; we should improve it.)

**Comment by jitendravyas** [comment]
ok. In your first comment you mentioned "...which removes all versions of xmind.." What do you mean by all versions? Why would anyone want to keep any version of the software which he has planned to not to use further. What would actually happen if we don't add --force
