### ISSUE TITLE
Errors Adding Economacs.App Version 6.0.11

### ISSUE THREAD

**Issue by vinkla** [caskroom/homebrew-cask#8831]
I'm trying to wrap my head around this issue I'm having. When trying to install [Economacs](http://aderstedtsoftware.com/) I encounter the following error message:

```
==> Downloading http://www.aderstedtsoftware.com/downloads/Economacs6.zip
######################################################################## 100.0%
Error: It seems the symlink source is not there: '/opt/homebrew-cask/Caskroom/economacs/6.0.11/Economacs.app'
```
The audits are fine and return green.

```
==> Downloading http://www.aderstedtsoftware.com/downloads/Economacs6.zip
Already downloaded: /Library/Caches/Homebrew/economacs-6.0.11.zip
audit for economacs: passed
```

Below is the `economacs.rb` cask file.
```ruby
cask :v1 => 'economacs' do
  version '6.0.11'
  sha256 'bfb0f926ee84a49fdf2479ecd523ac107ff805c3e2e45c0f50842eb03aa67389'

  url "http://www.aderstedtsoftware.com/downloads/Economacs#{version.to_i}.zip"
  name 'Economacs'
  homepage 'http://aderstedtsoftware.com/'
  license :commercial

  app 'Economacs.app'
end
```

Have I maybe missed some simple configuration?

**Comment by ndr-qef** [comment]
The value of `app` (or any other artifact) is a path relative to the downloaded archive. In this case, the error suggests that `Economacs.app` is not at the top level, but within a folder.

`brew cask audit --download` succeeds because it makes no effort to verify that the definition file is consistent with the actual contents: it is merely an integrity check.

Arguably:
- the “symlink source is not there” error is outdated and should be rephrased to match the current DSL.
- the `audit` command should provide an option to verify that the archive contains the declared artifacts.

Thanks for bringing these issues to our attention.

**Comment by vinkla** [comment]
:+1:

**Comment by vinkla** [comment]
@ndr-qef is there a way to manipulate the cask or does the developers of the Economacs.app need to edit their app zip archive?

**Comment by vitorgalvao** [comment]
The app’s name changes only in the Finder. Do an `ls` and you’ll see it as `iOrdning.app`. Not unheard of, an we are [prepared for it](https://github.com/caskroom/homebrew-cask/blob/57867eef3202dd06d93e67a703188819689c02e8/Casks/devonthink-pro-office.rb#L13-15). In this case we should just change the cask’s name to `iordning`, though, seeing as it’s the original one, and we can’t account for every case.

**Comment by vinkla** [comment]
Renaming it to `iordning` worked great. Thanks as always!
