### ISSUE TITLE
How can I get the details of casks by code

### ISSUE THREAD

**Issue by WitzHsiao** [caskroom/homebrew-cask#8842]
I am willing to do the feature of outdated.
I am wondering how to get the details of casks, like sha256 or something writing in Cask DSL by code.
Anyone can please give me some guide? 
Thanks a lot!

**Comment by vitorgalvao** [comment]
`brew cask cat <cask_name>`.

**Comment by vitorgalvao** [comment]
Wait, I believe I might have misunderstood what you want. What do you mean by “the feature of outdated”? Do you mean upgrading? If so, look at https://github.com/caskroom/homebrew-cask/issues/4678 for what needs to be done.

**Comment by WitzHsiao** [comment]
yes, but first I wanna do outdated first.  Any suggestion?

**Comment by vitorgalvao** [comment]
No, because the items on that list need to be done *before* its implemented. `upgrade` is a (probably the most) highly requested feature that everyone wants. Were it simple to do, it would have been done already, but there are multiple things that need to come first, to make it robust.

**Comment by WitzHsiao** [comment]
But I think it's easier to have outdated feature for doing "upgrad", isn't it?

**Comment by vitorgalvao** [comment]
I don’t understand what you mean. Please rephrase your comment.

**Comment by WitzHsiao** [comment]
I'm not sure if I'm wrong. I mean the upgrade feature is based on outdated feature. So if we have a outdated feature in homebrew-cask might easier to implement the upgrade feature.

**Comment by vitorgalvao** [comment]
Ah, I see what you mean: the `outdated` verb itself. Apologies for my misunderstanding. This issue is now kind of a mess, so we should open a clear new one.

Please open a new issue and make the title `Need help implementing outdated verb`. On the text itself, please be as clear and detailed as possible, regarding what you’ve already looked into (if anything) and what do you need help with specifically. Start by [taking a look at the code itself](https://github.com/caskroom/homebrew-cask/tree/master/lib).

**Comment by WitzHsiao** [comment]
Thanks for your understanding. I will look it up and open a new issue. :+1:
