### ISSUE TITLE
CLI output colors are not visible enough on light themes

### ISSUE THREAD

**Issue by niksy** [caskroom/homebrew-cask#9349]
I’m using Solarized Light theme in Terminal and this is the current output I get:
![screen shot 2015-01-28 at 10 28 39](https://cloud.githubusercontent.com/assets/389286/5979155/75a135f2-a8a5-11e4-80b5-b53dc0712fec.png)

Highlighting that output I get this:
![screen shot 2015-01-28 at 10 28 56](https://cloud.githubusercontent.com/assets/389286/5979156/77aa9dac-a8a5-11e4-86dc-a5be105e9d1c.png)

Can this be adjusted to cover both light and dark themes? I don’t know which version of Cask introduced this change.

**Comment by rolandwalker** [comment]
Hi! Thanks for the report!

If the behavior recently changed, there was probably an oversight on my part in #8390 or #8402, which we can look for and try to repair.

Since it isn't likely that any one scheme shows up perfectly for all themes, it would be great if this was configurable, as you propose.  Thanks to the PRs above, we can finally control such things.  A `--no-color` option is an obvious choice, and I'm mentioning @ndr-qef here because we recently discussed the fact that we are overdue to support a `~/.brewcaskconfig` file.

As a workaround, if you pipe any command through `cat`, it will detect that there is no TTY, and elide the color codes:
```bash
$ brew cask install vivaldi | cat
```

You can also change the basic colors in Terminal preferences, but I agree that you shouldn't have to.

**Comment by niksy** [comment]
Oh, I didn’t know about the plans to have `.brewcaskconfig` file, that would definitely be great for this use case :)

**Comment by rolandwalker** [comment]
This is fixed in #9473 and will go into the next release.
