### ISSUE TITLE
Tests are passing that shouldn't

### ISSUE THREAD

**Issue by johntrandall** [caskroom/homebrew-cask#9546]
It seems that Travis is allowing formulas without app stanzas pass in Yosemite. 

see #9542

**Comment by rolandwalker** [comment]
Hi!

Thanks for opening an issue to track this.  I assume that this happened because Travis is not running Yosemite.

However, we recently added the ability to fake the OS X release with an environment variable (#8870).  So, we should be able to set up a matrix of environments to run on Travis that will provide sufficient testing.

**Comment by vitorgalvao** [comment]
Anyone knows if this is fixed?

**Comment by adityadalal924** [comment]
Multiple OSX versions testing added in https://github.com/caskroom/homebrew-cask/pull/16226 by @jawshooah.

Should be sufficient to mark the issue as closed.
