### ISSUE TITLE
issue installing cask/cycling74-max

### ISSUE THREAD

**Issue by chrisRidgers** [caskroom/homebrew-cask#9551]
Noob warning: not entirely sure I'm having an issue here, as I've only just got going with brew cask.

Couple of things I've noticed.

1.  Not the latest version of software, 7.0.1, has been released.

2.  No app link gets symlinked into ~/Applications.  

3.  pkg appears to run but I don't see any changes on my system.  There's no new executables on my path.  

Not sure what else to see, it looks like this cask is getting updated regularly/ recently, but doesn't seem to be giving me what I expect it to.

Cheers.

**Comment by chrisRidgers** [comment]
Just found it, package installs to /Applications rather than ~/Applications.

Is there a standard here?  Other casks so far have been symlinked into ~/Applications where as this package just creates a directory within the /Applications.  I get that that's what the official release does as well, but is there some way to tweak this behaviour?

**Comment by vitorgalvao** [comment]
I'm on a phone right now so I can't check everything, but yes, it should be expected.

We have no control over the installation of `pkg` casks since those can pretty much do what they like. They don't even have to install an app, and may do something entirely different. For that reason, they’ll install differently then other casks.

Regarding the outdated version, could you please open a new issue? Or even better, a PR (feel free to ask for help, if you need).

**Comment by chrisRidgers** [comment]
I will take another look tonight/ this weekend.

I was tweaking the rb file and got about as far as downloading the latest version, couldn't get the substring/ version name to expand correctly to the updated version.  Kept putting spaces in but I'll take another look with moar enthusiasm. :)
