### ISSUE TITLE
A problem of Chrome support 1Password

### ISSUE THREAD

**Issue by arcticlion** [caskroom/homebrew-cask#9598]
![](http://ww4.sinaimg.cn/large/8178ba0egw1ep9vm3zumaj20e00903zy.jpg)

How do i enter command elegantly to move Chrome.app to /Application?

**Comment by vitorgalvao** [comment]
The Google Chrome cask [warns you about problems](https://github.com/caskroom/homebrew-cask/blob/0ad977001c4dba60495a442e24ecdb7bc1edb2b5/Casks/google-chrome.rb#L28-31). Unfortunately, the resolution is out of our hands. In the future we’ll have a command to copy the bundles instead of linking them, but at the moment, if you want to do it, you’ll have to do it manually.
