### ISSUE TITLE
prevent brew cask install from asking for password at each install

### ISSUE THREAD

**Issue by ssbarnea** [caskroom/homebrew-cask#9913]
This is a feature request for preventing `brew cask install xxx` form asking for admin password at each install. It should be a configurable option that would disable this security feature which is decreasing the accessibility a lot.

**Comment by vitorgalvao** [comment]
it isn’t (shouldn’t be) asking for password at each install. When it needs your password, it follows the `sudo` rules.

Please explain your problem a bit better, and walk us through the steps that are giving you that many password prompts.

**Comment by tirekicker** [comment]
Here is an example:

brew cask install basictex
==> Caveats
To use basictex, you may need to add the /usr/texbin directory
to your PATH environment variable, eg (for bash shell):

  export PATH=/usr/texbin:"$PATH"

==> Downloading http://mirror.ctan.org/systems/mac/mactex/mactex-basic.pkg
######################################################################## 100.0%
==> Running installer for basictex; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
Password:
==> installer: Package name is BasicTeX-2014
==> installer: Installing at base path /
==> installer: The install was successful.
🍺  basictex staged at '/opt/homebrew-cask/Caskroom/basictex/latest' (96M)

It prompts me for a password for every cask I've tried:

basictex
vagrant
xquartz

**Comment by vitorgalvao** [comment]
@tirekicker All of those use `pkg` installers. That is supposed to happen in those cases. Try something that links an app, like `alfred`, and it won't ask for the password.

Closing.

**Comment by phinze** [comment]
So there's a technical possibility of accomplishing this with something like a [`setuid`](https://en.wikipedia.org/wiki/Setuid) "sudo helper" script. Basically you'd have the user authorize the `chown root:admin` + `chmod g+s` of a script like:

```bash
# (NOT REAL CODE)
/usr/sbin/installer -pkg $1 -target /
```
Then subsequent uses of the script catch the `setuid` and don't need sudo.

The thing you have to be _really_ careful about when using tools like this is that you don't provide an attack vector for arbitrary code execution as root. And given the fact that you're executing a `pkg` installer here, the surface area is pretty large. In order to even consider this we'd probably need to bake checksum verification and serious argument checking into the script.

Probably more trouble than it's worth in the short term, but worth noting that it's possible! :cactus:
